### ISSUE TITLE
CPU 100% used when many queries are planning.

### ISSUE THREAD

**Issue by hustnn** [prestodb/presto#10002]
As some of my queries may need several minutes to finish the planning, sometimes, all these queries (e.g., 50 queries) are all planning. Therefore, the server becomes very slow (half dead status) as the cpu utilization is very high.

Any approach to control the concurrency of planning?
Thanks.

**Comment by nezihyigitbasi** [comment]
You can configure [resource groups](https://prestodb.io/docs/current/admin/resource-groups.html) to control the concurrency of the queries. Also several minutes of planning seems too long, which version are you using? Some planning regressions have been fixed in the past releases I recommend you to try the latest release to see whether planning time gets better.

**Comment by hustnn** [comment]
I am using 0.195.

**Comment by electrum** [comment]
Can run “jstack” on the Presto process while this is happening and paste the result here? That should give us an idea of what is going on.

**Comment by electrum** [comment]
Also, if you can, please post an example query that takes several minutes to plan. This should not happen.

**Comment by zhaiyuyong** [comment]
like  https://github.com/prestodb/presto/issues/9494 ？

**Comment by hustnn** [comment]
@electrum @nezihyigitbasi 

Sorry for replying late.  I am using the query in [9990](https://github.com/prestodb/presto/issues/9990).

We have improved the planning time after upgrading presto from 0.193 to 0.195. Before upgrading, it needs more than ten minutes to do the planning.
