### ISSUE TITLE
Driver may become blocked when yield signal kicks in

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#10003]
In `com.facebook.presto.operator.Driver#processInternal` there is a logic:
```java
if (!movedPage) {                         /// PLACE1
    List<Operator> blockedOperators = new ArrayList<>();
    List<ListenableFuture<?>> blockedFutures = new ArrayList<>();
    for (Operator operator : operators) {
        Optional<ListenableFuture<?>> blocked = getBlockedFuture(operator);
        if (blocked.isPresent()) {                         /// PLACE2
            blockedOperators.add(operator);
            blockedFutures.add(blocked.get());
        }
    }

    if (!blockedFutures.isEmpty()) {
        // unblock when the first future is complete
        ListenableFuture<?> blocked = firstFinishedFuture(blockedFutures);     /// PLACE3
        // driver records serial blocked time
        driverContext.recordBlocked(blocked);
        // each blocked operator is responsible for blocking the execution
        // until one of the operators can continue
        for (Operator operator : blockedOperators) {
            operator.getOperatorContext().recordBlocked(blocked);
        }
        return blocked;
    }
}
```

There are two problems here:

### Problem 1. `!movedPage` doesn't mean "no progress"

At `PLACE1`  we assume than if `!movedPage` then we're "basically blocked" and we need to identify why. However, it's completely legal for `operator.getOutput()` to return `null` even if some progress has been eg. when `com.facebook.presto.operator.DriverYieldSignal#isSet` kicks in.

This means a `Driver` may become blocked, waiting on some blocked operator higher up the pipeline (eg. Join's probe side), but it should not be. This may harm parallelism and in extreme case can potentially lead to starvation (when operator higher up is blocked on memory which is held by operator that didn't produce a page due to eg. yield signal).

### Problem 2. We evaluate isBlocked twice

At `PLACE2` we evaluate `operator.isBlocked().isDone()` second time. Any now-unblocked operator won't be part of future list we're waiting for (`PLACE3`). Thus there is a race condition: we didn't make progress because operator `A` was blocked (and some other operator `B` was blocked too). Operator `A` becomes unblocked and so we will wait for operator `B` _only_. In this case, we should not wait at all (it's like losing `Object.notify()` call).

cc @losipiuk @sopel39 @dain @highker

**Comment by sopel39** [comment]
That could potentially be one of the sources of query runtime non-determinism we have seen in our benchmarks.

**Comment by findepi** [comment]
Second part of the problem is easier to fix. I made a PR: https://github.com/prestodb/presto/pull/10004

**Comment by findepi** [comment]
> Problem 1. `!movedPage` doesn't mean "no progress"

It seems that what we need is a tri-state return value from `Operator.getOutput()`:
- operator did nothing (no progress, current meaning of `null` as far as `Driver` is concerned)
- operator produced a page
- (new) operator did progress, but didn't produce a page yet (e.g. yielded)

**Comment by sopel39** [comment]
It seems that `movePages` should just be set to `true` when `Page page = current.getOutput();` line is reached nevertheless if `page` is `null` or has 0 rows.

Basically operator is saying: I have stopped processing because I need more input (e.g: aggregation) or have yielded.
The operator doesn't intend to block the entire driver on some downstream operator (e.g: join).

**Comment by sopel39** [comment]
Fix proposal for 1) https://github.com/prestodb/presto/pull/10006

**Comment by highker** [comment]
I think making `getOutput` to return a state does make sense.

**Comment by findepi** [comment]
Another problem that I didn't think about this previously is that `Operator#finish()` can also make progress (while not producing any output).
See `HBO`: `finish()` is where, by necessity, all the spill magic happens.

Maybe, if some operator `isFinished` we should never call operators _before_ it? This would at least solve the problem of HBO: it's always the last one. If someone is calling finish on it, no earlier operators need to be called and we don't need to check their `isBlocked`..

**Comment by sopel39** [comment]
> * operator did nothing (no progress, current meaning of null as far as Driver is concerned)

But it still doesn't make sense to block the driver on the downstream operator. If the operator returned `null` and didn't make progress, then it should return undone future in `Operator#isBlocked`. Otherwise we can simply assume it made progress.

> `finish()` is where, by necessity, all the spill magic happens.

I think it's hacky contract to make actual work in `finish()` method. `finish()` should just signal operator and the operator should finish gracefully. What is missing here is some kind of `progress/process()` method that does actual work. `getOutput` could be such method but for HBO it's never called singe it's the last operator in pipeline.

I proposed similar concept in: https://github.com/prestodb/presto/issues/9470 and it's implementation is here: https://github.com/prestodb/presto/pull/9854/commits/589d0e7dcef91e6157682ab719940d5b0e7d4e2a. I would greatly appreciate a review because it really provides a clean contract for processing blocks which can be slowly incorporated into operators.

Basically the central processing method of `ContinuousWork` (vide really simplified `Operator`) is `process()` which returns `true/false` depending if work produced next elem/finished or has yielded/blocked. The state machine goes like that:
```
                                     ContinuousWork#process()
                                   /                      \
                                true                      false
                               /                             \
 work is finished or element is ready             work has yielded or is blocked
   |                         |                      |                  |
if not finished get elem     |             if blocked wait for future  |
                             |             then call process() again   |
                if finished then done!                                 |
                                                      if yielded just call process() again
```

**Comment by sopel39** [comment]
> See HBO: finish() is where, by necessity, all the spill magic happens.

What if for last operator in pipeline we call some kind of `process()` method instead of `getOutput`. Why exactly HBO `finish()` is a problem?

**Comment by findepi** [comment]
> But it still doesn't make sense to block the driver on the downstream operator. If the operator returned null and didn't make progress, then it should return undone future in Operator#isBlocked. Otherwise we can simply assume it made progress.

This is not that simple. Consider a `FilterOperator`. What should it return when it didn't receive any input yet?
Currently it returns _not blocked_, but `getOutput()` returns null. 
We can say, "hey, let's return _blocked_ until `addInput()` is called", but then we need change `Driver` logic: driver will never call `addInput()` on a blocked operator.

> What if for last operator in pipeline we call some kind of process/progress() method instead of getOutput. 

You probably meant "instead of _`finish()`_.
New method doesn't change the game, does it? You would still need to know whether `process()` made some progress

> Why exactly HBO finish() is a problem?

Consider a pipeline `[ A, B, HBO ]`.
`A` is blocked (e.g. on remote sources).
`B` is done (it was `LimitNode`, so it ended sooner than `A` ended)
`HBO` has spilled and needs repeated calls to `finish()` to do the (async) unspilling and produce a lookup source.

Now, `Driver` calls `HBO.finish()` once, `HBO` initiated unspilling.
`Driver` recognizes that no page has been moved (`A` is blocked, so won't produce a page; `B` is finished so won't produce a page either), so it goes on to produce a `blocked` future.
Now the important part:
* With current (racy)  code in `master`, the produced blocked future would _probably_ include `HBO.isBlocked()` (on unspilling) (unless unspilling future ends too quickly)
* With https://github.com/prestodb/presto/pull/10004 (as it is now), the produced blocked future would consider only `A.isBlocked()` (eg. on remote sources), which is not what we want to wait on.

**Comment by sopel39** [comment]
> This is not that simple. Consider a FilterOperator. What should it return when it didn't receive any input yet?

You have to take into account all operators up to (and including) `FilterOperator`. If none of them is blocked and at least one is not finished, then the pipeline up to `FilterOperator` has potential to progress. Therefore we should not block on downstream operator.

> New method doesn't change the game, does it? You would still need to know whether process() made some progress

Right, but we can assume that `finish()` made progress if the operator is not finished after `finish()` call. We also need to obtain blocked future after `finish()` call is made to wait on finishing operator (instead of a downstream one). Anyway, in practice, HBO is always last so we won't block on downstream operator anyway.

> Consider a pipeline [ A, B, HBO ].

We could have a `Operator::canProgress` method. If one of the operators return `canProgress()==true` then we can loop the entire `Driver` again. For instance this could help in a case like `PartialAggregation`. `PA` could dump data even though some upstream source operator is blocked. It could provide better CPU utilization. In practice, I am not sure if that a problem currently.

**Comment by dain** [comment]
I think it is clear (and has been for a long while) that the existing Operator model needs to be fully redesigned, but that is a massive undertaking.  This is why we have been making minor changes to the existing model.  

When we made the last change the heuristic of only stopping when some operators are blocked still worked reasonably well.  We had discussed adding a `canHaveOutput` method to for interruptible drivers to signal that they still can do work, but decided we didn't need it yet.  We could add something like that to work around the first problem `!movedPage doesn't mean "no progress"`.

The problem with `finish` on capstone operators like HBO is not something I have thought about before.  The `[ A, B, HBO ]` problem could be solved by something we have been considering for years, but never needed.  The idea is to remove operator below the finished operators from the chain.  This can reduce redundant calls and effectively dead operators, and can allow early state cleanup, but it makes the operator list mutable.  We didn't implement this because it was considered work without much benefit.

**Comment by dain** [comment]
Maybe the problem is we need to merge the concepts of needsInput and isBlocked... so a operator can be blocked waiting for an input page.   I haven't thought this all the way through, but I'm thinking of something like, we loop until all operators are blocked.  Some of the operators will be blocked on things outside of the driver stack (e.g., input buffers and output buffers), and some would be blocked on data from other drivers.
