### ISSUE TITLE
bad message 400

### ISSUE THREAD

**Issue by yangjun616** [prestodb/presto#10127]
sometimes wo get this exception:java sql.SQLException: query failed() Excepted response code to be 200 ,but was 400 HTTP/0.9.。I have not idea how it happend,who can help me
![1e2686ac2dbef4c983d1388a6c61b0e9](https://user-images.githubusercontent.com/32293670/37196999-ea7e2a1a-23b3-11e8-822e-6460dc88fcff.png)

or
 WARN    http-worker-495 org.eclipse.jetty.http.HttpParser       bad HTTP parsed: 400 Illegal character 0xA for HttpChannelOverHttp@44a1124f{r=51,c=false,a=IDLE,uri=null}
 WARN    http-worker-378 org.eclipse.jetty.http.HttpParser       bad HTTP parsed: 400 Unknown Version for HttpChannelOverHttp@9c05039{r=0,c=false,a=IDLE,uri=null}
WARN    http-worker-387 org.eclipse.jetty.http.HttpParser       bad HTTP parsed: 400 HTTP/0.9 not supported for HttpChannelOverHttp@28890230{r=10,c=false,a=IDLE,uri=null}
![1e2686ac2dbef4c983d1388a6c61b0e9](https://user-images.githubusercontent.com/32293670/37268814-c5f01ebe-2602-11e8-8e05-0465c5c484a6.png)

**Comment by nezihyigitbasi** [comment]
The HTTP client that sent this particular request uses HTTP/0.9 and the server returns an error saying that it's a bad request (status code 400). If the client uses HTTP/1.1 the problem should go away.

**Comment by yangjun616** [comment]
@nezihyigitbasi thank you very much ,i will try it

**Comment by yangjun616** [comment]
I think it isn't caused by client request,this happend in worker nodes

**Comment by yangjun616** [comment]
I think it isn't caused by client request,this happend in worker nodes
![1e2686ac2dbef4c983d1388a6c61b0e9](https://user-images.githubusercontent.com/32293670/37268806-b91b0b18-2602-11e8-90a2-9ee2cd3fefbd.png)

**Comment by nezihyigitbasi** [comment]
The message logged by the Jetty `HttpParser` is from the HTTP server running on that particular worker node, and what it tells is a client sent a bad request to this worker and the server failed parsing it and returned 400, which is the response code for a bad request -- so this is caused by a client.

Here the client can be the coordinator, some other worker, or some other client as I don't know the details of your system. To find out who is sending these bad requests you can take a look at the HTTP request logs on this worker (Presto HTTP servers log each processed HTTP request in a log file named `http-request.log`) .

**Comment by findepi** [comment]
Answered.
