### ISSUE TITLE
Raptor shard-cleaner-backup threads running into infinite loop

### ISSUE THREAD

**Issue by nmahadevuni** [prestodb/presto#10270]
Hi, We are on version 0.162. We are using Raptor with a backupstore and run in to this problem. When something goes wrong with a backup shard because of which the shard-cleaner-backup thread would not be able to delete a backup shard, it will run in to infinite loop in ShardCleaner.java:cleanBackupShards() method logging the error 
log.error(e, "Error cleaning backup shard: %s", uuid);

The below line at the beginning of this method will again get the shard uuid for which we encountered error and again add to the set of shards to be deleted.
uuids = dao.getCleanableShardsBatch(maxTimestamp(backupCleanTime));

So, the exit condition for the thread would never be met.
if (uuids.isEmpty() && processing.isEmpty()) {
                break;
            }

I know this probably would have occurred due to some manual intervention in the backupstore. But, should there be a guard against such conditions?

**Comment by nmahadevuni** [comment]
Hi, after I determined that we didn't manually intervene with backupstore, after some code browsing, I had a theory that I tested out. The thread running into infinite loop can be reproduced using below steps.

1) Run a INSERT INTO RAPTOR_TABLE SELECT * FROM ANOTHER_TABLE. Run this in such a way that it fails or force it to fail.
2) If the above operation fails, then the corresponding transaction is marked as unsuccessful.
3) Whatever the shards are created in this transaction will be in "created_shards" metadata table.
4) Transaction will be rollback. During this, the staged files and their backup files both are deleted??
5) When ShardCleaner thread kicks off, they start with cleaning old shards which were created as part of unsuccessful transactions. As part of this, it will move all shard entries from "created_shards" metadata table to "deleted_shards" metadata table. But these shards were already removed in step 4 during rollback.
6) ShardCleaner sees that deleted_shards has some entries which it needs to cleanup which it never finds and deleteShard() raises an exception, and runs finally thread runs into infinite loop.

In our case, we were using a custom backupstore and backupstore.deleteShard() was throwing an exception. 
But this problem can be reproduced by using FileBackupStore.  In the normal case, since deleteShard for FilebackupStore is using deleteIfExists() whose return value is ignored. After the transaction failure, and before the cleaner threads kicks in, please remove permission for the user(which presto server is running as) for the "backup.directory". So, the next time backupstore.deleteShard() is called, it will throw an IOException and threads runs in to infinite loop.

**Comment by electrum** [comment]
This is an interesting case.

First off, the `BackupStore.deleteShard()` method contract is that it should succeed if the file does not exist. I had hoped this was clearly captured by the Javadoc. There are many scenarios where we delete a file that was already deleted or never existed. The method should only throw if there is an error doing the check/delete (e.g., the request to a remote system times out). 

Given the contract, we don't expect repeated/permanent failures for a specific file (e.g., some file that is corrupt or has bad permissions). Doing so would require much more sophisticated deletion queue management. It's not clear that this complexity is worthwhile. My initial thought is to handle this in the backup store: have the `deleteShard()` method skip the error and pretend it was deleted (and log some information so an operator can investigate).

The infinite loop part is more concerning, since this can happen many times per second, and it blocks the cleaner from making progress. The MySQL covering index `(delete_time, shard_uuid)` on the `deleted_shards` table should cause the rows to always be returned in the same order based on deletion time. This means we will repeatedly get the same bad file.

One solution is to have the cleaner keep a list of "bad" files and to exit if all files in the batch are bad. This prevents it from failing in a tight loop, which can also happen if there is an overall problem with the backup store (e.g., the remote system is unavailable).

**Comment by electrum** [comment]
The cleaner ignores the return value from `deleteShard()` because it doesn't care if the file was actually deleted. All that matters is that, after the method returns, the file no longer exists and thus can be removed from the deletion queue.

We have a tiered backup store that stores large files in Gluster and small files in sharded MySQL (Gluster is on hard drives and MySQL on flash, so MySQL handles many small IOs better). To avoid keeping track of which files are where, we simply check MySQL first. On delete, the MySQL store tells us if it actually deleted the file. If so, we know it wasn't on Gluster, so we can avoid the more expensive delete call to Gluster.

**Comment by nmahadevuni** [comment]
@electrum  : Thanks so much for the detail on this. Keeping a bad file list and exiting the loop if none of them were processed looks simple. With that and honoring the deleteShard() method contract will solve this.
