### ISSUE TITLE
Insert into json table

### ISSUE THREAD

**Issue by bdm123** [prestodb/presto#10394]
Hi,

Trying to test a read/write on a simple JSON table but get the error below when performing an insert. Any ideas why inserting/writing data fails?

```
hive> CREATE TABLE json_test (
 Test string
 )
 ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
 STORED AS TEXTFILE;
```

 
```
presto:default> insert into temp.json_test select '1';
Query 20180406_204605_00004_q3en7 failed: Output format org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat with SerDe org.openx.data.jsonserde.JsonSerDe is not supported
com.facebook.presto.spi.PrestoException: Output format org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat with SerDe org.openx.data.jsonserde.JsonSerDe is not supported

```

Also, running the insert through hive worked fine and subsequently reading through presto worked. Writing seems to be the issue. Any ideas?

Thanks

**Comment by bdm123** [comment]
Is the simple answer that it is not currently supported in presto? Seems this would be a common and useful task.

**Comment by dain** [comment]
Presto supports the Hive standard JSON table serde `org.apache.hive.hcatalog.data.JsonSerDe`.  I've never seen `org.openx.data.jsonserde.JsonSerDe` before.  Is that a new thing?

**Comment by bdm123** [comment]
Hi @dain - This was resolved by switching to the correct serde as you advised.  I came across the openx serde in amazon's documentation for presto-athena. Thank you!

**Comment by yufengJ** [comment]
@dain Is there a reason Presto only support Hive standard JSON serde `org.apache.hive.hcatalog.data.JsonSerDe`? In other words, why does Presto bind serde to [HiveStorageFormat](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HiveStorageFormat.java) enum? My guess is because the writer needs to know [estimatedWriterSystemMemoryUsage](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HiveStorageFormat.java#L108) for each Serde so it could do memory related optimizations. 

I am thinking if Presto would be able support Create-Table-As-Select with customized serde and Insert into table with customized serde.

**Comment by dain** [comment]
We test everything we support, otherwise we have lots of problems supporting the community.  We can add more formats as needed, but we try to stick to the big systems that people use.
