### ISSUE TITLE
Remove the VisibleForTesting annotation in createSqlTaskExecution method in the class of SqlTaskExecution

### ISSUE THREAD

**Issue by leoluan2009** [prestodb/presto#10404]
hi,

The exist of the @VisibleForTesting annotation is mistake in the method of createSqlTaskExecution() in  SqlTaskExecution class. Because the method of createSqlTaskExecution() is the only way which can create a instance for SqlTaskExecution class. So this method is not only used by test, and we should remove the @VisibleForTesting annotation.

please correct me if i am wrong, thanks

**Comment by mbasmanova** [comment]
@haozhun @leoluan2009 Indeed, looks like SqlTaskExecution#createSqlTaskExecution() is used in production code.

@leoluan2009 Would you like to submit a patch?

**Comment by leoluan2009** [comment]
@mbasmanova , thanks for your reply, I will submit a patch for this issue.

**Comment by martint** [comment]
You're right about the annotation being used incorrectly here, but not for the reason you stated. That annotation is not intended to say that some code is used *only* in testing. It means that the visibility of the method not as constrained as it could be for the purpose of testing. For example, a method that could be private or package-private might need to be made public so that tests in other packages can access it.

**Comment by findepi** [comment]
Fixed in https://github.com/prestodb/presto/pull/10421
