### ISSUE TITLE
Optimizing SymbolAllocator

### ISSUE THREAD

**Issue by Praveen2112** [prestodb/presto#10408]
Instead of creating `HashMap<Symbol, Type> ` can we replace with a PMap<Symbol, Type> from PCollections which is also used in Cost Based Optimizer. The problem in using HashMap is that for queries which have more joins (10) involved and each table involved in the above query if it has more columns say (700), the Map size varies from (7000-15000). Each time `ExpressionAnalyzer` is invoked it might result in copying the entire map (for some optimizers) and thus increases the overall planning time . One solution is to refer the same HashMap instead of using  `ImmutableMap.copyOf(map)` but it is a not cleaner one. By using PMap I think we can reduce the copying time. Would there be any issues in replacing the `HashMap` with `PMap` ?

**Comment by sopel39** [comment]
This could be a good idea provided that there are numbers that back performance improvements. Keep in mind that there is `SymbolAllocator#getTypes` which exposes the underlying types map (without copying). We could maybe wrap types map into some kind of class (e.g: `SymbolTypes`)  so that the underlying map implementation (`PMap` vs `HashMap`) is not exposed.

**Comment by findepi** [comment]
I think this has been addressed by https://github.com/prestodb/presto/pull/10994
