### ISSUE TITLE
Raptor shard size limited by max buffer size

### ISSUE THREAD

**Issue by nmahadevuni** [prestodb/presto#10449]
Hi,
We observed that the Raptor ORC shard size is limited by `storage.max-buffer-size` rather than `storage.max-shard-size` OR `storage.max-shard-rows`. 

We load few hundred GBs data into Raptor daily and always end up with more shards than we assume. One problem we face with this is that our custom backupstore has limited number of objectids that it can create and we seem to be using them up very fast. 

For example, when we set
```
storage.max-buffer-size=256MB
storage.max-shard-size=1GB
```

The ORC shard size is always ~22MB compressed which is 220MB uncompressed which seems to be only limited by max-buffer-size. If it was limited by max-shard-size, we should have seen ~100MB compressed sizes for the shards.

I looked at the code and saw that the condition that leads to this is in the following method in `presto-raptor\src\main\java\com\facebook\presto\raptor\util\PageBuffer.java`
```
private void flushIfNecessary(int rowsToAdd)
    {
        if (storagePageSink.isFull() || !canAddRows(rowsToAdd)) {
            flush();
        }
    }
```
`storagePageSink.isFull()` returns false since the `max-shard-size` hasn't been reached yet. `canAddRows()` returns false since it checks whether the new set of rows can be added to the buffer limited by `max-buffer-size` and `flush()` is called to materialize the shard on disk.  Changing the `||` condition in the if condition in the above method to `&&` would resolve this according to the actual intent of these config parameters. Is it like this for some other reason? Appreciate your help in this regard.

**Comment by electrum** [comment]
These are actually two entirely different things. `max-shard-size`, along with `max-shard-rows`, limits the size of a shard/file. There are several reasons to limit the size:

* We generate one split per file and each split is processed by one split, so the time taken to process a split determines the minimum latency of a query.
* We don't want to be transferring huge files to/from the backup store. This is especially true when recovering data to different machines after a machine failure.
* If all the data for a table is in a few files, there won't be enough parallelism (too few threads per machine).

When writing, we buffer data in memory, which is what `max-shard-size` controls. This buffering is necessary for sorting (via the `ordering` table property). If there is a temporal column (via the `temporal_column` table property), then we split up data by date, and thus the max buffer size is shared across the buffers for all dates.

Because this buffer is storing uncompressed data, the written files will likely be much smaller (often 10x or more). However, compaction does not use a buffer (it does a merge sort), so files can become larger.

**Comment by electrum** [comment]
I was just reading the code and realized that we still buffer all of the uncompressed data even if we're not sorting rather than eagerly flushing it to the writer. I can't remember if that is intentional, but it may have been, as it's a safe way to guarantee memory usage. If we have many open writers, due to multiple buckets and/or dates, it's difficult to control memory usage, as Raptor is using the Hive ORC writer.

We are using the Presto ORC writer in Raptor v2, so when not sorting, there is the potential to use the writer's compressed in-memory buffer and thus end up with larger files. Though that won't matter much for our usages of Raptor, as people almost always specify sort columns for tables.

**Comment by nmahadevuni** [comment]
@electrum : I understand why the shard size is limited to a manageable size for parallelism. My question is that the final uncompressed shard size that is materialized to disk is being limited by max-buffer-size rather than max-shard-size along with max-shard-rows as you mentioned. In the given example,
storage.max-buffer-size=256MB
storage.max-shard-size=1GB
storage.max-shard-rows=10000000

The final shard's uncompressed size is nowhere close to 1GB and it definitely is not having anywhere close to 10M rows that I specified in storage.max-shard-rows.. Uncompressed shard size is always less than max-buffer-size. Going by your explanation, the shard's uncompressed size should be ~ 1GB.
