### ISSUE TITLE
Parsing/analysis time might exceed client-side query submission timeouts

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#10597]
We should send an HTTP response accepting the query before starting to analyze (or perhaps even parse) the query. This might indicate we need a new query state.

**Comment by dain** [comment]
We need this anyway to make the first POST retryable.  My proposed solution is:

* POST to /v1/statement should save the query in StatementResource
* Only, when client GETs the first url, we submit the query to the QueryManager

This fixes the problem in this issue, and makes the first POST retryable, because we don't start any work until the client acknowledges the queryId assignment (by fetching the URL).

**Comment by raghavsethi** [comment]
I believe this was addressed.
