### ISSUE TITLE
Fix property derivations for joins

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#10820]
A discussion in #10731 revealed that property derivations logic for joins in `PropertyDerivations.Visitor#visitJoin` is incorrect. 

The behavior should be as follows (as discussed in #10814):

  | Global | Local | Constants
-- | -- | -- | --
INNER | ALL | ALL(probe) | ALL(probe + build)
INNER + spill | ALL | Constant(probe) | ALL(probe + build)
LEFT | ALL(probe) | ALL(probe) | ALL(probe)
LEFT + spill | ALL(probe) | Constant(probe) | ALL(probe)
RIGHT | ALL(build) | Grouping(probe) + SortingNullsLast(probe) | ALL(build)
FULL | SingleStream(probe) | Grouping(probe) + SortingNullsLast(probe) | NONE
CROSS | ALL | None | ALL(probe + build)

* **Global** describes partitioning across streams (nodes or threads within a single node)
* **Local** describes properties of a single stream
* **Constants** lists columns with constant values within a single stream
* RIGHT and FULL joins don't support spill

Currently, `PropertyDerivations.Visitor#visitJoin` is implemented as follows (discrepancies with the above are highlighted in bold):

  | Global | Local | Constants
-- | -- | -- | --
INNER | **ALL(probe)** | ALL(probe) | ALL(probe+build)
INNER+spill | **ALL(probe)** | Constant(probe) | ALL(probe+build)
LEFT | ALL(probe) | ALL(probe) | ALL(probe)
LEFT+spill | ALL(probe) | Constant(probe) | ALL(probe)
RIGHT | ALL(build) | **NONE** | ALL(build)
FULL | SingleStream(probe) | **NONE** | NONE
CROSS | **ALL(probe)** | **ALL(probe)** | ALL(probe+build)

The discrepancy for the CROSS join is a correctness issue: local properties for CROSS join are stronger then they should be. This is being fixed in #10731 . Other discrepancies are weaker then they could be, hence, represent an opportunity for optimizations.

CC: @sopel39 @findepi @martint

**Comment by sopel39** [comment]
I will also add my comment from https://github.com/prestodb/presto/pull/10822 here:

Spilling join not preserving grouping could be a problem because then streaming aggregation will never happens for correlated subqueries and spill enabled.
I wonder how this could be addressed, e.g: make sure spill doesn't happen mid-group.

**Comment by findepi** [comment]
> I wonder how this could be addressed, e.g: make sure spill doesn't happen mid-group.

you can't request that. Spill can happen even during processing of a single row (when 1 probe row matches multiple build rows). This is because otherwise we would need long-lived locks in the lookup partitions, longer then the duration of a call to Operator. This would affect our ability to revoke memory ASAP and could lead to OOM.

**Comment by mbasmanova** [comment]
Theoretically speaking, at some point, one could imagine a cost-based optimizer being able to evaluate memory usage of spillable join with non-streaming aggregation and non-spillable join with streaming aggregation and choosing which one is better.
