### ISSUE TITLE
cast('' as bigint) throw an Exception!

### ISSUE THREAD

**Issue by xingnailu** [prestodb/presto#10976]
hi~, my presto version is 0.204. and I query like `select cast(some_field as integer) from table`, it return NULL that the field is NULL,  but when the field is an empty string, presto will throw an exception like : 
```
Query failed (#20180704_084146_00469_t3czj) in hive://purple: Cannot cast '' to BIGINT
 com.facebook.presto.type.VarcharOperators.castToBigint(VarcharOperators.java:177) 
java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) 
java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:649) 
................
```

and I filled my field with empty string in most case to prevent null point exception.  
is this a feature that presto plan to fix ? (is this section, hive and spark-sql will return NULL )

**Comment by findepi** [comment]
This is the expected behavior, just like with `CAST('a' AS INTEGER)`.
You can handle this with a `case` construct or `try_cast` (https://prestodb.io/docs/current/functions/conversion.html#try_cast).

> I filled my field with empty string in most case to prevent null point exception.

I didn't understand this part. Were you experiencing some NullPointerExceptions from Presto when the fields were NULL?
