### ISSUE TITLE
Correlated subqueries does not handle coercion

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#11026]
```
presto:tiny> SELECT 1 FROM nation n WHERE 1 = (SELECT n.nationkey);
 _col0
-------
     1
(1 row)

Query 20180712_134539_00036_qa8mt, FINISHED, 1 node
Splits: 20 total, 20 done (100.00%)
0:00 [25 rows, 0B] [243 rows/s, 0B/s]

presto:tiny> SELECT 1 FROM nation n WHERE 1 = (SELECT cast(n.nationkey as decimal(7,2)));
Query 20180712_134545_00037_qa8mt failed: line 1:35: Given correlated subquery is not supported
SELECT 1 FROM nation n WHERE 1 = (SELECT cast(n.nationkey as decimal(7,2)))
```

As you could see above when correlated predicate requires coercion then correlated subquery does not work.

CC: @anusudarsan

**Comment by atris** [comment]
The default cast specification works even for this case:

presto:tiny> SELECT 1 FROM nation n WHERE 1 = (SELECT cast(n.nationkey as decimal));
 _col0 
-------
     1 
(1 row)

Query 20180716_171442_00003_xdw4b, FINISHED, 1 node
Splits: 20 total, 20 done (100.00%)
0:00 [25 rows, 0B] [183 rows/s, 0B/s]

The reason why this is failing is because for decimal(7,2), the subquery's projections are of order:

"expr_3" -> "CAST("expr" AS decimal(12,2))"
"expr" -> "CAST("nationkey" AS decimal(7,2))"

Whereas for the default cast specification, the subquery has a single projection:

"expr" -> "CAST("nationkey" AS decimal)"

The extra "expr_3" projection in the first case does not allow removal of the LateralJoin, thus the query errors out during checking of the subquery plan.

Is the "expr_3" coercion really needed, or is it a bug in the analyzer?

@kokosing

**Comment by atris** [comment]
@kokosing No, none of the rules is firing for the rogue query, right upto the point where t uery plan validation errors out after seeing the lateral join

**Comment by atris** [comment]
@kokosing Please see the fix at:
https://github.com/atris/presto/tree/coercion_fix1

After the fix, The query plans are:

   explain SELECT 1 FROM nation n WHERE 1 = (SELECT cast(n.nationkey as decimal(7,2)));
                                                                                
    --------------------------------------------------------------------------------
    - Output[_col0] => [expr_4:integer]                                            
           Cost: {rows: 1 (5B), cpu: 455.00, memory: 0.00, network: 5.00}         
           _col0 := expr_4                                                        
       - RemoteExchange[GATHER] => expr_4:integer                                 
               Cost: {rows: 1 (5B), cpu: 455.00, memory: 0.00, network: 5.00}     
           - Project[] => [expr_4:integer]                                        
                   Cost: {rows: 1 (5B), cpu: 455.00, memory: 0.00, network: 0.00} 
                   expr_4 := 1                                                    
               - ScanFilterProject[table = tpch:tpch:nation:sf0.01, originalConstr
                       Cost: {rows: 25 (225B), cpu: 225.00, memory: 0.00, network:
                       nationkey := tpch:nationkey                                
                                                                                
  (1 row)

    presto:tiny> SELECT 1 FROM nation n WHERE 1 = (SELECT cast(n.nationkey as decimal(7,2)));
     _col0 
    -------
       1 
    (1 row)

**Comment by kokosing** [comment]
Typically we open a PR to collect the feedback. We do it even for Work-In-Progress kind of PR (please see https://github.com/prestodb/presto/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+wip).

**Comment by atris** [comment]
Thanks for reviewing.

I am not able to open a PR since I have not signed the CLA yet (should happen in a few days). Apologies for the workaround

**Comment by kokosing** [comment]
As I understand CLA is needed to merge the code not to share it.

**Comment by atris** [comment]
Ah, thats good to know, thanks

**Comment by atris** [comment]
@kokosing I have fixed the comments you gave, please take a look and let me know.

**Comment by atris** [comment]
@sopel39 Thanks for mentioning it. This PR does not fix it, I will raise another PR to fix this one.
