### ISSUE TITLE
Presto Create table on HMS

### ISSUE THREAD

**Issue by BlueStalker** [prestodb/presto#11102]
In com.facebook.presto.hive.HiveMetadata#createTable, 
If it is trying to create a new table, it will try to call com.facebook.presto.hive.LocationService#forNewTable to create a temp hdfs dir like "/tmp/presto-$user-$random_uuid", I wonder what's the purpose to do this?
Is it trying to handle things like "create table from select" ?

**Comment by dain** [comment]
When creating a new table or partition in Hive there are conventions for directory locations, but in some environments there is a desire for programatic control over these decisions.  For example at Facebook, we use random names for partition directories, so we don't need to use temp directories or move file commands.  This is implemented with an extension of the Hive connector that replaces the LocationService.

BTW for the future, we prefer questions like this on the mailing list instead of in Github issues.
