### ISSUE TITLE
Presto JDBC LDAP - bad credentials can still connect (just at query time it gives invalid credentials error)

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#11299]
Right now when LDAP enabled a jdbc connection can be initiated (expecting the connection to error out) rather than allowing connection then showing an error once query is run.

**Comment by electrum** [comment]
This is expected behavior given that the Presto client protocol is connection-less. The driver could make an extra call to the server to validate credentials when the JDBC connection is created, but this seems wasteful since we expect you will execute a query immediately afterwards (why else would you create a connection?).

Is this actually causing a problem for you, or is the behavior simply unexpected? (I agree it is unexpected compared to other databases)
