### ISSUE TITLE
please allow regular expressions as string

### ISSUE THREAD

**Issue by ron819** [prestodb/presto#11301]
I want to do the following:

`select position( '/s/' OR '/f/'   in '.../f/...')`

This is not SQL syntax but it explain the issues. While most DBs allows reg-expresions to define strings Presto does not allow this. Presto offers limited [regex](https://prestodb.io/docs/0.172/functions/regexp.html) support.

There is no way to find location of more than one sub string in Presto which is very problematic.

My issue could also be solved if you will add to https://prestodb.io/docs/current/functions/regexp.html
another function that returns the first location of sub-string in the string.
very similar to `regexp_like`  but return `int` and not `boolean`.

**Comment by haozhun** [comment]
It looks like there are some typos in your example.  I guess what you meant is something like `select position(/s/ OR /f/ in '...f...')`?

According to my limited research. MySQL and PostgreSQL support `POSITION (... IN ...)`, but neither allows `OR`. SqlServer and Oracle uses `charindex` and `instr` functions respectively, and doesn't support `OR` either.

This syntax also provides little value. The user can simply use `/s|f/` instead.

`POSITION` is a special syntax specified by SQL spec. The syntax of `position(/a/ in '...')` is a non-ambiguous extension, which would likely be doable. However, in general, special syntax like this requires a lot more work to deal with, and provides little extra value over regular functions.

Your post brought up the concern that none of Presto's regex function provides a `regexp_find` like capability (returning the matching position). `regexp_like` can be implemented more efficiently than `regexp_find` due to strict requirements in regex specification on tie-breaking (and as demonstrated by the RE2 regular expression engine). It is likely that we left out `regexp_find` for two reasons: 1) in the hope that user won't misuse it when `regexp_like` is sufficient; 2) no one needed it.

This is something we could add if there is a legitimate need.

Why do you need a numerical answer instead of a boolean answer for your regular expression matching need?

**Comment by ron819** [comment]
@haozhun  Hi, In my example the string is actually URL
I want to find if the URL contains one of these strings:  '/s/'  or  '/f/' in 'https://www.my.com/.../f/...' and if so to return the position of it in the URL.
but my is a specific example if we look at the bigger picture..

Both PostgreSQL  and MySQL allows you much more functionality which can be used to work around to solve such problems. 

For example PostgreSQL has: 
SELECT foo FROM regexp_split_to_table('the quick brown fox jumps over the lazy dog', E'\\s+') AS foo;
  foo   
-------
 the    
 quick  
 brown  
 fox    
 jumps 
 over   
 the    
 lazy   
 dog    
(9 rows)

**This can't be done with Presto.**

Note that the 2nd argument is regular expression. Basically they have functions which accept regular expressions and allow to work with them. Presto has not even a single function which allows to give regular expression as argument. 


To answer your question: 
I need numerical value because I'm required to parse the string and do many sorts of checks over it.
What programmers usually do is to write a store procedure with high level language (for example PL/Python in PostgreSQL and then you get Python functionality in your PostgreSQL session. This gives you the full control with manipulating strings. Sadly, this is not doable with Presto over Amazon Athena. Which is why I must use Presto SQL build-in functions.  

The work around in such case is usually to ask developers to give you these information in advanced. For example: add column and stream into it the value that you need (I assume this is why you didn't hear about these problems before - because solution such as this is relatively easy). However in my case I have no control over the data I receive nor I can ask for changing it. 

`regexp_like(string, pattern) → Boolean`   is great but sometimes (like in my case) you don't want to know only if it exists you also want to know where. 

**I suggest the following:**

1.  `regexp_like(string, pattern) → Boolean`   to `regexp_like(string, pattern) → Boolean` 
Returns the number of occurrences of the pattern in the string. 0 is equal to false, 1 or more is equal to true. This will have more value as it will also give the number of occurrences. 

2. `regexp_find(string, pattern) → integer`  returns the position of the first occurrence of pattern in string.
