### ISSUE TITLE
Error reading float column type in hive using parquet

### ISSUE THREAD

**Issue by puneetjaiswal** [prestodb/presto#11356]
We encountered this error when tried to read float column from a hive table:
```
Query 20180820_203000_01686_e7ind failed: java.lang.UnsupportedOperationException
com.facebook.presto.spi.type.DoubleType
com.facebook.presto.spi.type.AbstractType.writeLong(AbstractType.java:111)
com.facebook.presto.hive.parquet.reader.ParquetFloatColumnReader.readValue(ParquetFloatColumnReader.java:34)
```
Please take a look.

**Comment by dain** [comment]
This class of errors is commonly caused by schema migration.  Specifically, the original file was likely written with a float type, but the data is in a partition where the column has a double type.  Current, the parquet reader in Presto does not support this kind of file level implicit coercion.  Someone could implement the expected file level coercions (I assume there is a spec somewhere).

**Comment by puneetjaiswal** [comment]
This makes sense @dain , thanks for the explanation. Can you please point me to the spec, I would be happy to fix this.

**Comment by findepi** [comment]
There is an old PR addressing a few coercion / schema evolution aspects -- https://github.com/prestodb/presto/pull/9422

**Comment by vii** [comment]
as Hive can read tables where the underlying Parquet partition file does not match the schema, it seems like it would be less surprising if Presto could too. In the case that the conversion is not supported, the error message could be updated to make it clear that it is a disagreement between the Parquet schema and the metastore schema -

**Comment by findepi** [comment]
> as Hive can read tables where the underlying Parquet partition file does not match the schema, it seems like it would be less surprising if Presto could too

@vii yes, this is the desired state. We're just not there yet.
