### ISSUE TITLE
Presto plugin requiring javax.ws.rs-api-2.x; classes conflicting with presto-root

### ISSUE THREAD

**Issue by gray-eb** [prestodb/presto#11419]
Hello,

I have created a presto-atlas plugin. When trying to start a presto-server with this plugin which requires javax.ws.rs-api-2.1, I am running into this issue:

`java.lang.LinkageError: ClassCastException: attempting to castjar:file:/home/gray/presto-server-0.205/lib/javax.ws.rs-api-2.1.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/mnt/var/lib/presto/data/plugin/presto-event-listener/javax.ws.rs-api-2.1.jar!/javax/ws/rs/client/ClientBuilder.class`

Apparently two different classloaders are trying to use this class, but I am unclear on why it is trying to cast in the first place. When I mark the scope for javax.ws.rs-api-2.1 as 'provided', the presto-maven plugin complains, but I am able to silence it using a custom option. When I do this, my plugin cannot find the classes at runtime, but when I don't mark as provided, the classes conflict at runtime. Whats the deal?! Has anyone run into this before?

**Comment by electrum** [comment]
Plugins have their own class loader which only allows classes from plugin, plus Presto SPI and related classes. Classes in packages like `javax.ws.rs` would not be visible to plugins, which is why they can't be found if you mark the dependency as `provided` (that cause Maven not to include it in your plugin).

I looked into `ClientBuilder.newBuilder()` and it seems the problem is that `FactoryFinder.find()` is using the thread context class loader to find the client builder implementation. The context class loader should be null by default, which will use the system class loader, not the plugin class loader.

You should be able to fix it by setting the context class loader to be the plugin class loader:

```java
public class MyEventListener
        implements EventListener
{
    private final ClassLoader classLoader = getClass().getClassLoader();

    public void queryCreated(QueryCreatedEvent queryCreatedEvent)
    {
        try (ThreadContextClassLoader ignored = new ThreadContextClassLoader(classLoader)) {
            ... handle event here ...
        }
    }
}
```

A more general solution would be to create a `ClassLoaderSafeEventListener` wrapper, similar to `ClassLoaderSafeConnectorMetadata`, which you would use to wrap your event listener implementation.

**Comment by electrum** [comment]
Please reopen if you need further assistance.

**Comment by gray-eb** [comment]
Thanks for the response, @electrum 

The example solution did not resolve the issue. I'll be trying to wrap with the ClassLoaderSafeEventListener within the next few days but wanted to let you know the first solution did not resolve the issue. Any ideas why it may have failed? 

I'll be implementing a Ranger plugin for Presto as well, and for this I'm having to import jersey classes for Ranger, which will conflict upon deployment.
