### ISSUE TITLE
Include overall cost in the query plan

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#11432]
Query plan needs to include overall cost in addition to individual components (e.g. cpu, memory, network).

```
Cost: {overall: TBD, rows: 1315221992446373376 (8192PB), cpu: 261208704032897070000.00, memory: 6323027921.00, network: 2543067552446.00}
```

CC: @rschlussel

**Comment by martint** [comment]
We made cost is a vector (cpu, memory, network) intentionally since there's no single way to combine them into one number. It's also not clear what such number would mean to an end user (dimension and units) and how to use it two compare two queries. For instance, is 2x that number and indication of 2x the cost? Do two queries that have the same number cost the same?

**Comment by mbasmanova** [comment]
@martint Actually, CBO computes the overall cost as `75 * cpu + 10 * memory + 15 * network` and uses it to compare costs of different plans. (The multipliers are configurable.) Hence, it is useful to include the overall cost value in the plan. Otherwise, users need to lookup the multipliers and calculate it manually.

**Comment by findepi** [comment]
@mbasmanova you're right about current behavior of CostComparator. It applies linear combination to cost's dimensions (using configurable weights) and compares the results.
Note however, that this behavior won't last. For example, if I join a big table with a small one, I may choose to broadcast the small one. If, however, both tables are increased 10x, the small one will no longer fit into memory, won't be possible to broadcast. For these reasons, we need the following changes in the cost model:
- better estimation of memory cost. This should reflect max peak memory usage required for executing plan. Currently, we have no notion of which operations in a plan tree can run concurrently and which cannot, so we just estimate sum of peak memory usage per operator (as if everything was able to execute at the same time)
  - maybe we even need to distinguish per-node peak memory usage and global memory usage?
- better cost comparator, which does not use simple linear combination to cost's dimensions -- first refinement could be reject plans that would overrun memory limits -- that would mean we can choose a plan that has higher `75 * cpu + 10 * memory + 15 * network` because a plan with lower `75 * cpu + 10 * memory + 15 * network` was rejected.

**Comment by mbasmanova** [comment]
@findepi These are good points, but I feel they are not directly related to this issue. I'm having a hard time debugging cases when CBO didn't choose a better plan, in part because the plan doesn't show the actual `cost` that was used to make the decision. At the moment, I have to manually collect cpu/memory/network costs and run a formula over these. I'd like to eliminate this step by printing the overall `cost` in the plan (in addition to individual cpu/memory/network costs). This will become even more important as the cost model evolves and gets more complex.

As a side note, we are seeing that in many cases the broadcast join uses about the same amount of CPU as distributed join, a lot of memory, but results in drastically lower wall time. This is due to probe side having a severe skew (in distributed case a single node has to process all the rows for the skewed key, but in broadcast the rows are distributed evenly). At the moment, CBO is lacking capabilities to support these cases.
