### ISSUE TITLE
presto .210 query hangs forever

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#11442]
Am using Squirrel sql, seems like it generates this before actually running the query select * from hive.bob.asx_l

Below query hangs forever, if i kill it from the webui then i can run other queries

```
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE,
  TYPE_NAME, COLUMN_SIZE, BUFFER_LENGTH, DECIMAL_DIGITS, NUM_PREC_RADIX,
  NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB,
  CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE,
  SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_TABLE,
  SOURCE_DATA_TYPE, IS_AUTOINCREMENT, IS_GENERATEDCOLUMN
FROM system.jdbc.columns
WHERE TABLE_NAME LIKE 'asx_l' ESCAPE '\' AND COLUMN_NAME LIKE '%' ESCAPE '\'
ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION
```

**Comment by findepi** [comment]
> ` WHERE TABLE_NAME LIKE 'asx_l' ESCAPE '\' ... `

No surprise this is slow, because it has to list the tables to find the one matching `asx?l` "pattern".
I think, Squirrel's intention was to list columns of a single table already known by name, so `TABLE_NAME = 'asx_l'` (or using the declared escape character: `TABLE_NAME LIKE 'asx\_l' ESCAPE '\'`) would be more appropriate.

**Comment by tooptoop4** [comment]
@findepi still curious why presto takes so long to run that query? as system.jdbc.columns has less than 100k rows whereas presto can very quickly query tables with millions of rows.

**Comment by kokosing** [comment]
It is explained here: https://github.com/prestodb/presto/issues/6363
