### ISSUE TITLE
Expand support of types handled in generation of IO explain plan

### ISSUE THREAD

**Issue by JamesRTaylor** [prestodb/presto#11500]
The types supported when the IO explain plan is generated is limited to simple numeric and varchar types with other types causing an UnsupportedOperationException. In our use case, we're only interested in the columns being filtered on and whether it's an equality or range comparison. We use this information to track which columns are most frequently used in filters across all queries to drive recommendations for the optimal parquet sorting.

One possible solution is to conditionally not throw (based on a new FeaturesConfig?) and instead use the same mechanism as the explain plan to cast any constant to a varchar. See [here](https://github.com/prestodb/presto/pull/11049#discussion_r215084671) for some discussion that has already taken place.

cc @nishantrayan

**Comment by haozhun** [comment]
IO plan does not tell you what column is being filtered on. 

It only tells you what predicates the connector guarantees for data it produces (which is often the same as what predicates was successfully pushed down to the reader).

Due to a latent bug in pushing down predicates to table scans, other filters may show up in the IO plan. However, that was not intended and has since been fixed in 0.211.

**Comment by JamesRTaylor** [comment]
Thanks for the heads up, @haozhun. For our use case, we'd like to know which predicates were successfully pushed down to the reader (not other filters). Is this an appropriate use of the EXPLAIN IO feature?

Is [this](https://github.com/prestodb/presto/commit/c8f1b725fcff2b43364f5df710e8744dd5fcfb6f) plus the other commits you did that day the ones related to fixing this issue?
