### ISSUE TITLE
not all tables in information_schema is available in mysql catalog

### ISSUE THREAD

**Issue by kannan-aravind** [prestodb/presto#11509]
I am trying to query the information_schema tables from a mysql instance through presto. In mysql information_schema, there are 61 tables available for querying. 

"select * from information_schema.tables where table_schema = 'information_schema' "
if I run the above query in mysql directly, I get 61 tables 
![image](https://user-images.githubusercontent.com/4352709/45686839-c6bcf580-bb6a-11e8-9904-b46316195ff3.png)

However, if I run the same query through presto, I get only 5 tables
![image](https://user-images.githubusercontent.com/4352709/45686921-fcfa7500-bb6a-11e8-95c5-d02839659924.png)

It looks like the rest of the tables in information_schema is not even available for query. 
for example:
"select table_name from information_schema.key_column_usage where table_schema = 'adventureworksdw' "
when i run the above query on presto, I get a table does not exist error.

![image](https://user-images.githubusercontent.com/4352709/45687210-c3763980-bb6b-11e8-9334-db2e510f37f4.png)

Is this a mysql connector restriction or server restriction? I will be grateful for any help on this (will help me decide if I need to work around this for my project).

**Comment by findepi** [comment]
@kannan-aravind apologies, my previous answer is wrong.

The real reason is that "_connector_.information_schema" is a special schema that is builtin, generated _for_ a connector, based on the metadata it exposed to Presto engine.
Presto builtin information_schema contains the table you listed (schemata, tables, columns, views, table_privileges) and shadows mysql's information_schema, which cannot be queried.

As a workaround, you can create views exposing mysql's information_schema information and query those views in Presto.

**Comment by kannan-aravind** [comment]
@findepi : thanks for the info and workaround. 

Just wondering though, is this a limitation because the current builtin information_schema does not read the mysql information_schema for tables key_column_usage and likes or is that it cannot?

**Comment by findepi** [comment]
The builtin `information_schema` has nothing to do with MySQL's `information_schema`.  
In Presto, `mysql.information_schema` tables are populated from information retrieved from MySQL JDBC driver.
Since JDBC driver lists tables, columns and such, this is the _same_ information as in MySQL's `information_schema`,
but the retrieval path is different.
