### ISSUE TITLE
A few questions about the hive data source

### ISSUE THREAD

**Issue by hiliuxg** [prestodb/presto#11592]
Hello, I would like to ask a few questions about the hive data source?

1. How to calculate the number of splits, and the number of worker nodes, is it related to the number and the size of files in hive? Is there a configuration that can affect the splits and nodes?

2. In the first screenshot, what's  the difference between Input data and raw input data? Raw input data I know is the number of rows or size in hive files . 
In addition, what does blocked time mean, why is blocked time greater than elapsed time?

3. In the second screenshot, why is the memory and buffered is 0B? The buffered means cache ? What do the meanings of Q, R, and F in splits mean?

I hope to hear from you, thank you very much.

![blockedtime](https://user-images.githubusercontent.com/39675622/46156266-aba95e80-c2ab-11e8-8414-8e8cadf80154.png)
![blocked](https://user-images.githubusercontent.com/39675622/46156275-afd57c00-c2ab-11e8-932e-b7555b232f8a.png)

**Comment by dain** [comment]
> On Sep 27, 2018, at 8:21 AM, hiliuxg <notifications@github.com> wrote:
> 
> Hello, I would like to ask a few questions about the hive data source?
> 
> 	• How to calculate the number of splits, and the number of worker nodes, is it related to the number and the size of files in hive? Is there a configuration that can affect the splits and nodes?

Files are divided into `hive.max-split-size` sized spits (default 64MB).  The first `hive.max-initial-splits` splits (default 200) are `hive.max-initial-split-size` (default of half `hive.max-split-size`).

> 	• In the first screenshot, what's the difference between Input data and raw input data? Raw input data I know is the number of rows or size in hive files.

I’m not sure on this one, but IIRC, raw is the data pulled raw storage, and the other one is after is has been decoded in the input stage.  You get a big difference when you have compression, or stats that allow you to skip data sections.

> In addition, what does blocked time mean, why is blocked time greater than elapsed time?

Just ignore this. We are removing it.  It is the sum of any time any of the async tasks is blocked, so it is completely useless, because well, stuff is async.

> 	• In the second screenshot, why is the memory and buffered is 0B? The buffered means cache ?

The output line is the sum of data produced from that stage, whereas the buffered line is the data that is awaiting transfer to the next stage.

> What do the meanings of Q, R, and F in splits mean?

Queued, running, and finished.

**Comment by hiliuxg** [comment]
Many thanks for answering the question
