### ISSUE TITLE
Does presto can't be compatible with hive bucket table ?

### ISSUE THREAD

**Issue by Giant1** [prestodb/presto#11699]
**Use case** 
flume -> hive (bucket table) -> presto
 **error message**
presto:optimus> select sum(click) from default.rpt_effect_base_flume where pday=20181012 and phour=18;
Query 20181012_105812_03595_i4z4v failed: Hive table is corrupt. It is declared as being bucketed, but the files do not match the bucketing declaration. Found sub-directory in bucket directory for partition: pday=20181012/phour=18

**Comment by dain** [comment]
My guess is you have set this up as a Hive transactional table.  Presto currently does not support these (mostly due to lack of demand).  I believe this issue covert this https://github.com/prestodb/presto/issues/6666 .  It that is not what you have setup.  Will need the table properties (Hive formatted output) and a file listing for the partition.

**Comment by findepi** [comment]
this might be of interest: https://github.com/prestodb/presto/issues/1970#issuecomment-404057065

**Comment by findepi** [comment]
Closing based on @dain 's https://github.com/prestodb/presto/issues/11699#issuecomment-429453628
Please reopen if it wasn't an accurate guess.
