### ISSUE TITLE
Value cannot be cast to timestamp for the beginning of the Daylight saving time

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#11729]
Presto fails to cast the timestamp representing the beginning of the Daylight saving time:

```
presto> select cast(varchar '2017-03-12 02:00:00' as timestamp);
Query 20181017_170049_38639_mwuxk failed: Value cannot be cast to timestamp: 2017-03-12 02:00:00
```

**Comment by rschlussel** [comment]
what would the correct behavior be?  2am does not exist on the day we switch to DST.  The same way you can't have a timestamp `2017-03-12 24:00:00`.

**Comment by haozhun** [comment]
This is a known issue. It should work because "TIMESTAMP" should have LocalDateTime semantics. However, "TIMESTAMP" in Hive has Instant semantics. Presto screwed up and gave "TIMESTAMP" Instant semantics. This code will work if the new semantics is turned on. But the new semantics is not ready due to lack of connector support.

**Comment by findepi** [comment]
Closing in favor of #7122 and https://github.com/prestodb/presto/issues/10326
