### ISSUE TITLE
Determine join distribution type should be stats based (for join flippling)

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#11745]
After https://github.com/prestodb/presto/pull/11625
join won't flip with only basic (non-column) stats. However, for basic join flipping (in `DetermineJoinDistributionType`) we don't need columnar stats. Just plain row count is enough to flip join sides.

CC: @arhimondr

**Comment by findepi** [comment]
As i understand, this will work for joins of 2 tables, but won't be able to reorder 3 tables -- without column stats we won't be able to estimate output of 2 joins in order to compare it with the 3rd table.

More resilient approach to consider would be to have some simplified version of RerderJoins, which would compare source table sizes and eg put the biggest table on the left. (Just a sketch, not a full solution).
It doesn't mean we need to implement this "more resilient" approach.

**Comment by sopel39** [comment]
> More resilient approach to consider would be to have some simplified version of RerderJoins, which would compare source table sizes and eg put the biggest table on the left. (Just a sketch, not a full solution).

That would require some kind of pessimistic stats estimator, no?

**Comment by arhimondr** [comment]
@sopel39 

> As i understand, this will work for joins of 2 tables

Doesn't it work now for 2 joins without any filters? (you need column level stats to estimate filters)

**Comment by mbasmanova** [comment]
CC: @mbasmanova @rschlussel @picrinite
