### ISSUE TITLE
json_extract_scalar returns NULL for non-NULL array object

### ISSUE THREAD

**Issue by MichaelChirico** [prestodb/presto#11800]
https://stackoverflow.com/questions/53038338/json-object-is-null-but-somehow-its-children-are-not

I thought this might be an SQL problem, but it works as expected in Spark's SQL API (using `get_json_object` as a drop-in replacement of `json_extract_scalar`):

```sql
select json_extract_scalar('{"json_array":[{"array_field":"1"}]}', 
                           '$.json_array') is null,
       json_extract_scalar('{"json_array":[{"array_field":"1"}]}', 
                           '$.json_array[0]') is null,
       json_extract_scalar('{"json_array":[{"array_field":"1"}]}', 
                           '$.json_array[0].array_field') is null
-- true  true false
```

I can't imagine how the first two can return  `true` but the third `false`, so I assume it's a bug.

**Comment by findepi** [comment]
`json_extract` seems to be the function you actually want to use here.

**Comment by MichaelChirico** [comment]
So, this seems like another version of https://github.com/prestodb/presto/issues/2507

**Comment by dain** [comment]
For any future readers, `json_extract_scalar` returns a scalar value which are simple single value types like a number, boolean or string, where as JSON arrays and objects are not scalars.  The `json_extract` method returns a JSON encoded value of any type, which is normally not people want when extracting a JSON string, because a JSON string is quoted.
