### ISSUE TITLE
Special jdbc types (like postgres jsonb, interval, tsrange, ...) are skipped in jdbcTypeToPrestoType

### ISSUE THREAD

**Issue by guyco33** [prestodb/presto#11821]
Special column types are skipped while selecting a jdbc table.
For example: 
Postgres table  T(id integer, val integer, period tsrange)
is mapped in presto as table T(id integer, val integer)
while desired mapping should be:  T(id integer, val integer, period varchar)
so period data column can be accessible :)

**Comment by dain** [comment]
Just to clarify, you are proposing that any "unrecognized" type is automatically mapped to `VARCHAR`?  I think that may create a backwards compatible trap for us.  For example, above you use the Postgres `tsrange` type, but what if in the future we add a similar type to Presto.  At the point all existing queries would break. 

Instead of this generic approach, I would suggest that we implement proper mappings for `JSON` and `INTERVAL`, which Presto already supports.  For `tsrange`, I think we need a larger discussion, so maybe start a new issue for that one (or ask on Slack or the mailing list).

**Comment by guyco33** [comment]
@dain 
We can protect this behaviour with a session attribute that will be added later and will preserve a backward compatibility when new types will be implemented in the Jdbc mapping.
There is a huge value for the analysis pipelines to expose now all the columns in the Jdbc source tables.
