### ISSUE TITLE
Casting timestamps with timezones to varchar changes the time

### ISSUE THREAD

**Issue by DrXopher** [prestodb/presto#11855]
If I cast a timestamp with timezone to a string it shifts the time by an hour. If I cast a string to a timestamp with timezone it shifts the time in the opposite direction. 

It seems to be related to daylight savings. Sao Paulo changed their daylight saving on 4th November. Trying dates after that works fine. 

What's going on?

```
SELECT
    CAST('2018-10-28 14:44:59.000 America/Sao_Paulo' AS TIMESTAMP WITH TIME ZONE),
    CAST(CAST('2018-10-28 14:44:59.000 America/Sao_Paulo' AS TIMESTAMP WITH TIME ZONE) AS VARCHAR)
```

**Comment by haozhun** [comment]
This looks like #8233

**Comment by haozhun** [comment]
* We must not upgrade to joda 2.10.1, which has tzdata 2018g. There is no java release with that version of tzdata at this time.
* If we upgrade to joda 2.10, tzdata version will be 2018e. Java has 2018e since 10.0.2, 8u181, 7u191, 6u201.
* Since joda 2.9.9 (until 2.10), tzdata version has always been 2017b. Java has 2017b since 8u141, 7u151, 6u161 (but updated to 2017c since 9.0.4, 8u161, 7u171, 6u181). In other words, 8u151/152 is the only Java version that works without tz glitches with current Presto.

**Comment by haozhun** [comment]
According to tzdata, `America/Sao_Paulo` zone went through rule changes since 2017b.

```
# From Steffen Thorsen (2017-12-18):
# According to many media sources, next year's DST start in Brazil will move to
# the first Sunday of November, and it will stay like that for the years after.
# ... https://www.timeanddate.com/news/time/brazil-delays-dst-2018.html
# From Steffen Thorsen (2017-12-20):
# http://www.planalto.gov.br/ccivil_03/_ato2015-2018/2017/decreto/D9242.htm
#
# From Fábio Gomes (2018-10-04):
# The Brazilian president just announced a new change on this year DST.
# It was scheduled to start on November 4th and it was changed to November 18th.
# From Rodrigo Brüning Wessler (2018-10-15):
# The Brazilian government just announced that the change in DST was
# canceled....  Maybe the president Michel Temer also woke up one hour
# earlier today. :)
```

**Comment by electrum** [comment]
Is there an easy way to detect the tzdata versions for Joda and Java? If so, we could fail on startup if they do not match.

**Comment by haozhun** [comment]
Let's move discussion about solving the root cause to #8233
