### ISSUE TITLE
Add feature toggle for treating Hive partitions as Presto partitions.

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#11876]
Presto partitions enable grouped execution and reduced memory footprint. Currently grouping execution works only with Hive buckets (when `hive.bucket-execution` is on).
It would be useful to have a toggle for treating Hive partitions like "buckets" so that users can take advantage of grouped execution when they don't have physical Hive buckets created. This would be useful in low memory scenarios and also for singular large queries on cluster that otherwise executes low mem queries.

FYI: @haozhun

**Comment by dain** [comment]
This has come up a few times, but normally it is around writing Hive partitions.  Specifically, if you are writing a lot of partitions with a single query, you get one file per partition *per writer task*.  Since writers like ORC can use a significant amount of memory (128MB each), and small files hurt HDFS and read performance,  so there is a desire to support write distribution based on partitioning.  The issue with distributing on write is that in the vast majority of cases Hive queries write exactly one partition, and if you distribute on partition keys you would get only one writer.  We spent some time discussing an adaptive approach, but everything we came up with was really complex and totally Hive specific, so we had this on the todo list as a session property.

Anyway, for this proposal, I believe you are talking about read side.  We also talked about this idea a few times.  The core idea was to add partitioning to the bucket function, so it would appear as if each partition was a separate bucket (and if bucked the sub buckets).  I believe there are a bunch of complexities with actually implementing this, but I'll leave that to @haozhun to explain.  My hope was that on the read side the CBO would be able to make the determination based on the partition stats, but my fear is that this will be very complex to model. So, I would guess if this is possible to implement, we would need a session property also.

**Comment by findepi** [comment]
> Specifically, if you are writing a lot of partitions with a single query, 

This isn't what this issue is about. However good point also. Especially for ETLs. This is covered by https://github.com/prestodb/presto/issues/8901 Let's continue "writes" there.

> Anyway, for this proposal, I believe you are talking about read side. We also talked about this idea a few times. 

yes, this is about reads.
This was briefly discussed on Slack. AFAIR @haozhun said it should be doable but just not implemented, as a lower priority.
