### ISSUE TITLE
Pushdown join constraints as Filter to the larger relation

### ISSUE THREAD

**Issue by hustnn** [prestodb/presto#11885]
For one small table join a large table, if I want to eliminate the job by pushing down the small table as filter, Should I use  Dynamic filtering in Presto or some better way?

**Comment by dain** [comment]
This really depends on exactly what the problem is.  Dynamic filtering can help reduce the IO, decompression, and decoding of data segments contain no matching rows.  Depending on the data distribution and physical organization, that could have no effect or a huge effect.  Normally the biggest win is a broadcast join for the "small" table, because this prevents redistribution of the larger table, which is quite expensive. Also, if the table is really small you can get skew that reduces the concurrency (if you have one value you only process on one machine with parallel threads).  You can manually force broadcast session property `join_distribution_type=broadcast`.  If you have stats, `join_distribution_type=automatic` may work also... check the explain plan.

There are a couple of pending PRs (not sure of the state) dynamic filtering you can find by searching the outstanding PRs.

**Comment by dain** [comment]
In that specific case, I think you will want to implement index join for your HBase connector.

**Comment by hustnn** [comment]
Hi @dain ,

I saw the document of dynamic filtering here https://docs.google.com/document/d/1NYhEqYfmOPUqYFVzmOWvIXds5reFlaAi7z-zeJWqSLE/edit.

It is the same cased as I said. Let me also have a look at the index join, do you think the index join should be better for this kind of query?

**Comment by dain** [comment]
@hustnn it is a complex subject.  For me the key is you mentioned you have a very small table, and your backend system already has an index on they key.  This means that at worst case you could get a lookup on for the keys on each your machines.  My assumption is that this extra lookup cost (i.e., each machines instead of one machine) is less than the cost of a redistribution.  If on the other hand the lookup table were "large" then the cost of the extra lookups could easily exceed the cost of the redistribution.  We saw both sides of this at FB and it really depends on the exact workload.

**Comment by hustnn** [comment]
@dain Thanks for your explains.
I am sill confused by the use case of implementing a index join for a connector and dynamic filtering. According to my understanding, the huge win for both approaches should be a data source with index join with a small table, correct me if wrong. Then, in this case, index join and dynamic filtering are quite similar, is it right？
