### ISSUE TITLE
Queries not getting dequeued when the resource-group hits hardCpuLimit

### ISSUE THREAD

**Issue by phd3** [prestodb/presto#11881]
It has been seen that Presto (0.203) doesn’t dequeue a queued query of a user by itself, when that query was preceded by high-cpu utilization by the same user.  

Presto throttles further query ingestion by a resource-group (RG) in case of high cpu utilization by that RG. For simplicity, let’s assume that we are talking about a leaf RG that is one of the direct subgroups of a root RG. Now, when a query **q** is submitted by this (leaf) RG at the time when cpuUsageMillis > cpuHardLimit, it gets queued, which is expected. But we also know that  cpuUsageMillis keeps reducing with time based on cpuQuotaGenerationMillisPerSecond. It has been observed that **q** doesn’t get dequeued by itself even after cpuUsageMillis goes below the limit. 

The dequeuing of **q** would depend on the RG being added to eligibleSubGroups of the parent (root) RG. But this action of adding to eligibleSubGroups happens through updateEligibility(), which doesn’t get called when cpuUsageMillis goes below the limit. So, internalStartNext doesn’t actually trigger dequeuing of **q**. 

 **q** gets dequeued as expected if another query is submitted once the cpu quota has been “replenished”, since startInBackground and enqueueQuery end up calling updateEligibility. This is a workaround, but puts burden on the user.

@nezihyigitbasi @raghavsethi @findepi Have you guys come across or looked into this issue earlier? I looked at a few PRs, but the issues there seem to be different.

Thought about using updateEligibility in internalGenerateCpuQuota, but afraid that it would be expensive. Would appreciate any suggestions on the fix. Thanks.

**Comment by raghavsethi** [comment]
> afraid that it would be expensive

Why?

Another way would be to have a background thread that calls updateEligibility every so often

**Comment by raghavsethi** [comment]
I'm not sure how you would do that, but would be happy to look at a draft PR.

**Comment by ankitdixit** [comment]
@raghavsethi @phd1994  I am facing the same problem too. Is there any timeline for the solution. 
Would you like to suggest a temporary workaround until this is fixed.
In can run more we have this code 
`if (cpuUsageMillis >= hardCpuLimitMillis) {
                return false;
            }`
Does it make sense to have a new variable which keeps track of whether the cpuUsageMillies has "crossed hardCpuLimit" per group, this can be set when a query finishes and we find hardLimit is crossed and in the else part of above code we can add 
`else if (crossedHardLimit)`
{ 
updateEligibility(); 
crossedHardLimit=false;
}

**Comment by phd1994** [comment]
@ankitdixit thanks for your comment.

Personally, I don't think it is a good idea to update state inside `canRunMore` method, since it's purpose is to check the state and return a boolean. 

On the lines of what you suggested, we can implement this in `internalGenerateCpuQuota` method. We can check for the value of cpuUsageMillis, and see if it has become less than the threshold of `hardCpuLimitMillis`. If that is indeed the case, then we call `updateEligibility`. This should resolve the problem, but that can result in inefficient execution, given that `internalGenerateCpuQuota` is a recursive method, and hence ancestors will be updated repeatedly.

As mentioned earlier, this is a workaround:
> **q** gets dequeued as expected if another query is submitted by the user once the cpu quota has been “replenished”, since startInBackground and enqueueQuery end up calling updateEligibility. This is a workaround, but puts burden on the user.

I have some ideas on updating eligibility using a different method, which traverses the tree once every time when `RootInternalResourceGroup::generateCpuQuota` gets called. I plan to implement and draft a PR for that soon. If that approach doesn't work out, we can explore the other one.

**Comment by phd3** [comment]
fixed in https://github.com/prestosql/presto/pull/1128
