### ISSUE TITLE
presto with large resultset performance problem

### ISSUE THREAD

**Issue by rockxsj** [prestodb/presto#11908]
We use presto as our MPP calc framework, in most time it works well.
But when the query resultset is large enough, for example we have some queries will return more than 1GB result. 
When I use presto-cli or jdbc to query these queries and dump to disk, it will take about 3 minutes or more.

When I watch the query at presto monitor UI, I can see one worker buffed too many data, the screenshot below will show this:
![image](https://user-images.githubusercontent.com/3021207/48389251-998a5f00-e737-11e8-8a08-494931defeb6.png)

Does have any workaround with the large resultset queries?

Thanks for any reply!

**Comment by rockxsj** [comment]
Hi, when I follow the query, I think I have found the reason...

Because the client get result by a series of queries, each query will get part of the result. In the version before v0.213, each query will only get 1MB data, so 1GB data will need about 1000 times queries http request. In v0.213, the client can modify the fetch size by the new param named "targetResultSize".

:)

**Comment by haozhun** [comment]
In general setups, the connection between Presto client and Presto coordinator is low latency. In such case, making each chunk larger simply won’t help because the additional roundtrip was never the bottleneck. If this is not the case in your setup, increasing it may help. But don’t expect anything dramatic.

Note that Presto client protocol is not designed to stream large amount of data. As you noticed, all data to the client is streamed through the coordinator. When you have way more workers than coordinators, this inevitably creates a bottleneck on the coordinator. If you are using Presto to run pipelines, the result should be written into a table. If, for some reason, you want the client to do postprocessing on the data, the suggested approach for non-trivial amount of data is to instruct Presto to write into a table encoded in TEXTFILE (assuming you’re using Hive backend), and read the CSV output directly off your storage. If you’re using a different backend, you can probably just instruct Presto to write into any table, and then read off that backend using whatever API that backend provides.

**Comment by rockxsj** [comment]
@haozhun Thanks for your reply.

 In my use case, I query the detail data in hive through presto by JDBC driver and export the query result to a local file, and then another thread import the result file to a GreenPlum cluster.  

In the past our detail data was stored in another GreenPlum cluster, and the above pipeline worked well because the COPY command of GeenPlum have a very high performace.

So, in your advise I should use the Postgres connector provider by presto connect to my GreenPlum cluster, and then modify my business pipeline to use some statements like "INSERT INTO gp.result_table SELECT FROM hive.fact_table"?     In fact, I have consider this, but I don't know should I store my result data into hive instead of GreenPlum?

**Comment by tooptoop4** [comment]
@rockxsj how do you pass the targetResultSize argument when using Presto JDBC or CLI ?

**Comment by rockxsj** [comment]
@tooptoop4 I have no idea, now it's not a problem, because we insert the big-result into a temp table as csv format, and then download these csv.
