### ISSUE TITLE
Add ASSUME UNIQUE SQL support for joins

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#11962]
This is a proposal received from a user. I'm posting it here to get feedbacks if this is doable and doesn't violate any SQL language rules.

Motivation

In many queries that perform JOIN operations the assumption of the author of the query is that for every row on the left side of the JOIN no more than one line on the right side of the JOIN matches it. However, occasionally this is not the case because of bad data. This results in duplicate rows that may propagate to downstream tables and results either in failures in downstream pipelines or in bad data in tables. Such a failure or bad data often leads to a big effort in debugging since the root cause of the problem is not where it's detected but rather much early in an upstream table.

The proposed solution

Add ASSUME UNIQUE keywords to the SQL language. This will be used just after the JOIN keyword. It will not have any semantic effect. However, when the query engine executes the query it will test whether for every row at the left side of the JOIN at most one row on the right side of the JOIN matches it. If the test fails then the query will fail with an appropriate message.

Example

SELECT
    *
FROM lineitem 
JOIN ASSUME UNIQUE  orders
ON lineitem.orderkey=orders.orderkey

**Comment by martint** [comment]
> Add ASSUME UNIQUE keywords to the SQL language.

This is not standard SQL syntax. We are very careful about adding new features to the language due to concerns about compatibility with future revisions of the specification, and generally don't do it unless there's an very compelling reason and no alternative within the existing capabilities. We also look for precedent and consensus in other SQL implementations as a sign that the syntax might eventually become part of the standard.

> It will not have any semantic effect.

It certainly has. It will cause a join that would otherwise succeed to fail.

In this case, the same result can be achieved using standard SQL syntax in a manner that better captures the intent of the user by way of a correlated scalar subquery, so I don't think it's reasonable to add the proposed syntax to the language. Note that this is not currently supported by Presto.

```sql
SELECT lineitem.*, (SELECT * FROM orders WHERE lineitem.orderkey = orders.orderkey).*
FROM lineitem
```
