### ISSUE TITLE
Max number of columns ORC reader can support with partition

### ISSUE THREAD

**Issue by ch7025833** [prestodb/presto#11965]
Hi, I have a table stored in Hive with ORC format, and it probably has 1000 columns stored in orc file, it only has 25,000 records inside. I try to create a new table(CATs) with selecting all fields from this table, and partition it into a partitioned table(probably 80 partitions),  then 1 worker node soon gets OOM, and stop responding. The worker has 20GB free memory, and soon gets exhausted.

I try to reduce column number to 600 and it works. Is there any limits of supported columns for orc file?

**Comment by dain** [comment]
There are no limits that we know of, but each column takes memory from the system.  This memory is accounted for and will fail the query if the limits exceed the max memory allocated to the query.  @wenleix at Facebook has done a lot of work to ensure the memory accounting it accurate, so I would guess that the workers are configured to use more memory than is actually available in the JVM.

I would guess the real issue is that the `80 partitions *  1 file / partition * 128 MB buffer / file ~= 10GB` . I'd try reducing thee stipe size to 64MB to reduce the overhead.  Of course since your table is so wide, you will not get very good compression.  If that is a concern, I'd provision machines with a decent amount of memory (20 GB is "laptop" sized).

**Comment by ch7025833** [comment]
thanks for your reply ! I am going to try your advise and maybe also try to reduce some columns

**Comment by findepi** [comment]
> ... work to ensure the memory accounting it accurate, so I would guess that the workers are configured to use more memory than is actually available in the JVM.

@dain @wenleix would that be possible to misconfigure like that?
