### ISSUE TITLE
How to limit the number and size of files  generated when using hive's insert

### ISSUE THREAD

**Issue by hiliuxg** [prestodb/presto#11975]
When I  use the hive's insert into function, I found that many small files were generated on hdfs, perhaps the number of files is related to the number of concurrent tasks. How do I control and limit the number and size of files? After all, many small files will affect the performance of hadoop.

**Comment by findepi** [comment]
My guess is that you're doing some kind of ETL into a partitioned table. 
In that case, there will be multiple files created (per partition and per writer task). You can control number of writers:
- check you didn't increase `task.writer-count` config toggle
- reduce concurrency (fewer tasks): `task.concurrency` config toggle
- user writer scaling, so that you use fewer writers where possible: `scale-writers` config toggle

There are cases where all this isn't sufficient. For example, writer scaling will limit number of writers only when source of your data is slower than writes.
There is also https://github.com/prestodb/presto/issues/8901 which would help.

BTW
user group (https://groups.google.com/d/forum/presto-users) is the best place for this kind of questions.

**Comment by hiliuxg** [comment]
> My guess is that you're doing some kind of ETL into a partitioned table.
> In that case, there will be multiple files created (per partition and per writer task). You can control number of writers:
> 
> * check you didn't increase `task.writer-count` config toggle
> * reduce concurrency (fewer tasks): `task.concurrency` config toggle
> * user writer scaling, so that you use fewer writers where possible: `scale-writers` config toggle
> 
> There are cases where all this isn't sufficient. For example, writer scaling will limit number of writers only when source of your data is slower than writes.
> There is also #8901 which would help.
> 
> BTW
> user group (https://groups.google.com/d/forum/presto-users) is the best place for this kind of questions.

super thanks
