### ISSUE TITLE
Expected service announcement after 8000.00ms, but announcement was delayed 16.11s

### ISSUE THREAD

**Issue by x-otto-x** [prestodb/presto#12132]

**Comment by nezihyigitbasi** [comment]
This message is logged by the discovery `Announcer` [here](https://github.com/airlift/airlift/blob/master/discovery/src/main/java/io/airlift/discovery/client/Announcer.java#L142-L145), when the discovery announcement is delayed more than 5s. I have seen this message multiple times due to long GC pauses. You can check your GC logs to see whether there are long pauses around the time of this message.
