### ISSUE TITLE
Different date result between presto and hive

### ISSUE THREAD

**Issue by ebyhr** [prestodb/presto#12180]
As Shubham posted on Google Group, selecting `0600-01-01` from hive connector returns `0600-01-03`.
https://groups.google.com/forum/#!topic/presto-users/lb-5xLV7buc

Steps to reproduce
1. Create table on hive
```sql
hive> create table presto_12180 stored as orc as select cast('0600-01-01' as date) as c1;
hive> select * from presto_12180; 
0600-01-01
```

2. Select via Presto
```sql
presto> select * from hive.default.presto_12180; 
 0600-01-03 
```

Also date_add results are different. (Probably, presto result is right?)
```sql
hive> select date_add('1970-01-01', -500380);
0600-01-01

presto> select date_add('DAY', -500380, cast('1970-01-01' as date));
0600-01-03 
```

**Comment by Praveen2112** [comment]
But the Presto's result is the correct one right ? I guess Shubham is using Hive 1.1.0 and it might be a issue in Hive 1.1.0 ?

**Comment by Praveen2112** [comment]
@ebyhr It is because of the issue in Hive for version before 3.1. Prior to 3.1 version hive uses `DateWritable` for converting the `Date` to epoch day and the conversion is bit buggy (might be because of Julian and Gregorian calendar changes) and after Hive 3 they have moved it to `DateWritableV2` which  `LocalDate#toEpochDay` to get epoch day.

When we try to run this query `select datediff(cast('1582-10-15' as date), cast('1582-10-05' as date))` these are the following results

1. Before Hive 3.1
  0
2. On Hive 3.1
  10

One solution is to move the Hive to 3.1 and for ORC files (Parquet or RC files might also be affected) which are created from older versions of Hive we can have a separate Date type which will might convert the epoch day created by `HiveWritable` to epoch day created by `LocalDate`. I would like to raise a PR for the same. Or is there is any other alternate solution which would be a efficient one.

**Comment by findepi** [comment]
The problem of Julian-Gregorian differences is totally ignored by Java Time. Java Time uses proleptic Gregorian calendar.
(true support for combined Julian-Gregorian should be region-aware, as different countries did transition in different years, some as early as  sixteen century, some as late as twenty century)

Before Hive 3.1, Hive would always (?) use java.util.Date, java.sql.Timestamp which share calendaring logic with java.util.Calendar.
Presto would use these classes only when using Hive SerDe directly, so not in case of ORC, Parquet, RCFiles which all have dedicated reader implementations.

Now, the problem of historic dates is in reality impossible to solve. For example, in Julian calendar there was a date like 1500-02-29, but there was is no such date in proleptic Gregorian calendar, so such value cannot be represented in Presto.

When dealing with historic dates, I would use `varchar` always.

**Comment by ebyhr** [comment]
@findepi @Praveen2112 Thank you for the detailed explanation. Let me close this issue.
