### ISSUE TITLE
“minimum is not less than maximum“ when  Failed to read ORC file

### ISSUE THREAD

**Issue by daikon12** [prestodb/presto#12200]
Question:
 
When my query involves a column A ( As a where condition ) of a table which is ORC , the result will be "EXTERNAL ERROR" .  But if I don't use column  A in where , the result will be  normal .This problem has been bothering me for a long time. It would be great if you could provide me with some reasons and solutions

With column A: 
select * from browser.f_evt_browser_article_info where dt='20190107'  and docid='15565570' limit 6  
![image](https://user-images.githubusercontent.com/8246136/50887400-02d3d900-142e-11e9-8769-6fb18e5f4c4a.png)

Without column A: 
select * from browser.f_evt_browser_article_info where dt='20190107'   limit 6
![image](https://user-images.githubusercontent.com/8246136/50887516-53e3cd00-142e-11e9-8fa3-ef34925bf6a1.png)

The schema of table :
![image](https://user-images.githubusercontent.com/8246136/50887544-69f18d80-142e-11e9-9238-95c00ecf7219.png)

Look forward to your thoughts .Thanks!

**Comment by dain** [comment]
This means you have a corrupt ORC file.  The Presto engine does its best to validate the ORC statistics to avoid returning incorrect results on corrupt data.  This is because Presto makes extensive use of the statistics in the file to skip sections of the file that will be filtered out.  The engine has a pretty hard rule about bad data and does not allow processing of files that are "partially" corrupt, and instead assumes that only corruption means there may be other sections that are corrupted in undetectable ways. 

Regardless, this exact error was likely caused by a bad writer that is incorrectly sorting VARCHAR values containing high unicode values.  I would suggest that you rewrite the data using a newer version of Hive or Spark.

**Comment by daikon12** [comment]
@dain 
Thank you very much for your explanation and Suggestions which inspire me  a lot 。
