### ISSUE TITLE
Inconsistency in date support

### ISSUE THREAD

**Issue by fs-td-eitaro-ueda** [prestodb/presto#12273]
I have noticed that there is inconsistency in returned specific dates when I imported a CSV file to create a table in hive and read it from presto. I have tried with the latest versions for both.

I have so far found that within theses ranges of dates in Hive:
Between 1000/01/01 - 1000/02/28, dates obtained by presto is dates obtained by hive +5.
Between 1000/03/01 - 1100/02/28, dates obtained by presto is dates obtained by hive +6.
Between 1100/03/01 - 1300/02/28, dates obtained by presto is dates obtained by hive +7.
Between 1300/03/01 - 1400/02/28, dates obtained by presto is dates obtained by hive +8.
Between 1400/03/01 - 1500/02/28, dates obtained by presto is dates obtained by hive +9.
Between 1500/03/01 - 1582/10/04, dates obtained by presto is dates obtained by hive +10.

For example, 1000/01/01 in hive turns out to be 1000/01/06 in presto (+5 days), as shown below:

Hive: 
```
hive> create table date_test (d date);
OK

hive> insert into date_test select '1000-01-01' from camma limit 1;
OK

hive> select * from date_test;
OK
1000-01-01
```

Presto: 
```
presto:default> select * from date_test;
     d      
------------
 1000-01-06 
(1 row)

presto:default> select cast(d as date) from date_test;
   _col0    
------------
 1000-01-06 
(1 row)

presto:default> select cast(d as varchar) from date_test;
   _col0    
------------
 1000-01-06 
(1 row)
```

Has anyone encountered this issue? Please let me know if there is a way around.

(Possible related issue: https://github.com/prestodb/presto/issues/8120)

**Comment by Praveen2112** [comment]
@fs-td-eitaro-ueda It is because of the issue in Hive for version before 3.1 (For dates which were before `1582-10-15`) . Prior to 3.1 version hive uses DateWritable for converting the Date to epoch day and the conversion is bit buggy (might be because of Julian and Gregorian calendar changes) and after Hive 3 they have moved it to DateWritableV2 which LocalDate#toEpochDay to get epoch day (which is on par with Presto's Date to epoh day conversion).

It is already discussed in #12180.

As @findepi said 

> When dealing with historic dates, I would use varchar always.

**Comment by electrum** [comment]
I am working on updating to Hive 3.1 in https://github.com/prestosql/presto which should resolve the issue
