### ISSUE TITLE
Function to canonicalize phone number

### ISSUE THREAD

**Issue by rongrong** [prestodb/presto#12283]
This request comes from Facebook internal users. It seems to be generically useful so proposing to add this in the open source repo. It could have the following versions:
```
CANONICALIZE_PHONE_NUMBER(phone)
CANONICALIZE_PHONE_NUMBER(phone, country)
CANONICALIZE_PHONE_NUMBER(phone, country, format)
```
Would love to get some feedback on whether this is useful and the API.

**Comment by rongrong** [comment]
@nezihyigitbasi @raghavsethi @wenleix @highker What do you guys think about introducing this to open source?

**Comment by raghavsethi** [comment]
I don't understand how this function works - could you provide a spec or examples? I'm also a little worried about naming, especially if there are multiple well-known ways to canonicalize. If we are using technique `abc`, I would suggest maybe we call it `abc_canonicalize_phone_number`?

**Comment by mayankgarg1990** [comment]
this is based on Google's library - `libphonenumber`. The inputs to the function are country and format. `country` is the standard ISO code for the country and the format will be one of the standards - copying the enum from the library:

```
public enum PhoneNumberFormat {
    E164,
    INTERNATIONAL,
    NATIONAL,
    RFC3966
  }
```

An example use case will be:

`SELECT canonicalize_phone_number('412 9 150.000 x 500', 'US', 'RFC3966');`

Result: `tel:+1-412-915-0000;ext=500`

Since we are canonicalizing to international formats, I don't think we need to prepend a specific way of doing this.

**Comment by nezihyigitbasi** [comment]
This looks like a generic function that may be useful for some users out there, so I am fine with introducing this function. At the same time, I don't remember any user asking for this functionality in the open source so far.

**Comment by mayankgarg1990** [comment]
We are not planning to solve this for now since this needs more think through. Closing this for now.
