### ISSUE TITLE
Resource aware query planning

### ISSUE THREAD

**Issue by mnoumanshahzad** [prestodb/presto#12344]
Hi,

We are running multiple Presto clusters on AWS EMR. Presto serves as the backend SQL query engine for our analytics reporting server. Currently we use "r4" instance types (memory intensive) for our clusters, but I want to try a mix of compute and memory intensive instance types, as some of our queries can be CPU bound.

When planning a SQL query, does Presto somehow take into account the resources (CPU + Memory) available on individual nodes of a Presto cluster? What could be hidden downsides that I am not able to forsee by using a heterogeneous collection of nodes for a Presto cluster?

Secondly, I know so far Presto plans a query on the available nodes in the cluster and in case of a scale out, the existing running queries don't make use of the newly added nodes. Are there plans in the near future to support dynamic load distribution in case of a scale out event? 

What best practice (or metrics) would you suggest to perform effective auto-scaling? Currently, we scale out on the CPU + Memory usage thresholds along with Query Execution Time Increase (calculated by metrics available from Presto).

Thanks in advance for any inputs

**Comment by raghavsethi** [comment]
Presto is not currently designed to be able to use up resources efficiently on a heterogenous cluster.

To your second question:

In some cases, task assignment can happen after the query is initially scheduled (scaled writes) or if using phased execution. Presto cannot always scale queries during execution since we only consider new nodes when assigning tasks. There are some tricks that people use to effectively achieve this scaling (setting the minimum required workers) such that only the coordinator needs to remain up to receive queries. I would recommend posting in the Slack channel to ask community members for input.

**Comment by mnoumanshahzad** [comment]
Thank you for the guidance @raghavsethi
