### ISSUE TITLE
Slow planning (iterative_optimizer_enabled) V-0.214

### ISSUE THREAD

**Issue by rigogsilva** [prestodb/presto#12402]
Hi, 

I am digging around to find the reason why our planning takes about 40 seconds. We do have a lot of partitions, and the setting `iterative_optimizer_enabled` is on; I've read in some posts to turn this setting off, but I am not sure if that is the cause. 

What does the `iterative_optimizer_enabled` setting do? Can I turn it off? Will it improve planning performance?

Thanks in advance!

**Comment by rschlussel** [comment]
I doubt that `iterative_optimizer_enabled` is the cause.  You can test out turning it off and see if it helps. If it does, that means one of the optimizer rules is the cause because it just turns off some "newer" rule implementations, however none of the rules it turns off are very new anymore.

Having many partitions could make planning slow.  Could you try running with `hive.statistics_enabled = false`?  This turns off asking for statistics information from hive for all of the partitions.  If you have a lot of partitions, and especially if you have high latency in requests to the metastore, that could increase your planning time.
