### ISSUE TITLE
We need a TRY_ALL() operator that can catch all exceptions

### ISSUE THREAD

**Issue by danb-lotsofnumbers** [prestodb/presto#12404]
In Presto, we have the TRY() operator, which can wrap some operations and convert certain Exceptions to null -- notably they convert INVALID_FUNCTION_ARGUMENT to null.

The TRY() operator does not convert all Exceptions to null.
In particular, if a UDF hits a bug, the UDF is likely to throw an Exception that will not be handled by TRY().

I am working with some newly written geometric functions which sometimes have hard-to-find bugs.
I'm worried about a situation where one of the rows in my table triggers a hard-to-find bug.
If this happens, it would take months to get a fix released, and the UDF would be unusable until then.

We need a TRY_ALL() operator that would work like TRY() but would convert all Exceptions into nulls.

**Comment by danb-lotsofnumbers** [comment]
(see also: https://github.com/prestodb/presto/issues/12289)

**Comment by mbasmanova** [comment]
CC: @raghavsethi @arhimondr @rongrong @nezihyigitbasi

**Comment by arhimondr** [comment]
I'm afraid of many kind of abuses of this method, that may potentially lead to all kind of data corruption that are incredibly hard to detect. 

I understand that it makes some sense particularly for the GEO functions set, as there are so many way the input data can be corrupted. But instead of introducing a TRY_ALL() construction, i would rather wrap all the GEO functions that are likely to fail into a try-catch, and re-throw a `
INVALID_FUNCTION_ARGUMENT` exception containing the original cause.

**Comment by raghavsethi** [comment]
I agree with Andrii - the most straightforward fix would be to have functions throw the correct errors (that can be caught by TRY).

**Comment by mbasmanova** [comment]
@arhimondr @raghavsethi Andrii, Raghav, thanks for your input. It should be straightforward to update the geospatial functions to catch all errors and re-throw IllegalArgumentException. I'll work on a PR.
