### ISSUE TITLE
Does Presto support Parquet file format

### ISSUE THREAD

**Issue by JobsChang** [prestodb/presto#1277]
Hi all,   In my environment(Presto-0.66 + CDH5), when I use  presto-cli query data through hive, which used parquet file format, throw exception: 
 MetaException(message:org.apache.hadoop.hive.serde2.SerDeException SerDe parquet.hive.serde.ParquetHiveSerDe does not exist)

And I also find a problem, I can query data through hive, but can not query in presto, which the output is : 
Query 20140506_091032_00014_tmfct failed: Only '\N' supported as null specifier, was ''
Can anyone tell me what happened?

Many thanks!

**Comment by gowtham-sai** [comment]
is there way to avoid invalid parquet files ?

In my case, one task will continuously writes to parquet files in partitioned folder in a bucket. Presto is reading those files at the same time. Most of the queries are failing because of this? 

I'm using s3. I'm writing to temporary storage first and then moving the file to actual storage. Still it is failing. More detailed information [here](https://github.com/dask/s3fs/issues/104).

**Comment by lvijay** [comment]
@gowtham-sai this question is better suited to the presto-users mailing list.  https://groups.google.com/forum/#!forum/presto-users
