### ISSUE TITLE
MAX BIG INT returns TRUE when equality is compared to a bigger value

### ISSUE THREAD

**Issue by dserrano1524** [prestodb/presto#12784]
I noticed that when you multiply the BIGINT 4611686018427387904 by 2 powered 1, the result is 9223372036854776000, which is bigger than 9223372036854775807 (MAX BIGINT value), however, the equality boolean test takes them as equals.

I found this while trying to implement a bitwise left shift through the available Presto functions.

```sql
SELECT
    9223372036854775807 AS max_bigint,
    CAST('4611686018427387904' AS BIGINT) * pow(2, 1) AS before_max_bigint,
    CAST('4611686018427387904' AS BIGINT) * pow(2, 1) = 9223372036854775807 equal_boolean_test,
    CAST('4611686018427387904' AS BIGINT) * pow(2, 1) > 9223372036854775807 greater_boolean_test,
    CAST('9223372036854775807' AS BIGINT) * pow(2, 1) > 9223372036854775807 true_greater_boolean_test
```

Furthermore, any decimal number that can be created with the first 9 bits of the following binary string, result in the same wrong behaviour:

`100000000000000000000000000000000000000000000000000000111111111`

Once the tenth and any other of the first bits is used, the expected GREATER THAN behaviour is returned:

`100000000000000000000000000000000000000000000000000001000000001`

So there seems to be an issue with a few numbers that are close to the 9223372036854775807 value when multiplied by pow(2,1).

**Comment by tdcmeehan** [comment]
It's because `pow(2,1)` returns double ([see the documentation for `pow`](https://prestodb.github.io/docs/current/functions/math.html#pow)).  As `DOUBLE` is represented with the IEEE 754 standard, it has a higher range of values than `BIGINT`.

The expression:

`CAST('4611686018427387904' AS BIGINT) * pow(2, 1) = 9223372036854775807`

Returns true because `pow(2,1)` returns a `DOUBLE`.  So that causes the left side to be cast as a `DOUBLE` (to make the multiplication work).  Then, to make the comparison make sense, the right side must be cast to `DOUBLE` as well.  Because this is at the higher end of the range of floating point values, `9223372036854775807` is represented as `9.223372036854776E18`, which is the same value as the left side.

You'll get this sort of behavior for lots of numbers at the top of the range for BIGINT.

If you cast that `pow(2,1)` to some whole number type then you'll get the expected overflow error.

**Comment by dserrano1524** [comment]
Thanks for the explanation, this wasn't obvious to me. I'll take it into account.
