### ISSUE TITLE
[Need Information] Major version vs minor version

### ISSUE THREAD

**Issue by ajantha-bhat** [prestodb/presto#12805]
Hi, I have 2 questions related to project process as I am new here.

a) how do we differentiate the major and minor version in presto ?
Example Hive has 1.X.X, 3.X.X, so first digit indicates major version.  What naming convention is followed here ?

b) When we raise PR, where do compilation and UT runs for changes. for merged PR, I don't see any task for compilation and UT. so, how quality is ensured ?

Please let me know, these might be dumb questions. But I am new. So, want to understand.

**Comment by mayankgarg1990** [comment]
Re: versions

For the presto versions, we have been mainly focused on doing regular releases (currently every 4 weeks or so) with just a minor version change. So we have releases like 0.218, 0.219 and the one currently in preparation being 0.220.

Recently we have moved presto to also have hotfix versions - if with one of our releases we find that we have a major issue, for those we will end up releasing hotfix versions like - 0.219.1. 

We will make a call of when we move Presto to the next major version. That said, all of our releases are actively introducing new features and improvements to the engine so that is not to say that we are not moving the engine forward :) 

Re: testing

Every PR opened triggers Travis CI runs that is visible on the PR page. Feel free to take a look at any active PR and you can see the CI results.

In addition to that when we perform a release, within Facebook we run validation on more than 50k queries to ensure correctness and reliability of the build. We are actively working on providing more tools to further improve our coverage.

Let me know if you have more questions.
