### ISSUE TITLE
PlanOptimizer Expression-to-RowExpression Migration

### ISSUE THREAD

**Issue by highker** [prestodb/presto#12828]
This is the phase 2 of IR refactoring. The goal is to detach AST dependency from all plan optimizers. This does not block connector participating query optimization. The ultimate goal is to remove `OriginalExpression`.

Blocked by #12546

cc: @hellium01 @rongrong @mbasmanova @wenleix @arhimondr @rschlussel

**Comment by hellium01** [comment]
The plan is currently to split the clean up to multiple stages:

In the first stage, we will push the `TranslateExpression` to `AddExchange` so that we can push down logical plan to connectors and deprecate old `getLayout` API.
* Move `TranslateExpression` to above last projection pushdown  (PR #13047 )
* Move `TranslateExpression` to below last predicate push down (PR #13184)
* Move `TranslateExpression` to below addExchange (PR #13112)

At the second stage,  we will change `AddExchange` to utilize `RowExpression` and deprecate old metadata API `getLayout`.

At the third stage, we will clean up the optimizers up to the beginning and build `RowExpression` directly in `QueryPlanner`.

**Comment by highker** [comment]
- Move `TranslateExpression` to above addExchange (PR #13521)
