### ISSUE TITLE
Aria: enable tuple domain extraction for subfields

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#12917]
When pushdown filter is enabled, Hive connector needs to be able to extract range filters (tuple domains) that apply to subfields, e.g. `SELECT a FROM t WHERE b[1] = 10`.

See `com.facebook.presto.hive.SubfieldExtractor` and `com.facebook.presto.hive.TestHiveLogicalPlanner`.

CC: @aweisberg @yingsu00 @tdcmeehan @oerling

**Comment by aweisberg** [comment]
This [change](https://github.com/prestodb/presto/commit/1cb3c109a5c11edccc1ddcf1e02741244786b1c2#diff-78a525548cc5bc5bfc6bd9573d88389eR124) to how literals are represented seems to trip up [SubfieldExtractor](https://github.com/prestodb/presto/blob/a359e14c163da202db27498bc887405c08c2d930/presto-hive/src/main/java/com/facebook/presto/hive/SubfieldExtractor.java#L84) which expects ConstantExpression and not the CallExpression generated to cast the GenericLiteral.

I could try and walk back this change (not sure why it was originally done) or smarten up SubfieldExtractor to the extent it can evaluate a few of the problem cases we want to address.

**Comment by aweisberg** [comment]
I got this wrong. LongLiteral is still not the ConstantExpression that SubfieldExtractor is looking for so there is more to it.

**Comment by aweisberg** [comment]
The fix ended up being [enabling optimization when invoking SqlRowToExpressionTranslator from PickTableLayout.] This resolves any casts, function calls etc. that can be evaluated at planning time so that SubfieldExtractor can match on the result.

After that there was a bug fix for varchar subscripts and tests that cover the same things as TestSubfieldExtractor, but with actual input from the planner.
