### ISSUE TITLE
What is the difference between Physical Input Data and Input Data in Presto-dashboard?

### ISSUE THREAD

**Issue by groobyming** [prestodb/presto#12990]
Hello everyone!
I just used Presto. I don't understand the difference between the following parameters on the Presto panel. Please help me, thank you!
![image](https://user-images.githubusercontent.com/34335395/59909414-3afe2f80-9442-11e9-83a3-1482e595ea28.png)

**Comment by shixuan-fan** [comment]
My understanding is that input data is the size after decompression, while physical input data is the size before decompression.

**Comment by groobyming** [comment]
@shixuan-fan Thanks.    I found the raw data is parquet with snappy compression mode, and I This is the reason for the difference .

**Comment by atifiu** [comment]
I still want to understand the difference between physical input data and Input data. In my case input data is lower than physical inupt data. Based on above explanation of compression and decompression it should not be the case. I am using iceberg 1.1.0 , trino 405 and orc file format.![image](https://github.com/prestodb/presto/assets/48252551/1f67d1cf-5169-49d9-8165-2cfbcc39f88c)

**Comment by LiuJiazhen1999** [comment]
I want to understand the difference between physical input data and Input data too. In my case input data is lower than physical inupt data.

**Comment by atifiu** [comment]
So physical data is the actual data read from the files which might be compressed if in parquet or orc format and footers i.e. metadata. While input data is the uncompressed data to be processed by Trino/presto but only required columns. In ideal case due to compression physical data will be less as compared to input data but in some cases it might be more if metadata size is substantial( which is a problem) and there is lot of projection filtering on trino side i.e only few/some columns are actually read.

**Comment by LiuJiazhen1999** [comment]
Thank you very much，your answer makes it clearer to me. I would like to add to my observations，not only the compression, but also the reduction of physical input due to data encoding. In addition, I feel that trino's ui displays incorrectly in some cases, such as my where clause filtering all of parquet's row groups, at least the metadata is read (footer), but its physical input data size is displayed as 0.

**Comment by atifiu** [comment]
Yes I have seen few open issues regarding  incorrect reporting in ui.
