### ISSUE TITLE
Why to_unixtime's return type is Double?

### ISSUE THREAD

**Issue by shigemk2** [prestodb/presto#13178]
In Hive, unix_timestamp()'s return type is bigint.
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF

When we use unix timestamp as data, we always use it as Integer(or BigInt).
I want to know the reason why to_unixtime's return type is Double.

**Comment by ebyhr** [comment]
@shigemk2 As I replied you on twitter, the reason is the function allows to receive milliseconds. Hive's result doesn't have milliseconds.

It's not advertisement, but [prestosql community's slack](https://join.slack.com/t/prestosql/shared_invite/enQtNTMyNzU2NzQ1NzQ4LWRhMTE4ZTA4NjM0NDA1NmFkZjEyZDJmN2MxNGY1ZTk4NmM4MzMxZDk4OGQ0NjZhNmQxMWUyNGIxMDliODk0MmU) has Japanese speaker's channel (`#general-jp`) and `#troubleshooting` channel. You can ask these questions and get the answer quickly.
