### ISSUE TITLE
quickest way to validate a view?

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#13218]
1. create external table (pointing at parquet/s3) inside hiveserver2 with 2 columns, both string data type.
2. create view inside presto with 
CREATE VIEW hive.x.vw_y AS
SELECT
col1
,date_parse(NULLIF(col2, 'unknown'), '%d-%m-%Y') col2
from
hive.x.y
3. place a parquet file in the relevant location for this table with 100 million rows, 99,999,999 rows have a valid timestamp conforming to the data_parse pattern but 1 row does not!

4. What is the fastest (in terms of wall time, lowest resource usage) way to validate if all rows in the view are valid or alternatively quickly get an error?

Doing 'select * from hive.x.vw_y' throws the error consistently but takes a while to run given the large volume. Doing 'select * from hive.x.vw_y limit 1000' often returns success (only very rarely returns error if it finds the 1 bad row in that limit)
EXPLAIN (TYPE VALIDATE) select * from hive.x.vw_y always give success
Doing select count(1) from ( select * from hive.x.vw_y except select * from hive.x.vw_y ) also throws the error consistently but i don't think its the best way....

**Comment by rschlussel** [comment]
If you're trying to validate all the rows, you'll need to read all the values.  part of the reason the select * may be slow is that all the results need to stream through the coordinator. That's why doing a count is likely better than just select * , and performance-wise I'm not sure you'll find anything better.
