### ISSUE TITLE
Release notes for 0.225

### ISSUE THREAD

**Issue by shixuan-fan** [prestodb/presto#13212]
Issue to track release notes for next release

**Comment by caithagoras** [comment]
# Missing Release Notes
## Ajay George
- [ ] all checked
- https://github.com/prestodb/presto/pull/13224 Fix reporting of output data size for PartitionedOutputOperator
## Ami Tavory
- [ ] all checked
- https://github.com/prestodb/presto/pull/13187 Improvements to classification metric docs
- https://github.com/prestodb/presto/pull/13192 Using reStructuredText citations
- https://github.com/prestodb/presto/pull/13107 Math mode in restructured text docs
- https://github.com/prestodb/presto/pull/12966 Fixed-Range Histograms
## Andrii Rosa
- [ ] all checked
- https://github.com/prestodb/presto/pull/12738 Limit query submition threads
## Bhavani Hari
- [ ] all checked
- https://github.com/prestodb/presto/pull/13193  Add ByteSelectiveStreamReader
## Dain Sundstrom
- [ ] all checked
- https://github.com/prestodb/presto/pull/13173 Add logging for hanging tests
## David Phillips
- [ ] all checked
- https://github.com/prestodb/presto/pull/13222 Cherry pick 142
## Grzegorz Kokosiński
- [ ] all checked
- https://github.com/prestodb/presto/pull/13176 Pass JdbcIdentity To DriverConnectionFactory#openConnection
## Hao Luo
- [ ] all checked
- https://github.com/prestodb/presto/pull/13196 GCP related backports
## James A. Gill
- [ ] all checked
- https://github.com/prestodb/presto/pull/13175 Throw exception when creating an empty spatial partition
- https://github.com/prestodb/presto/pull/13157 Fix NPE in spatial joins with GeometryCollections
- 5826162b654346dd589ae8fce0566973326dc4fd Use Flatbush instead of JTS STR RTree for spatial joins
- 69f9a9616aa293379668ba00caf985f53cef2f9f Add benchmarks for Flatbush and JTS STR RTree
- a4b621a80ae5addc0dd87d0eae9095211fe74dee Implement Flatbush Hilbert RTree
- e218678a092532b5fb47365965e2989ceef32c06 Add HasExtent interface
- fed702cae7f24a4ff085cd41371f5ec52b6103db Ignore order of rows in spatial join tests
## James Sun
- [ ] all checked
- https://github.com/prestodb/presto/pull/13237  Remove Hadoop ORC writer from Raptor
## Jiexi Lin
- [ ] all checked
- https://github.com/prestodb/presto/pull/13172 Fix flaky testVirtualBucketing()
## Karol Sobczak
- [ ] all checked
- https://github.com/prestodb/presto/pull/13210 Run allocationListener on trySetBytes and close
- https://github.com/prestodb/presto/pull/13166 Add revocable memory and reserved memory pool docs to spill
## Ke Wang
- [ ] all checked
- https://github.com/prestodb/presto/pull/13087 Resolve tables/schemas case-insensitively in JDBC connectors
## Leiqing Cai
- [ ] all checked
- https://github.com/prestodb/presto/pull/13206 Multiple Verifier Improvements
## Masha Basmanova
- [ ] all checked
- https://github.com/prestodb/presto/pull/13217 Remove predicate information from HiveSplit
- https://github.com/prestodb/presto/pull/13214 Make subfield pruning work with CBO
- https://github.com/prestodb/presto/pull/13099 Add SelectiveStreamReader for LIST type
## Nezih Yigitbasi
- [ ] all checked
- https://github.com/prestodb/presto/pull/13137 Update properties reference to add oom killer policy
## Piotr Findeisen
- [ ] all checked
- https://github.com/prestodb/presto/pull/13159 Fix travis product test stability
- https://github.com/prestodb/presto/pull/13140 Optionally ignore session zone from client
## Pratik Dhandharia
- [ ] all checked
- https://github.com/prestodb/presto/pull/13243 Add Procedure in Raptor to trigger bucket balancer
## Shixuan Fan
- [ ] all checked
- https://github.com/prestodb/presto/pull/13195 Add release note for 0.224
- 94354f309608b654a6afa7abd01cd55866630390 prepare for next development iteration - 0.225-SNAPSHOT
## Vic Zhang
- [ ] all checked
- https://github.com/prestodb/presto/pull/13228 Enforce task count limit
- https://github.com/prestodb/presto/pull/12808 Add TableStatistics in QueryInputMetadata for Join Query
- 9cc7059cd136c4618731a03307daa703823dea87 Update memory usage while building R-Tree
## Yi He
- [ ] all checked
- https://github.com/prestodb/presto/pull/12982 Move row expression up step2
## Ying Su
- [ ] all checked
- https://github.com/prestodb/presto/pull/13181 Enable setQueryMaxTotalMemory for TestingTaskContext
## Yupeng Zhang
- [ ] all checked
- https://github.com/prestodb/presto/pull/13158  Improve Presto Query Page UI
## Zhenxiao Luo
- [ ] all checked
- https://github.com/prestodb/presto/pull/12948 Support nested fields in Elasticsearch Connector
## praveenkrishna
- [ ] all checked
- https://github.com/prestodb/presto/pull/13169 Fix display of Non-Heap memory usage in UI


# Release Notes Summary

**Comment by kaikalur** [comment]
#13209 @kaikalur: 
Fixed the raptor connector to error out on unsupported types on create/alter table operations including create table as select.

**Comment by atavory** [comment]
(@highker asked me to add a note about fixed-range histograms)

#13212: Add fixed-range histograms (more efficient numerical histograms, when the range is known).
* Added a simple histogram, and a histogram with breakdown of weights within each bin. These are used / will be used by classification metrics and differential entropy UDFs.

**Comment by rongrong** [comment]
For #13087, PrestoSQL added release notes to individual connectors based on JDBC: https://prestosql.io/docs/current/release/release-309.html We can do it in similar way, or we can just add one part as: 

```
JDBC Connector Changes
-----------------------------
* Match schema and table names case insensitively. This behavior can be enabled by setting the ``case-insensitive-name-matching`` catalog configuration option to true. 

```

**Comment by viczhang861** [comment]
```
General Changes
-----------------
* Improve memory tracking for geospatial query indexing and prevent worker node down due to out of memory (#13251 )
* Added TableStatistics in QueryInputMetadata for Join Query (#12808 )
* Use Flatbush instead of JTS STR RTree for spatial joins
```

**Comment by viczhang861** [comment]
@zhenxiao I copied description in #12948 as release note,  please update if needed
```
General Changes
-----------------
Fix nested fields in Elasticsearch Connector (#12948)
```

**Comment by aweisberg** [comment]
```
General Changes
-----------------
* Allow overriding session zone sent by clients. (#13140)
```
