### ISSUE TITLE
Prevent userA from killing userB's queries

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#13297]
I understand there are 3 ways to kill somoene else's query. 
1. kill button in web ui
2. sql statement (CALL system.runtime.kill_query(query_id => '20151207_215727_00146_tx3nr', message => 'im a jerk');)
 3. api call (curl -XDELETE http://<my-presto-coordinator>:<my-port>/v1/query/20140722_203501_00017_2iwjw)

This feature is about introducing a new config flag (killEnabled), that when set to false prevents any of the above 3 kill query methods.

The reason is Sarah from accounting team may have a grudge against Bob in HR team and can maliciously disrupt his work by killing all his queries.

This global flag blocking all kills is the simpler option, later on could introduce an 'admin vs user role' where only trusted admin users are allowed to kill, plus allow a user to kill their own queries.

**Comment by rschlussel** [comment]
I think this should have admin capability from the start, and certainly allow users to kill their own queries.  
Otherwise 
1. you could have lots of unnecessary queries running due to users accidentally running a really expensive query (potentially blocking their other work or other users from running queries depending on resource group configurations)
2. Admins wouldn't be able to kill queries that are affecting cluster health.
