### ISSUE TITLE
JDBC identity not passed down to connection properties

### ISSUE THREAD

**Issue by hellium01** [prestodb/presto#13355]
We added support for passing through credential to connectors. However, we are not yet utilizing this information making new connections:

https://github.com/prestodb/presto/blob/db03518bf342c8fb74ace9ba25f2b0c78991953a/presto-base-jdbc/src/main/java/com/facebook/presto/plugin/jdbc/DriverConnectionFactory.java#L60

**Comment by duyquangnguyenhac** [comment]
I would like to claim this issue if possible, James

**Comment by highker** [comment]
@hellium01, has this issue been assigned to anyone else? Otherwise, @duyquangnguyenhac can take it.

**Comment by hellium01** [comment]
Nope, please feel free to assign to your self @duyquangnguyenhac.

**Comment by duyquangnguyenhac** [comment]
I'm not sure how can I self-assign this issue, could someone assign it to me ?
James

**Comment by hellium01** [comment]
It seems like the same issue is already solved on prestosql: https://github.com/prestosql/presto/commits/master/presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/DriverConnectionFactory.java, so likely you just need to back port the last two commits that changed this file.

**Comment by tooptoop4** [comment]
would this work if there are say 3 catalogs/connectors, can it use user credentials to mysql, config credentials to postgres and then 'NTADMIN/'+user credentials to MSsqlServer? If so how can this be specified ?

**Comment by duyquangnguyenhac** [comment]
> It seems like the same issue is already solved on prestosql: https://github.com/prestosql/presto/commits/master/presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/DriverConnectionFactory.java, so likely you just need to back port the last two commits that changed this file.

Can you elaborate on what I need to do here? I'm not sure what you mean by back port the two commits

**Comment by tooptoop4** [comment]
@duyquangnguyenhac prestosql repo has the fix, you can lift&shift to prestodb repo

**Comment by hellium01** [comment]
Yes, please make sure to include the original author if you decided to do that.  The implementation might need to be tweaked a little bit to support multiple connector cases.

**Comment by duyquangnguyenhac** [comment]
I'm working on it right now, please give me a few days to analyze how the program work and how to fix this issue. Thank you, James!

**Comment by duyquangnguyenhac** [comment]
@hellium01 how can I contact you on slack ?
- James

**Comment by duyquangnguyenhac** [comment]
Hi, 
If you could, can you guide me a little? As a beginner, this is a little bit overwhelming for me to complete. I'm still confused on what I needed to tweak because it's such a large repo, and I do not understand how can I test the programs. I've been committing the changes made on prestosql onto prestodb, I just need a way to check if it works. 
- James

**Comment by Xwanchai** [comment]
- [0]

**Comment by duyquangnguyenhac** [comment]
Hi,
I'm backporting the commits but there's a lot of missing methods, and conflicts. I need some help, if it's not possible for someone to assist me, then it'd be better for this issue be assigned to someone else.

**Comment by rongrong** [comment]
@duyquangnguyenhac I believe this is the commit you need to backport: https://github.com/prestosql/presto/pull/1124/commits/17d597660ad1eca49155ad6b2aebd5175d225965

Which methods are missing?

**Comment by duyquangnguyenhac** [comment]
In general, there are slightly different implementations across prestosql and prestodb. I don't fully comprehend the usage of each method, so I'm not sure if I can make my own changes. I've been backporting the last three commits, since "Allow user and password passthrough in jdbc connector".  Particularly methods like "getConnectionUrl" or "setCaseInsenitiveNameMatchingCacheTtl" shown in the picture attached. It doesn't exist in prestodb. So what do I do?


<img width="933" alt="Screen Shot 2019-11-05 at 2 30 37 PM" src="https://user-images.githubusercontent.com/52845974/68239416-e9150b00-ffd8-11e9-8167-224fcf29a730.png">

**Comment by duyquangnguyenhac** [comment]
<img width="793" alt="Screen Shot 2019-11-11 at 3 09 53 PM" src="https://user-images.githubusercontent.com/52845974/68617575-8d91c400-0495-11ea-9be4-57b68a69a337.png">
<img width="924" alt="Screen Shot 2019-11-11 at 3 10 14 PM" src="https://user-images.githubusercontent.com/52845974/68617576-8d91c400-0495-11ea-89f8-3758028f6bee.png">

As you can see, in the MySQLClient, i'm having trouble implementing the line connectionFactory (config, mySqlconfig). As far as I can see, prestodb and prestosql has entirely different implementation of DriverConnectionFactory.java. One uses credentialprovider and the other uses BaseJDBCconfig. I'm cautious to mimic the code in prestosql because it will cause further problems and I'd have to add more methods that's not in prestodb.

**Comment by duyquangnguyenhac** [comment]
Hello, at this point I think it is best if you reassigned this subject? I haven't been getting any replies.

**Comment by highker** [comment]
already fixed
