### ISSUE TITLE
Queries are getting stuck.

### ISSUE THREAD

**Issue by dggs123** [prestodb/presto#13488]
Hi,

We are running presto with 6 workers(r5.4xlarge ec2 machines). Even then, when we have more than 60 queries/ or have a greedy query which takes mostly 100-150 GB of reserved memory. The whole system is getting stuck. We saw the queries which take a few secs, taking hours to run.

We looked into the cause and found out at some point the threads on workers are getting stuck. Still, not able to figure out why it's happening.

Presto version we are using `302-E.9`.

Jstack thread dump of a worker.
[jstack.log](https://github.com/prestodb/presto/files/3676478/jstack.log)

**Comment by tooptoop4** [comment]
V302 is not in Prestodb repo

**Comment by findepi** [comment]
@dggs123, as @tooptoop4 pointed out, Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)

I see you're using Starburst Presto release. Appreciated! If you have a support subscription, contact the Starburst Support.
Otherwise I recommend using the slack link above.

**Comment by tooptoop4** [comment]
similar to https://github.com/prestodb/presto/issues/11952
