### ISSUE TITLE
Whats the process to include presto-oracle?

### ISSUE THREAD

**Issue by dprophet** [prestodb/presto#13959]
Whats the process to include
https://github.com/marcelopaesrech/presto-oracle

Within this org's standard presto? Oracle is a big use case for us and, IMO, its better to have upstream.

**Comment by aweisberg** [comment]
Someone would have to open up a PR adding the connector. I think it's a useful addition since Oracle is commonly used.

There is also https://github.com/prestosql/presto/pull/1959 to consider instead.

It looks like even if we had this it couldn't ship in the regular build due to licensing issues? The code would just be there for other people to build?

**Comment by fgwang7w** [comment]
I can use this issue to add support for oracle connector, in reference to https://github.com/prestosql/presto/pull/1959
