### ISSUE TITLE
Lazy Block loading is not utilized efficiently in case of nested column project pushdown on Parquet tables

### ISSUE THREAD

**Issue by vkorukanti** [prestodb/presto#14517]
The main issue is we read all subfields in one column. We should separate each subfield into its own column in Scan.

For example `select msg.a, msg.b, msg.c from tbl where msg.a=10`. In the existing implementation on 217 at Uber, we were reading the `msg.a`, `msg.b` and `msg.c` as separate blocks. In 230, we read the entire `msg.[a,b,c]` as one Block. This doesn’t utilize the lazy block loading during filter evaluation for `msg.a=10`. In 217 we were just loading the `msg.a` first and decide whether to load `msg.b` and `msg.c`, but in 230 we are loading all `msg.[abc]` at once as part of the filter evaluation.

This causes too much IO pressure.

**Comment by vkorukanti** [comment]
After discussion with @zhenxiao, @mbasmanova, the plan to fix this is follows:

* backport https://github.com/prestosql/presto/commit/4928507ecd2a60bc12aba0dd714d26491045c85a, which allows projection pushdown for individual columns 
* implement pushdown optimization for hive connector, similar to: https://github.com/prestosql/presto/commit/9aacfde3d12e2d6fa8e145df80d3b57e3bc9d716, but using our connector based optimizer 
* optimize the scan in Parquet reader

**Comment by mbasmanova** [comment]
CC: @prestodb/aria

**Comment by zhenxiao** [comment]
hi @vkorukanti @mbasmanova 
After checking the code, I am thinking, since we already have Subfield in ColumnHandle, I think we could skip backporting:
https://github.com/prestosql/presto/commit/4928507ecd2a60bc12aba0dd714d26491045c85a

which is complicated and time consuming.

Instead, we could directly implement optimizer, leverage Subfield to do dereference pushdown.

Proposed a plan like:

- implement pushdown optimization for hive connector, similar to: prestosql/presto@9aacfde, but using our connector based optimizer, and use Subfield, instead of projected columns
- optimize the scan in Parquet reader

What do you think?

**Comment by mbasmanova** [comment]
@zhenxiao Sounds good to me. I'd say give it a try.
