### ISSUE TITLE
Cannot access worker page from Query Details Page

### ISSUE THREAD

**Issue by chalmagr** [prestodb/presto#15121]
The Stages section of the Query Details page (corresponding to "execute statement1") shows the stages of the execution and for each it shows how the work was allocated throughout several workers.
These workers are currently showing their IP under the Host column (not their IDs). When I click on the IP it is sending me to an invalid URL: /ui/worker.html?undefined

If I replace the 'undefined' above with the worker id I get the page to load properly with the worker stats.

Haven't been able to find any information online if this could be some missing configuration or not... I used the Deploying Presto guide to create the cluster and it seems to be running smoothly.

Using Version 0.239.2

Thanks,
Christian

**Comment by tdcmeehan** [comment]
Thanks for reporting this bug @chalmagr.  Looks like it was introduced in 67114fb606ce535151c492b05a4bdda91f3cd4be by removing `nodeId` from `TaskStatus`.  A reasonable fix can be to simply re-introduce it, but back into `TaskInfo` (since it is cheaper to maintain there than in `TaskStatus`).  This is a simple fix and it is free for anyone to pick up.

**Comment by agrawalreetika** [comment]
I think there is a bug, I don't see the Tasks section on the Query Details page for any query.

**Comment by ergouy** [comment]
> worker id

where is the worker id?
