### ISSUE TITLE
Cumulative user memory is 0

### ISSUE THREAD

**Issue by GXM2333** [prestodb/presto#15597]
We use presto release 241, we write our own connectors. our ConnectorPageSource has implemented `getCompletedBytes` method ,why the Cumulative user memory from presto admin is still 0. Does it will cause reserved pool memory never be used?
presto admin sql UI:
![sql](https://user-images.githubusercontent.com/24871202/103990480-45228300-51cc-11eb-95e3-4dabe2acbab7.png)

While executing the above sql, I debugged it and get a positive number from our connector's `getCompletedBytes` method.
![debug](https://user-images.githubusercontent.com/24871202/103990358-07bdf580-51cc-11eb-9c04-8e94ff23aa72.png)

Is something wrong of our used case?Please help us.

**Comment by rschlussel** [comment]
Completed bytes tells how much data has been processed. That's not really related to how much user memory the query is using, since user memory is how much memory is used e.g. for building hash tables for joins.  Your query is a simple select with a filter, so I wouldn't expect it to use any user memory

**Comment by GXM2333** [comment]
Thanks a lot. :)
