### ISSUE TITLE
presto can not fetch partitioned table data

### ISSUE THREAD

**Issue by SilvesSun** [prestodb/presto#15627]
same as [article](http://hadoopdk.blogspot.com/2017/04/hive-partitioned-tables-issue-with.html), after alter column of a partitioned table, only new partition can fetch data, but old partition cause exception: column type mismatch

**Comment by dborkar** [comment]
@SilvesSun thanks for pointing out. we'll take a look.

**Comment by imjalpreet** [comment]
@SilvesSun The error you are facing is due to the fact that when the table schema was updated the older partitions' schema wasn't updated and due to that presto encounters a schema mismatch for the respective column. Presto currently doesn't support such coercions and therefore throws the related exception.

To resolve this, as a workaround you can update the schema for the older partitions as well. You can do this by performing alter table individually for each partition or you can set the following session property before executing alter statement for the table, something like this:

```
SET hive.exec.dynamic.partition = true;
ALTER TABLE table_name PARTITION (partition_column) 
CHANGE COLUMN old_col new_col data_type;
```

This property will enable dynamic partitioning that means alter statement will change all partitions.

**Comment by SilvesSun** [comment]
thanks

**Comment by PraneethGudumasu** [comment]
This workaround does not work for us. We have a column of date data type and Presto throws us the exception after the attribute is modified to timestamp type.  Our Presto version is 0.234. Is it because of the Presto version, the workaround does not work or date to timestamp coercion is the problem ?

**Comment by imjalpreet** [comment]
@PraneethGudumasu Can you elaborate a bit more on what is the error message you are seeing? 

Also, since you are using a very old Presto version(almost 2-3 years old) it is very difficult to comment on whether that would be an issue or not. But I would recommend that you try to upgrade presto to a more recent version.

**Comment by imjalpreet** [comment]
@PraneethGudumasu The error you are facing is because of datatype mismatch between actual ORC files and Hive Metastore. Date and Timestamp cannot be coerced. So, you will have to make sure the datatype of the column in the ORC file as well as the metastore is the same. You can probably create a new table and move the data from the old ORC table.

**Comment by PraneethGudumasu** [comment]
@imjalpreet Thanks for confirming. so i ended up writing a Spark program to read the data , cast the date and overwrite the partition.
