### ISSUE TITLE
MAP_UNION accepts ORDER BY syntax but does not do the right thing at execution

### ISSUE THREAD

**Issue by kaikalur** [prestodb/presto#15754]
MAP_UNION aggregation accepts the ORDER BY clause but it's not actually respecting it. So either we disallow/warn about the syntax or implement it properly (preferred).

```
presto:di> select map_union(x order by y desc) from (select 10, map(array[1], array['a']) union all select 1, map(array[1], array['b'])) T(y, x);
 _col0
-------
 {1=b}

presto:di> select map_union(x order by y asc) from (select 10, map(array[1], array['a']) union all select 1, map(array[1], array['b'])) T(y, x);
 _col0
-------
 {1=b}
 ```

**Comment by nmahadevuni** [comment]
@kaikalur : I debugged the query. Found that PruneOrderByInAggregation rule removes the ORDER BY from this aggregation because the "orderSensitive" flag was set to false while constructing InternalAggregationFunction object. Any reason for it to be marked as order insensitive? If not, I can send a PR for this.

**Comment by rongrong** [comment]
> @kaikalur : I debugged the query. Found that PruneOrderByInAggregation rule removes the ORDER BY from this aggregation because the "orderSensitive" flag was set to false while constructing InternalAggregationFunction object. Any reason for it to be marked as order insensitive? If not, I can send a PR for this.

Feel free to send a PR to fix this. Thanks for your contribution!
