### ISSUE TITLE
Missing S3 SDK metrics table in jmx.current

### ISSUE THREAD

**Issue by wjyao0316** [prestodb/presto#16526]
I am trying to set up the SDK metric for presto and I don't see the table S3 sdk metric when I list all tables. 

I am able to find the glue sdk metric in table `com.facebook.presto.hive.metastore.glue:name=hive,type=gluehivemetastore`.
Based on the [PrestoS3FileSystem Code](https://github.com/prestodb/presto/blob/7e4fe3d909a598d561b7e9b8b37c606a9df7241c/presto-hive/src/main/java/com/facebook/presto/hive/s3/PrestoS3FileSystem.java#L163)
Following the same pattern the table name should be something like "com.facebook.presto.hive.metastore.glue:name=hive,type=prestos3filesystem", but there is nothing close to it. 

The Presto Version I use is `0.245.1-amzn-0`, the EMR version is 6.3.0

**Comment by rohanpednekar** [comment]
@imjalpreet do you think you can help here?

**Comment by pettyjamesm** [comment]
I believe the name you would be looking for is `"com.facebook.presto.hive.s3:name=hive,type=prestos3filesystem"`, are you sure you don't see it listed there? If not, it's probably because you're using EMRFS as your file system implementation (this is probably the default in EMR, the value is configured via `"hive.s3-file-system-type"` in your `catalog/hive.properties` configuration file) which doesn't publish stats via JMX that way. If you configure `hive.s3-file-system-type=PRESTO` then you should start getting those stats (although note: this is a fundamentally different hadoop `FileSystem` implementation, so performance characteristics may change as a result).

**Comment by wjyao0316** [comment]
That makes a lot of sense. I use EMRFS as the file system implementation since it is recommended by EMR. 

Thanks!
