### ISSUE TITLE
Optimize joins with "similar" subqueries

### ISSUE THREAD

**Issue by martint** [prestodb/presto#1732]
Optimize queries of the following shape:

``` sql
SELECT * 
FROM (
   SELECT k, agg1, agg2
   FROM t
   GROUP BY k
) a
JOIN (
   SELECT k, agg3, agg4
   FROM t
   GROUP BY k
) b
ON (a.k = b.k)
```

as

```
SELECT k, agg1, agg2, agg3, agg4
FROM T
GROUP BY k
```

More generally, if we know `k` contains distinct values, optimize

``` sql
SELECT * 
FROM (
   SELECT k, v1, v2
   FROM t
) a
JOIN (
   SELECT k, v3, v4
   FROM t
) b
ON (a.k = b.k)
```

as

``` sql
SELECT k, v1, v2, v3, v4 
FROM t
```

**Comment by zhenxiao** [comment]
@martint @dain May I ask a question about this optimization?
In the OutputNode of a join query, there will be 2 outputs for the join key, one from left table and one from right table, say, a.k and b.k, probably symboled like key and key_1
when optimize into an aggregation query, the OutputNode still expects both key and key_1, so the aggregationNode should output both key and key_1, and they are actually referring to the same column in the table.
Do you think the optimization should rewrite the OutputNode, only output one key, so that tableScanNode only has one output for the key column, so is ProjectNode and AggregationNode.
Or both key and key_1 should be kept in all the nodes, and the optimization should carefully deal with all the key and key_1 assignments in the NodeTree?
