### ISSUE TITLE
How to evaluate memory config in Spark on Presto mode

### ISSUE THREAD

**Issue by JySongWithZhangCe** [prestodb/presto#17589]

**Comment by JySongWithZhangCe** [comment]
For now, users have to do some tests for every sql in Presto on Spark to set memory size. Each sql will run failed 3 ~ 5 times  due to OOM.

**Comment by JySongWithZhangCe** [comment]
@rongrong Could you please take a look~Thx:)

**Comment by rohanpednekar** [comment]
cc @aweisberg @sambekar15

**Comment by JySongWithZhangCe** [comment]
> @souravpal is working on automatically setting hash partition count which should help for most queries. I am also interested in doing some automation to automatically request larger containers for either the entire query or just failing tasks, but that is mostly just an idea RN.
> 
> Which memory settings do you find are problematic and need setting for every query?

`spark.executor.instances`, `spark.executor.cores` and `spark.executor.memory` need setting for every query.

Father more, I found that even if the product of the three parameters remains the same, the effect of different ratios is not the same, which is not the same as spark.

In my case, when I set small `spark.executor.instances` and big `spark.executor.cores` & `spark.executor.memory`, the query will be OOM, but I set big `spark.executor.instances` and small `spark.executor.cores` & `spark.executor.memory`, the query will run well.

**Comment by JySongWithZhangCe** [comment]
Q1：Where is it failing? 
A1：I can't make sure which stage is failing, because the whole execution pipeline is invisible, so I opened another issue https://github.com/prestodb/presto/issues/17590.

Q2: Are you setting any of the presto memory configs - query.max-memory-per-node, query.max-total-memory-per-node. 
A2: I haven't set `query.max-memory-per-node` and `query.max-total-memory-per-node`. I just set `task.concurrency`, `task.max-worker-threads` and `task.write-count` as https://prestodb.io/docs/current/installation/spark.html mentioned. There are some parameter-differences between `Presto Cluster` and `Presto on Spark`. For now, it's hard to know how to set parameters in `Presto on Spark` mode.

I will try both `query.max-memory-per-node= spark.executor.memory ~ 70% ` and `tune hash partition count`.

Thinks for your advice!

**Comment by sambekar15** [comment]
@JySongWithZhangCe  I am not aware of spark.initial-partition-count. Are you referring to hash partition count? It is a presto config not spark one - query.hash-partition-count. you can relate this to spark.sql.shuffle.partitions. You need to set this presto config query.hash-partition-count  for controlling number of shuffle tasks. The default value is 100. Check your workload size, shuffle read size, ~ task read size  before increasing this otherwise It may result in small files if you increase unnecessary. Spark Driver log has the presto query plan and has details on the default configs passed . Spark Driver log should have the error stack trace . You can drill down into spark UI to get Shuffle Read Size , approximate task read shuffle size.  Also as Ariel mentioned, team is working on automating hash partition count which should help for most queries. Until then you can do above exercise to determine query.hash-partition-count in case you want to increase it.

**Comment by JySongWithZhangCe** [comment]
> 

Thinks for your great explanation! It's really helpful !

**Comment by JySongWithZhangCe** [comment]
> Thinks for your great explanation! It's really helpful !



> @JySongWithZhangCe I am not aware of spark.initial-partition-count. Are you referring to hash partition count? It is a presto config not spark one - query.hash-partition-count. you can relate this to spark.sql.shuffle.partitions. You need to set this presto config query.hash-partition-count for controlling number of shuffle tasks. The default value is 100. Check your workload size, shuffle read size, ~ task read size before increasing this otherwise It may result in small files if you increase unnecessary. Spark Driver log has the presto query plan and has details on the default configs passed . Spark Driver log should have the error stack trace . You can drill down into spark UI to get Shuffle Read Size , approximate task read shuffle size. Also as Ariel mentioned, team is working on automating hash partition count which should help for most queries. Until then you can do above exercise to determine query.hash-partition-count in case you want to increase it.

Thinks for your great explanation! It's really helpful !
