### ISSUE TITLE
Support submit sql by JDBC in Presto on Spark mode

### ISSUE THREAD

**Issue by JySongWithZhangCe** [prestodb/presto#17591]

**Comment by rohanpednekar** [comment]
If I am not wrong, @sambekar15 explored a few options and workaround for this. CC @aweisberg

**Comment by aweisberg** [comment]
We don't really have a way to offer this without standing up a service to start Spark drivers (and this requires some place to run them) that can then redirect JDBC clients to Presto on Spark. Currently Presto on Spark doesn't expose the endpoints a Presto client requires so that work would need to be done as well.

I don't know of anyone planning to undertake this in the near future.

**Comment by JySongWithZhangCe** [comment]
> We don't really have a way to offer this without standing up a service to start Spark drivers (and this requires some place to run them) that can then redirect JDBC clients to Presto on Spark. Currently Presto on Spark doesn't expose the endpoints a Presto client requires so that work would need to be done as well.
> 
> I don't know of anyone planning to undertake this in the near future.

Thx:)
I'm looking to see if there is any other way.
