### ISSUE TITLE
Add unit to RuntimeMetric

### ISSUE THREAD

**Issue by yuanzhanhku** [prestodb/presto#17633]
RuntimeMetric is used to track the per query execution stats. It was added in this issue: https://github.com/prestodb/presto/issues/16654

Currently it can only be used to track integer metrics, such as latency, CPU time, number of bytes, count, etc. There is currently no clean way to distinguish which type it is. It is better to add a enum unit to it so that we can display the metrics in different formats in the coordinator UI.

https://github.com/facebookincubator/velox/pull/1391 added the support in Velox. This issue tracks the work in the presto Java stack.

**Comment by mbasmanova** [comment]
CC: @majetideepak

**Comment by zacw7** [comment]
If unit is added to runtime metric, it makes sense to keep it as part of the key to avoid conflict, but changing the RuntimeStats from `Map<String, RuntimeMetric>` to `Map<RuntimeMetricKey, RuntimeMetric>` makes it not JSON serializable. For example, the following JSON is invalid cause objects cannot be keys: 
```JSON
"runtimeStats": {
  {"name": "getTableHandleTimeNanos", "unit": "NANO"}: {
    "name": "getTableHandleTimeNanos",
    "unit": "NANO",
    "sum": 42914,
    "count": 1,
    "max": 42914,
    "min": 42914
  },
  {"name": "S1-storageReadDataBytes", "unit": "BYTE"}: {
    "name": "S1-storageReadDataBytes",
    "unit": "BYTE",
    "...": "..."
  },
  "...": "..."
}
```
Also our current protocol changes actually has redundant information:
```JSON
"runtimeStats": {
  "getTableHandleTimeNanos": {
    "name": "getTableHandleTimeNanos",
    "sum": 42914,
    "count": 1,
    "max": 42914,
    "min": 42914
  },
  "S1-storageReadDataBytes": {
    "name": "S1-storageReadDataBytes",
    "...": "..."
  },
  "...": "..."
}
```
Note that we use the metric names as the keys of the entries, but they are also part of the values.
PR #17658 added the unit to runtime metric and also changed the protocol structure into following:
```JSON
"runtimeStats": {
  {
    "name": "getTableHandleTimeNanos",
    "unit": "NANO",
    "sum": 42914,
    "count": 1,
    "max": 42914,
    "min": 42914
  },
  {
    "name": "S1-storageReadDataBytes",
    "unit": "BYTE",
    "...": "..."
  },
  "...": "..."
}
```
RuntimeStats is no long a map but a collection. There is no redundant information and we can always build a map from it if needed. 
Right now there are two issues:
1. Verifier is broken: https://github.com/prestodb/presto/pull/17658#issuecomment-1119035294 => I think the root cause is the old verifier cannot recognize the new structure. But as long as there is inconsistency it is always gonna break. Wondering how do we normally handle this case? @aweisberg 
2. CPP worker is broken. => Can @amitkdutta help to evaluate if CPP can adopt this new structure?

**Comment by zacw7** [comment]
I would love to hear your thoughts on this: @NikhilCollooru @mbasmanova

**Comment by mbasmanova** [comment]
The proposed change makes sense to me. @amitkdutta Amit, let's check that we can adapt Prestissimo to this.

**Comment by aweisberg** [comment]
> 1. Verifier is broken: [Add unit to RuntimeMetric #17658 (comment)](https://github.com/prestodb/presto/pull/17658#issuecomment-1119035294) => I think the root cause is the old verifier cannot recognize the new structure. But as long as there is inconsistency it is always gonna break. Wondering how do we normally handle this case? @aweisberg

Breaking changes to the protocol create an incompatibility across versions.  That verifier run is failing because it is using the latest verifier with an older version of Presto. So for example when we got to do release verification we won't be able to use verifier to compare control and test for the release that makes the breaking change.

I don't know what we do for breaking protocol changes. In 3 years I don't recall us making one. I don't recall seeing us version the protocol.

Is it possible to accomplish this without a breaking change?

**Comment by amitkdutta** [comment]
@zacw7 Breaking change is fine. If you plan to make RuntimeStas a List instead of a map, that's good as well. It needs to be something that can be serialized/deserialized to json.

**Comment by zacw7** [comment]
> > 1. Verifier is broken: [Add unit to RuntimeMetric #17658 (comment)](https://github.com/prestodb/presto/pull/17658#issuecomment-1119035294) => I think the root cause is the old verifier cannot recognize the new structure. But as long as there is inconsistency it is always gonna break. Wondering how do we normally handle this case? @aweisberg
> 
> Breaking changes to the protocol create an incompatibility across versions. That verifier run is failing because it is using the latest verifier with an older version of Presto. So for example when we got to do release verification we won't be able to use verifier to compare control and test for the release that makes the breaking change.
> 
> I don't know what we do for breaking protocol changes. In 3 years I don't recall us making one. I don't recall seeing us version the protocol either. We have been lucky to not need it since we don't really do online upgrades.
> 
> Is it possible to accomplish this without a breaking change?

Unfortunately I'm not able to find other way. Unit is an extra information that the current Presto version cannot recognize.
