### ISSUE TITLE
Presto is not rounding decimals correctly.

### ISSUE THREAD

**Issue by jharringtonCoupons** [prestodb/presto#17859]
We are currently moving from Hive EMR to Athena Presto. During testing and validation, we noticed penny variances on transactions. Root cause analysis shows that Presto is not rounding correctly beyond 14 digits of decimal precision.

Attempts to resolve these variances only increase the total number of variances by causing **more** penny variances on other records. So, we solve one record's value, but create `[1 + n]`  more problems elsewhere. Is there any way to correct for this other than moving these calculations into an ETL engine and handling it there?

Note: the input values to the ROUND() function are, themselves, errors on floating point operations while we are multiplying two decimal columns together on-the-fly in a SELECT statement.

Expected result from below sample calculation: 6.98

```
-- 15 digits of decimal precision.
SELECT ROUND(6.984999999999999, 2)  -- Hive (EMR):       6.98
SELECT ROUND(6.984999999999999, 2)  -- Presto (Athena):  6.99

-- Remove one level of precision (i.e., 14).
SELECT ROUND(6.98499999999999, 2)   -- Presto (Athena):  6.98
```

**Comment by rohanpednekar** [comment]
What Presto version you are using? can you try open-source version of Presto and let us know the feedback?

**Comment by jharringtonCoupons** [comment]
@ClarenceThreepwood Thank you for looking into this and confirming on the higher version of Presto. By any chance, and as a sanity check, can you check out the `0.217` version and confirm that you are able to re-produce the same error? 

It looks like this will be a more challenging effort to resolve on our end because we do not control what version of Presto is installed on AWS's EMR clusters - AWS controls that. We can look at raising a ticket with them to see if they can take care of it for us; and I prefer this resolution path because we will be running on the latest version of Presto, which contains the latest bug fixes, features, enhancements, etc. But, I think AWS would like to see that the error can be re-produced on Presto `0.217` and resolved on the `0.273` versions that is available.

Any help/consideration is greatly appreciated.

**Comment by rohanpednekar** [comment]
cc @pettyjamesm FYI

**Comment by pettyjamesm** [comment]
@ClarenceThreepwood - when you query Athena, are you expressing those values as literals in the query string like above? The behavior shown in the issue description, where the literal expressions are being evaluated will behave differently in Athena than when reading decimals from input sources. The reason you're getting the results for Athena that don't match EMR presto is because Athena actually parses literal values in the query string as `double` instead of `DECIMAL`, at which point you're seeing floating point errors affecting the result. You should get the correct result on Athena running something like this instead:

```
SELECT ROUND(DECIMAL '6.984999999999999', 2); -- (Athena) 6.980000000000000
```

**Comment by jharringtonCoupons** [comment]
@pettyjamesm 

We are calculating a new column on-the-fly by multiplying two columns together and then rounding them to two decimal places. 

In preparing a detailed example, after further review, it appears that Presto is correct and Hive EMR is not. My apologies for the confusion. I am inclined to close this ticket to working as-is, although I still think that the ROUND(), when used in isolation, is not functioning properly in Presto `0.217`.

**Meta Data:**
```
Presto Column A  : DECIMAL(10,2)
Presto Column B  : DECIMAL(18,6)
Hive Column A    : DOUBLE
Hive Column B    : DOUBLE
```

Below is a sample of the raw inputs. Ironically, the interim calculation of multiplying Column A by Column B yields an inaccurate result, which I understand to be due to errors with how hardware and software handle floating point arithmetic. But, once the value is rounded, it is corrected.

```
-- COLUMN A * COLUMN B  : 139.70 * 0.0500000
Calculator              : 6.985
Hive pre-rounded        : 6.98 <- WRONG!
Presto no round         : 6.985
Presto with round       : 6.99
```

When I plug in for the values above in Athena, I get the following:

```
SELECT 139.70 * 0.050000 -- 6.984999999999999
UNION ALL
SELECT ROUND(139.70 * 0.050000, 2) -- 6.99
UNION ALL
SELECT ROUND(6.984999999999999, 2) -- 6.99 <- I expected this to round down to 6.98
UNION ALL
SELECT ROUND(DECIMAL '6.984999999999999', 2) -- 6.99   
```

**Comment by pettyjamesm** [comment]
> Ironically, the interim calculation of multiplying Column A by Column B yields an inaccurate result, which I understand to be due to errors with how hardware and software handle floating point arithmetic.

Correct. The `DOUBLE` data type (or `double` natively in Java) is an IEEE754 64 bit floating point value which can lose precision in a number of ways either because a given value can't has no valid 64 bit floating point representation or as a result of performing arithmetic operations on them. As such, `double` is not a suitable data type to represent, e.g.: monetary amounts when precision loss is not desirable. In those cases `DECIMAL` types should be preferred since represents and operates over a fixed precision representation.

A quirk of Athena, which is not the default behavior in most presto clusters- is that literal values in the query string like `1.0` have an inferred type of `DOUBLE` instead of `DECIMAL`, so `ROUND(6.984999999999999, 2)` is rounding using `double` arithmetic which loses precision. If instead you force the type to be `DECIMAL`, then the correct result is returned:

```
SELECT ROUND(DECIMAL '6.984999999999999', 2); -- 6.980000000000000 (Athena)
```

However, if you perform that _same_ operation inside of the `UNION ALL` chain that you included above, the result column is again inferred to be of type `DOUBLE` because the other values returned by the other unions are of type `DOUBLE`, and again the floating point precision loss could be introduced again as a result of the conversion. However, testing the specific operation in Athena I get a result of `6.98` and not `6.99`.

**Comment by jharringtonCoupons** [comment]
`A quirk of Athena, which is not the default behavior in most presto clusters- is that literal values in the query string like 1.0 have an inferred type of DOUBLE instead of DECIMAL, so ROUND(6.984999999999999, 2) is rounding using double arithmetic which loses precision. If instead you force the type to be DECIMAL, then the correct result is returned`

I did not know that about Athena. Thank you for raising that awareness with me.

I will go ahead and close the ticket. T
