### ISSUE TITLE
Pinot subqueries may generate subtasks with missing column selectors

### ISSUE THREAD

**Issue by cliandy** [prestodb/presto#17998]
The generated subtask query doesn't have any selected columns which fails the query. In the example, if the `col2 > 0` predicate is removed, the query will run properly. Running in Presto 0.273 with gRPC connector.

Example
```sql
SELECT * 
FROM table
WHERE id = 
  (select id FROM table where id = '123' and col2 > 0)
```

Subtask Query

```sql
"SELECT  FROM table__TABLE_NAME_SUFFIX_TEMPLATE__ 
WHERE ((\"id\" = '123') 
AND (\"col2\" > 0))__TIME_BOUNDARY_FILTER_TEMPLATE__ LIMIT 21"...
```
Expected
```sql
"SELECT id  FROM ...
```

**Comment by timkocik** [comment]
This query is also failing, selecting a specific column(s) when there is a join and where clause condition on the same column that is joined on.
```
SELECT id 
FROM table
JOIN table2 ON table.id=table2.col1
WHERE table2.col1='123'
```
If the where clause only checks columns not in the join condition, the query will run properly, and the query also runs properly if the where condition references a variable rather than literal (e.g. '123').
SELECT * also works with this same query whereas SELECT a specific column(s) fails.

Similarly the subtask query:
```
SELECT  FROM table2__TABLE_NAME_SUFFIX_TEMPLATE__ WHERE ("col1" = \'123\')__TIME_BOUNDARY_FILTER_TEMPLATE__ LIMIT 21...
```

**Comment by xiangfu0** [comment]
Thanks for reporting, I will take a look!

cc: @dongxiaoman

**Comment by nizarhejazi** [comment]
@highker can you assign me this issue? I will work on a fix.

**Comment by nizarhejazi** [comment]
@highker Sent a fix here: https://github.com/prestodb/presto/pull/18067. Can you please review?

**Comment by xiangfu0** [comment]
Put a fix here: https://github.com/prestodb/presto/pull/18105

**Comment by xiangfu0** [comment]
Can you check on the latest change and see if it resolved this issue?

**Comment by cliandy** [comment]
looking good, thanks @xiangfu0 !
