### ISSUE TITLE
[native] test-native github action workflow keeps failing with SIGSEGV

### ISSUE THREAD

**Issue by mshang816** [prestodb/presto#18290]
here is one example https://github.com/prestodb/presto/runs/8211210675?check_suite_focus=true
From the log of running test case TaskManagerTest.outOfQueryUserMemory():
*** Aborted at 1662482470 (Unix time, try 'date -d @1662482470') ***
*** Signal 11 (SIGSEGV) (0x0) received by PID 3568 (pthread TID 0x7ff224efa700) (linux TID 3568) (code: address not mapped to object), stack trace: ***
(error retrieving stack trace)

somehow stack trace is not available for further debugging. But one observation is this failure seem to be aways happening in TaskManagerTest.outOfQueryUserMemory and after tons of "MEM_CAP_EXCEEDED" errors. Not sure if it's related to the fact that the default github action runner only have 7GB in RAM.

**Comment by mbasmanova** [comment]
CC: @majetideepak

**Comment by mbasmanova** [comment]
CC: @tanjialiang

**Comment by spershin** [comment]
I noticed on mac (local E2E test run) that workers are crashing on seemingly random tests. I run TestHiveQueriesUsingJSON.
My last run two tests failed: 'testCast' and 'testPrestoBenchTables'.
Before that only one failed: 'testTimestampWithTimeZone'.
On GH see [examples](https://github.com/prestodb/presto/runs/8141784947?check_suite_focus=true) of other failed: 'testFiltersAndProjections' and others.

It indicates that issue is systemic and does not depend on what query we run.

I also don't see the EXCEEDED errors in the worker logs on mac. What I see is abruptly finished log (way before the end of the test run) and the 'presto_server' processes disappear (there must be 4 of them).
That might indicate that what I see is different issue?

**Comment by ZacBlanco** [comment]
I have encountered another similar segfault recently.

```
[       OK ] PrestoExchangeSourceTest/PrestoExchangeSourceTest.retryState/7 (1501 ms)
[ RUN      ] PrestoExchangeSourceTest/PrestoExchangeSourceTest.retries/0
[       OK ] PrestoExchangeSourceTest/PrestoExchangeSourceTest.retries/0 (3536 ms)
[ RUN      ] PrestoExchangeSourceTest/PrestoExchangeSourceTest.retries/1
E20240509 18:11:12.847795 10408 EventBase.cpp:1045] EventBase: failed to schedule timeout: Operation now in progress
*** Aborted at 1715278272 (Unix time, try 'date -d @1715278272') ***
*** Signal 11 (SIGSEGV) (0x100) received by PID 6483 (pthread TID 0x7f3035ffb700) (linux TID 10409) (code: address not mapped to object), stack trace: ***
(error retrieving stack trace)


91% tests passed, 1 tests failed out of 11

Total Test time (real) =  52.83 sec
```

Full CI log: [segfault-log.txt](https://github.com/prestodb/presto/files/15266712/segfault-log.txt)

**Comment by czentgr** [comment]
> I have encountered another similar segfault recently.
I've seen the same SEGV on a local system (Linux). Because the SEGV does look different and occurs in a different test I've created a new issue for it: https://github.com/prestodb/presto/issues/22714

**Comment by majetideepak** [comment]
We moved from github actions to CircleCI. I am closing this.
