### ISSUE TITLE
Presto CLI sql folding should replace end-of-line comment with c-style comment

### ISSUE THREAD

**Issue by dain** [prestodb/presto#1865]
This query:

```
presto:default> select 4 + 5
             -> -- + 6
             -> + 7;
```

folds to:

```
presto:default> select 4 + 5 -- + 6
+ 7;
```

which can't be edited.  Instead we should fold it to:

```
presto:default> select 4 + 5 /* + 6 */ + 7;
```

**Comment by vaughn1010111** [comment]
After reading through various vendor docs on comment handling then testing out several scenarios in the presto CLI I think the original proposal from @dain  will work. 

This is because presto (and other vendors) appear to completely ignore all characters inside the comment sequence. This means there is no support for nested comments but rather starting new comment sequences (i.e. "/*" or "--") while inside a comment is not handled specially but rather these characters are just treated as part of the comment.  

For example [IBM docs state it explicitly] (http://www.ibm.com/support/knowledgecenter/SSGU8G_11.70.0/com.ibm.sqls.doc/ids_sqs_0209.htm) if you search for "nested".

In ad-hoc tests of the CLI all of the following statements produce the same results:

select 1;

select /* -- */ 1;

select -- /*
1;

select /* /* */ 1;

I'm working on a simple commit to implement the original proposal.

**Comment by dain** [comment]
What about `SELECT 1 -- */, 2`?  That would turn into `SELECT 1 /* -- */,2 */` which, I think, would be an error?

**Comment by vaughn1010111** [comment]
Good catch! Thinking about this again, I could either escape/remove the closing C-style comment or I could simply drop double hyphen comment sequences from the "flattened" statement. I'll go ahead and drop double hyphen comments as @electrum suggested.
