### ISSUE TITLE
[Improvement] Please provide ARM64 docker image

### ISSUE THREAD

**Issue by HuangFru** [prestodb/presto#18750]
![image](https://user-images.githubusercontent.com/68625618/204980024-3c7ade64-5cc7-4def-b33c-52a925adf560.png)
I found your Docker images don't provide arm64 images. 
This is very unfriendly to mac with m-series chips which is the ARM architecture.
Can you please provide both two architecture images on the docker hub?

Suggestion:
You could push the image with 'buildx' tool in Docker. The Command is like this:
```
docker buildx build -f ${DOCKERFILE_NAME} --platform linux/arm64,linux/amd64 -t xxx/xxx ${PATH} --push 
```
I would really appreciate it if you could push arm64 images of the last few versions in DockerHub

**Comment by arestifo** [comment]
Any updates on this? We're in the same situation as @HuangFru and would love to use a native Docker image.

**Comment by MasterOdin** [comment]
For more recent releases, it looks like each image has three different artifacts that get published:
<img width="1244" alt="Screenshot 2023-11-17 at 11 37 55 AM" src="https://github.com/prestodb/presto/assets/1845314/e21031df-6d32-4ae7-814f-d834495f284c">

* `${version}`
* `${version}-arm64`
* `${version}-amd64`

While it's nice to see that there are `arm64` builds, because they're a separate image, it's not usable for us via a single docker-compose that's run on a mix of amd64 and arm64 machines. Ideally we'd see the same image be uploaded for multiple different architectures, like Trino does it:

<img width="1240" alt="Screenshot 2023-11-17 at 11 43 20 AM" src="https://github.com/prestodb/presto/assets/1845314/22b181d9-7acd-4f1b-9750-923380686b8a">

It looks like @wanglinsong is manually uploading these, vs via some automated process. Doing a multi-arch build for a single image is as easy as using the [buildkit](https://docs.docker.com/build/buildkit/) runner via `buildx` command. See https://docs.docker.com/build/guide/multi-platform/ for info on the right flags. Happy to submit a PR, though not sure exactly what the current process is for this and best place to modify.

**Comment by MasterOdin** [comment]
As part of setting up a [new presto sandbox image](https://github.com/popsql/prestodb-sandbox) with the loss of ahanaio/prestodb-sandbox, this can be used as an example of using GH actions to build an image for both `linux/amd64` and `linux/arm64`, publishing under a single tag. This goes to GHCR, but could be modified easily enough to point at docker hub:

https://github.com/popsql/prestodb-sandbox/blob/main/.github/workflows/build.yml

**Comment by tdcmeehan** [comment]
#21547 now provides a multi-arch docker image which includes ARM support.
