### ISSUE TITLE
The current native docker image build approach does not support CI properly

### ISSUE THREAD

**Issue by wanglinsong** [prestodb/presto#19066]
Here is the current Dockerfile: https://github.com/prestodb/presto/blob/master/presto-native-execution/scripts/release-centos-dockerfile/Dockerfile

There are 2 major issues from CI's perspective,
1. git clone of Presto repo inside docker image
   For a PR, the CI process usually merges the base branch (say master) into the feature branch, before launching build/test stages. The Dockerfile is already part of source code repository, we should reuse the already cloned repository.

2. development environment setup inside the same Dockerfile to build the Prestissimo/Velox code.
   Usually the development environment is stable, with very infrequent update. The better way is to pre-build this environment into a docker image, like what Velox development team has been doing -see this prestocpp/prestocpp-avx-centos:kpai-20221018.

Based on the above reasoning, I propose we remove git clone from the Dockerfile and also break it into 2 Dockerfiles, one for development environment, and another to build Prestissimo/Velox source code.

**Comment by wanglinsong** [comment]
@Mionsz @majetideepak FYI

**Comment by Mionsz** [comment]
You are right in reasoning about the issues from CI perspective - but at the same time it depends what you want to achieve. My basic assumptions and the end goal of this approach was to create Dockerfile for fully automated image creation, without the need of third party basic images etc. This way any user can build the image with one command and start testing it with another.

From CI perspective - like in Velox example - when there are no major dependencies you can use such approach. Here you would probably want to use `Velox base image` and change it (rebuild) only when Velox hash is updated in presto-native-execution.

For the repository part you are fully correct - I even have not think about this - but it is the best approach. Instead of cloning inside you can just for example set the docker build context to `pwd` or `.`:

```bash
docker build -f $(pwd)/presto-native-execution/scripts/release-centos-dockerfile/Dockerfile $(pwd)
```

```Dockerfile
ARG BASE_IMAGE=quay.io/centos/centos:stream8
FROM ${BASE_IMAGE} AS build-stage

ADD ./* /opt/presto/_repo/
```

**Comment by majetideepak** [comment]
@Mionsz thanks for your feedback.  Let's remove the git clone part.
We want to be able to use this script in CI/release process and avoid duplication.
Should we modify this script to take configuration parameters so that we can control the build-all vs build-dependencies, build-prestissimo portions? I am not an expert in this space, but my thinking is to control this via environmental variables.

**Comment by Mionsz** [comment]
@majetideepak Not sure but seems to that that this should work: https://github.com/prestodb/presto/pull/19068
:-p

**Comment by Mionsz** [comment]
This one is connected - we will be slowly pushing changes in direction that would allow more platforms for Velox and Prestissimo to be optimized for. https://github.com/prestodb/presto/pull/19064

**Comment by Mionsz** [comment]
@majetideepak @wanglinsong  Close this issue and let us move with all talks here https://github.com/prestodb/presto/issues/19211

**Comment by elharo** [comment]
closed in favor of https://github.com/prestodb/presto/issues/19211
