### ISSUE TITLE
MAP_SUBSET(MAP(), ARRAY['abc']) runs forever without failure

### ISSUE THREAD

**Issue by kidchemical** [prestodb/presto#19222]
As the title suggest, we are seeing queries run without failure when an _empty_ map is passed as an input to the MAP_SUBSET(a,b) function.

Example:
`MAP_SUBSET(MAP(), ARRAY['abc'])`

The current workaround is to COALESCE a dummy map which contains at least one element so that the function is able to return no match. 

Thanks for looking into this!

**Comment by kaikalur** [comment]
`Caused by: com.fasterxml.jackson.databind.JsonMappingException: Maps must be represented with SingleMapBlock (through reference chain: com.facebook.presto.sql.planner.PlanFragment["root"]->com.facebook.presto.sql.planner.plan.OutputNode["source"]->com.facebook.presto.spi.plan.ProjectNode["assignments"]->com.facebook.presto.spi.plan.Assignments["assign`ments"]->java.util.Collections$UnmodifiableMap["map_subset"]->com.facebook.presto.spi.relation.ConstantExpression["valueBlock"])
