### ISSUE TITLE
[native] Option to enable or disable PARQUET e2e tests for native execution

### ISSUE THREAD

**Issue by amitkdutta** [prestodb/presto#20374]
We have a good way to [include/exclude PARQUET](https://github.com/prestodb/presto/blob/master/presto-native-execution/CMakeLists.txt#L51) support during compile time in native execution. It will be great to have a similar option in e2e tests maven build as well, so that we can enable or disable them. Currently the tests are ran by default, although build time include is optional. Following same as build will help to disable/enable parquet tests with more granularity.

CC: @majetideepak @xiaoxmeng @aditi-pandit @mbasmanova @mshang816

**Comment by mbasmanova** [comment]
@majetideepak Deepak, is this something you could help with?

**Comment by majetideepak** [comment]
@amitkdutta I see two needs here.
The first is the ability to conditionally execute tests.
We can achieve this via the `void skipTestUnless(boolean requirement)`  defined here https://github.com/prestodb/presto/blob/master/presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestQueryFramework.java#L483

Now the second need is to set `requirement = false` when test `storageFormat` is `PARQUET` 
and Prestissimo does not support `PARQUET`.
There is no easy fix here since CMake, and Maven are two different build systems. This is similar to
manually setting the `PRESTO_SERVER_PATH` value to prestissimo binary.

My proposal, for now, is to add another argument `PRESTO_PARQUET_ENABLED` similar to `PRESTO_SERVER_PATH`.
We can use this variable to define the `requirement` based on the test `storageFormat = PARQUET`

Down the line, we can probably make CMake  generate a Maven config with these variables and pass it to the testing framework.

**Comment by majetideepak** [comment]
@amitkdutta I do not know your maven test environment for Prestissimo. Will the above proposal work for you?

**Comment by amitkdutta** [comment]
@majetideepak Thanks for the comments. I totally agree with you, its not reasonable to use same macro for CMAKE and Maven. I think `PRESTO_PARQUET_ENABLED` is a good idea for now. Today we run

 `mvn test -pl 'presto-native-execution'  -DPRESTO_SERVER=${{PRESTO_SERVER_BIN}}  ... `
 
 If we can pass `PRESTO_PARQUET_ENABLED=False` that will be great. CC: @mshang816

**Comment by mshang816** [comment]
What about we set a parquet group at class or method level then have two profiles: one running all test while the other running all tests excluding parquet tests  ? Then we can do:
`mvn test -p all-tests`
or
`mvn test -p all-tests-x-parquet `
?

**Comment by mshang816** [comment]
> What about we set a parquet group at class or method level then have two profiles: one running all test while the other running all tests excluding parquet tests ? Then we can do: `mvn test -p all-tests` or `mvn test -p all-tests-x-parquet `

this trick probably won't work as the abstract class is shared among many sub classes.
