### ISSUE TITLE
Test TestHivePushdownDistributedQueries testRunawayRegexAnalyzerTimeout fails with a timeout

### ISSUE THREAD

**Issue by swapsmagic** [prestodb/presto#20411]
https://github.com/prestodb/presto/actions/runs/5685313042/job/15409924223?pr=20409

Error:  Failures: 
Error:    TestHivePushdownDistributedQueries.testRunawayRegexAnalyzerTimeout » Test 
The exception was thrown with the wrong message: expected "Regexp matching interrupted" but got "The query optimizer exceeded the timeout of 1.00s."

**Comment by ClarenceThreepwood** [comment]
This is a straightforward race condition. The test is supposed to initiate an indefinite regular expression matching which then gets interrupted and is expected to produce the error "Regexp matching interrupted". 
Occasionally, since the regular expression matching has not initiated yet when the timeout/interruption happens, the other error message pops up.

Two possible solutions - increase timeout to minimize chances of this error happening, or tolerate both error states
