### ISSUE TITLE
[Native] Add E2E test for poisson_cdf()

### ISSUE THREAD

**Issue by yzhang1991** [prestodb/presto#20591]
poisson_cdf() was added in https://github.com/facebookincubator/velox/pull/4862

**Comment by Ann-Rose** [comment]
While implementing the E2E test for poisson_cdf, I am hitting an issue:

The function signature registered for poisson_cdf is (double, bigint) and when I tried to run the query
```
"select poisson_cdf(totalprice, orderkey) from orders;"
```
I am hitting this error:
```
Query 20230818_063024_00058_zjcpb failed: line 1:8: Unexpected parameters (double, bigint) for function poisson_cdf. Expected: poisson_cdf(double, integer)
```
where the table describe is :

```
presto:tpch> desc orders;
    Column     |    Type     | Extra | Comment
---------------+-------------+-------+---------
 orderkey      | bigint      |       |
 custkey       | bigint      |       |
 orderstatus   | varchar(1)  |       |
 totalprice    | double      |       |
 orderdate     | varchar     |       |
 orderpriority | varchar(15) |       |
 clerk         | varchar(15) |       |
 shippriority  | integer     |       |
 comment       | varchar(79) |       |
(9 rows)
```

**Comment by Ann-Rose** [comment]
Looks like it was expecting function signature to be (double, integer) but the function was registered as (double, bigint). 
The same issue exists in binomial_cdf. I have added the fix in the PR https://github.com/facebookincubator/velox/pull/6180. But I am hitting errors in linux-pr-fuzzer-run that says backward compatibility is being broken due to function signature changes.

**Comment by Ann-Rose** [comment]
As per the instruction from @aditi-pandit, I am creating 2 PRs for the same. One to add the new function signatures (https://github.com/facebookincubator/velox/pull/6180) and the other to remove the existing ones.
