### ISSUE TITLE
Allow clients to receive query results in PrestoPage format

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#20886]
Presto query results today are returned in JSON format: https://prestodb.io/docs/current/develop/client-protocol.html

This is slow and difficult to parse for some clients (e.g. Aggregation Fuzzer in Velox: https://github.com/facebookincubator/velox/issues/6595).

It would be helpful to introduce a new HTTP Header that a client can specify to receive results in PrestoPage format: https://prestodb.io/docs/current/develop/serialized-page.html

The results can still be JSON, but the data would be a string that contains base64-encoded PrestoPage(s).

CC: @aditi-pandit @tdcmeehan @majetideepak

**Comment by tdcmeehan** [comment]
If the primary motivation is better performance, I believe @sachdevs attempted to do this a few years ago and didn't find as significant performance improvements as we expected in the client's ability to fetch lots of data.  I think this is because typically the bottleneck is network and we go through a single coordinator process, fetching page one at a time. I would recommend an approach that allows us to separate metadata from data altogether, and would allow the client to fetch data from workers with multiple threads (e.g. the [v2 protocol](https://github.com/prestodb/presto/wiki/presto-v2-client-protocol)).

If the primary motivation is ease of parsing in a C++ library, have you considered the following:

1) I believe Meta has a C++ client which already parses the JSON data without issue (and with sufficient performance).  Could this be open sourced, or could a modified version be put in open source?
2) Could the output be written to a local file?  In this mode, we don't need any non-backward compatible changes in the client API, you would simply add a session param to save the data locally in the coordinator, or try to persist to a local file system (as I believe Hive can be configured to do), and not attempt to parse the JSON data blob.

**Comment by mbasmanova** [comment]
Relevant change: "Make query result HTTP response compression configurable" - https://github.com/prestodb/presto/pull/15393

**Comment by mbasmanova** [comment]
@tdcmeehan Tim, thank you for your comments.

There are two motivations: (1) performance in fuzzer / test, i.e. when running single-node Presto cluster on localhost; (2) ease of parsing in the client (Velox).

JSON serializing and parsing is quite expensive and will slow down tests considerably, hence, there is a desire to avoid JSON serde altogether. See #15393 for a somewhat related perf optimization for localhost.

Therefore, I still think it would be helpful to allow the client to request results in PrestoPage format and have the server produce these without serializing into JSON. What do you think?

**Comment by mbasmanova** [comment]
CC: @agrawaldevesh

**Comment by tdcmeehan** [comment]
It seems like that PR allows greater flexibility in avoiding server-specified HTTP payload compression, which doesn't entail a change in the client API.  Here, we are specifying an alternative format in the client API, and broadening the API footprint to include the particulars of the Presto page format.

I am pessimistic any client will actually be modified to use this upgraded client protocol, because it seems like it will be a lot of work: one needs to understand how to interpret the various blocks (perhaps even encoded blocks?), and it needs to be done for each client (in each language).

Given the amount of work involved, I wonder if it's worthwhile to investigate the usage of an open standard binary format (e.g. Arrow), that way one can leverage libraries that can interpret this format?  While this involves more upfront work for the purposes of Fuzzer testing in Velox, it may involve less overall work, as one could leverage libraries which already interpret the open format.

In lieu of that major change, I am wondering if there are easier ways to accomplish fast fuzzer tests in Velox, hence my suggestion on leveraging an off the critical path solution (e.g. simply persist the binary data to a file).  While it would still need to be read, nothing would need to be parsed, and I don't think it's hard or slow to incrementally parse JSON (e.g. simply read up to the `data` field and ignore its contents).

**Comment by mbasmanova** [comment]
> Here, we are specifying an alternative format in the client API, and broadening the API footprint to include the particulars of the Presto page format.

This is correct.

> I am pessimistic any client will actually be modified to use this upgraded client protocol, because it seems like it will be a lot of work:

Existing clients do not need any change unless they want to take advantage of the new logic. As long as they do not explicitly request new data format by specifying new header, they will continue seeing same results.

**Comment by mbasmanova** [comment]
> hence my suggestion on leveraging an off the critical path solution (e.g. simply persist the binary data to a file). 

This solution still requires Java server to serialize data into JSON, which is slow.

**Comment by tdcmeehan** [comment]
As an alternative, what about rewriting the queries as CTAS into Hive local temporary files so that the coordinator only polls and doesn't fetch any data?

**Comment by mbasmanova** [comment]
> As an alternative, what about rewriting the queries as CTAS into Hive local temporary files so that the coordinator only polls and doesn't fetch any data?

This is an interesting idea. The challenge is then to figure out how to read this data from Velox. Velox doesn't have integration with Hive Metastore, hence, wouldn't know how to a table written by Presto.

**Comment by mbasmanova** [comment]
@tdcmeehan Tim, also note that writing data using DWRF or Parquet format is pretty slow.

**Comment by tdcmeehan** [comment]
One suggestion: use a `FileHiveMetastore`.  Once the write is complete, use the Metastore to query the partition locations, and list files in that location.  While this will be slower than using a native format all things being equal, it might be worth experimenting if this is faster in spite of that (as the coordinator is not optimized for throughput).

How much data is going to be put through the fuzzer?  Also, I presume the coordinator will be a daemon that is reused across many tests?

**Comment by mbasmanova** [comment]
> One suggestion: use a FileHiveMetastore. Once the write is complete, use the Metastore to query the partition locations, and list files in that location.

All this exists only in Java. There is no such code in C++ / Velox.

**Comment by mbasmanova** [comment]
Implemented in https://github.com/prestodb/presto/pull/20932
