### ISSUE TITLE
[Native] Adding functions in Prestissimo

### ISSUE THREAD

**Issue by majetideepak** [prestodb/presto#21715]
All the Presto native function implementations are currently in Velox. These functions have unit tests as well and 
very useful Fuzzer tests.
In the Prestissimo WG meeting [last week](https://docs.google.com/document/d/1oL0KVf_02_P_kIfNs2oZVwB60_PqHBNou6MzRAS1fbM/edit#heading=h.o85nkj3afpgg), there was a discussion on how to improve the C++ developer community in the Presto Project.
One thought was to allow trivial functions to be written in Prestissimo instead of Velox. We wanted to start with
the "fail" function first. https://github.com/prestodb/presto/issues/20742
But this does mean some functions continue to live in Velox while others live in Prestissimo. We will also need to add
Fuzzer testing in Prestissimo.
The scope of this issue is to discuss this further and conclude.

**Comment by majetideepak** [comment]
CC: @tdcmeehan, @aditi-pandit. @mbasmanova, @amitkdutta

**Comment by mbasmanova** [comment]
> In the Prestissimo WG meeting [last week](https://docs.google.com/document/d/1oL0KVf_02_P_kIfNs2oZVwB60_PqHBNou6MzRAS1fbM/edit#heading=h.o85nkj3afpgg), there was a discussion on how to improve the C++ developer community in the Presto Project.
> One thought was to allow trivial functions to be written in Prestissimo instead of Velox. 

Splitting the set of functions into 2 repos seems a poor solution for improving "the C++ developer community in the Presto Project". 

Where can I learn more about the problem we are trying to solve and what solutions have been considered / tried already?

CC: @xiaoxmeng @pedroerp

**Comment by mbasmanova** [comment]
We (Meta) have an overarching goal of consolidating streaming, adhoc, batch and ML workloads on single dialect (PrestoSQL) and single base set of functions (Presto functions). This requires all functions to be available outside of PrestoDB repo.

**Comment by tdcmeehan** [comment]
@mbasmanova I've added a link to the recording in the working group meeting notes.  Perhaps you can make it to the next working group meeting to help us brainstorm?  The way I see it, the goal you mention is not mutually exclusive.

**Comment by mbasmanova** [comment]
> you can make it to the next working group meeting to help us brainstorm? 

Sounds good. Would it be possible to publish agenda a few days in advance to help folks decide whether to attend or not. There are way too many meetings to attend all of them.

**Comment by tdcmeehan** [comment]
@mbasmanova I've updated [the agenda doc](https://docs.google.com/document/d/1oL0KVf_02_P_kIfNs2oZVwB60_PqHBNou6MzRAS1fbM/edit), please bookmark it as that always has the upcoming agenda.

**Comment by pedroerp** [comment]
While I understand the concern about fostering a C++ community in Presto, fragmenting function definition sort of conflicts with Velox's direction of providing a full-PrestoSQL compatible engine. 

Like @mbasmanova pointed out, the end goal is that different engines will provide the exact same semantic to users, and hence require the exact same functions to be available. If functions are scattered across Velox and Presto/Prestissimo, it breaks this model. I suspect that if the Presto community decides to move this way, soon enough we will have to move/copy these functions back to Velox to make them available to non-Presto users, and this will cause more a lot more hassle (and tech debt) than benefit. 

Note that this is the exact same model used by Gluten today; all Spark functions are available in Velox.

**Comment by tdcmeehan** [comment]
Thanks for the discussion.  The rationale for adding the fail function to Prestissimo is the following:

1) Fail is not a public function.  It was added so that certain optimizations can be made in Presto safely: for example, when optimizing correlated subqueries, we can use the fail function to check that a correlated subquery returns just a single row.  Likewise, if we include a division by 0 in an expression nested by an WHEN condition, we can replace it will fail during expression optimization—this way we rewrite it once, and preserve behavior after the rewrite.
2) Because it is a hidden function, its usage remains unsupported: it will not be returned in `SHOW FUNCTIONS`, and it remains undocumented.  As such, although in this case it doesn’t seem conceivable, we can could feel free to change its behavior at any time.

A nice objective in Presto’s transition to a mixed Java/C++ project is simply more C++ code.  So this function was identified as a potential candidate to add purely in Prestissimo.

Of course, adding the fail function in no ways move the needle on this goal: one simply needs to start somewhere.  There’s also many paths to get to that outcome, of which the fail function could be just a small part.

I understand the objectives on wanting to ensure a consistent set of functions to users, on the basis that our vision is a plurality of engines having consistent SQL semantics, including function behavior.  Of course, such functions should exist in one place.  However, I think it’s important to decide on what is the “canon”:

Is the canon all functions, even hidden optimizer-only functions?  If it is, it would seem that you would need a Presto optimizer to generate usages of this function for something that will not be evaluated in a Presto runtime, and as far I’m aware nothing like this exists.  I understand the convenience of putting fail in Velox, but is it necessary to achieve our goal of one consistent canon of Presto functions?

One other point that I think is worthwhile to note that Presto has a function SPI.  Newly added functions are not namespaced separately from whatever is considered to be built-in.  As such, it’s not possible to provide the exact same functions between Presto and Velox—Presto has a potentially unbounded list of possible functions that could be loaded at startup.  While indexing on built-ins is a useful milestone, I think we’re looking at a future where complete parity may never be achieved.  As such, rather than looking at all functions as the target, it might make sense to define what functions we will target—new functions are continually being added to Presto, so we already have the moving target problem that’s mentioned.  

One last point: I think the difference between Presto and Gluten is that, as far as I’m aware :) , Gluten will not replace Sparks’ eval, just supplement.  Without the Spark community agreeing to take in Velox, Gluten seems to always play catch up with defaults in Spark.  In Presto, there is a long-standing firm commitment to move to C++.  This means at some point, the source of truth should be in C++—not just adding a duplicate in C++ whenever a Java function is added, what is meant is actually deleting the Java functions and using just C++.  This means at some point C++ will define the behavior of Presto, instead of C++ mimicking the behavior of Java.  I just wanted to point this out because it’s an important difference and I think it’s something we need to reflect on as Velox matures and we reorient the Presto community to be more C++ oriented.

**Comment by pedroerp** [comment]
To be clear, I agree that extensions that are Presto-specific and not part of the public API which implements PrestoSQL could live in Presto. If `fail()` is not exposed to users and only generated internally by Presto's optimizer/planner (i.e. if it's a Presto implementation detail), then it should be part of Presto, but it wouldn't really help achieve the proposed effect of "improve the C++ developer community in the Presto Project.".

Are there other examples of such functions other than "fail()"?

**Comment by mbasmanova** [comment]
Note that splitting the set of functions would prevent testing all possible combinations of expressions using Velox Fuzzer unless someone spends time and effort to setup and maintain similar testing for the PrestoDB repo. Also, note it makes it harder to reproduce the issues as recent PR from @majetideepak demonstrates where he ended up copying function implementation into Velox Test code.

**Comment by pedroerp** [comment]
> (...) Presto has a function SPI. Newly added functions are not namespaced separately from whatever is considered to be built-in. As such, it’s not possible to provide the exact same functions between Presto and Velox—Presto has a potentially unbounded list of possible functions that could be loaded at startup.

One way to see the problem is that Presto provides a set of builtin function that are well tested, curated, documented and compose the PrestoSQL dialect. We want to be able to leverage these across engines. Presto users can always extend the engine by adding another layer of functions of top of that; these are available just like regular functions, but do not comprise the PrestoSQL dialect. They are customer specific extensions.

**Comment by xiaoxmeng** [comment]
Velox has already built thorough testing coverage for Presto functions. If we move or add new functions in Prestissimo code base, we will have to duplicate the efforts that we made in Velox. It is also bit hard to maintain Presto functions in two code bases in practice. I don't see much benefit to maintain some of functions in Prestissimo code base. Also having the functions in Velox code base can help other query engines to use and ease maintenance.

**Comment by aditi-pandit** [comment]
We concluded that we will add new functions to Velox in the near term until we see examples that are just not a good fit for it.
