### ISSUE TITLE
[Doc] Support for doc translations.

### ISSUE THREAD

**Issue by Waterkin** [prestodb/presto#21732]
## Expected Behavior or Use Case

Multilingual documentation.

## Possible Implementation

Add a sphinx plugin to support google translation.

## Context

Support for multi-languages.

**Comment by steveburnett** [comment]
Thanks for the suggestion! 

* Discussed this with @tdcmeehan and we don't have the resources to implement and maintain multilingual documentation at this time. 

* Based on Possible Implementation suggestion, I also looked and did not find a sphinx plugin to support google translation. 

* I did find [Translating documentation using Sphinx](https://docs.weblate.org/en/latest/devel/sphinx.html) which links to the Sphinx docs for [Internationalization](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html). 

Because of the resource constraint and lack of specifics how to move forward, I'm closing this issue. 

If you have more suggestions how to implement this feature request, please reopen this issue, or a new issue, as you feel appropriate.
