### ISSUE TITLE
Add documentation for history based optimizer

### ISSUE THREAD

**Issue by tdcmeehan** [prestodb/presto#21830]
Many prominent improvements are being added to the history based optimizer.  We already have documentation for the [Redis HBO provider](https://prestodb.io/docs/current/plugin/redis-hbo-provider.html), yet lack documentation for how HBO works and how to enable it.  We should add this documentation to encourage its use.

It seems like this should be added to [the query optimizer section](https://prestodb.io/docs/current/optimizer.html).

CC: @pranjalssh @mlyublena @feilong-liu @jaystarshot

**Comment by mbasmanova** [comment]
A list of optimizations:

* DetermineJoinDistributionType
* PushPartialAggregationThroughExchange
* DetermineSemiJoinDistributionType
* ReorderJoins
* ScaledWriterRule
* RandomizeNullKeyInOuterJoin

CC: @mlyublena

**Comment by mlyublena** [comment]
@feilong-liu is working on adding documentation.

**Comment by feilong-liu** [comment]
Just drafted a doc on HBO, since it's mainly for Presto user, hence I skip the technical details, but focus on the brief description of the supported optimizers and associated session properties to turn them on. https://docs.google.com/document/d/1Y6ylfV4yfbJ5X5lQwG5gTiC5nSVyV0QoyP0VLyJfLME/edit?usp=sharing

@steveburnett Hi Steve, I know that you are working on Presto documentation, wonder if you could help to polish the draft before adding it to the documentation (and share a email account so that I can assign edit access to you or copy it into another doc whichever works better for you). Thanks!

**Comment by steveburnett** [comment]
> Just drafted a doc on HBO, since it's mainly for Presto user, hence I skip the technical details, but focus on the brief description of the supported optimizers and associated session properties to turn them on. https://docs.google.com/document/d/1Y6ylfV4yfbJ5X5lQwG5gTiC5nSVyV0QoyP0VLyJfLME/edit?usp=sharing
> 
> @steveburnett Hi Steve, I know that you are working on Presto documentation, wonder if you could help to polish the draft before adding it to the documentation (and share a email account so that I can assign edit access to you or copy it into another doc whichever works better for you). Thanks!

@feilong-liu I would be happy to help! I see that you've already received some good feedback on the draft in your link. You can use the email address attached to my GitHub profile if you like.

**Comment by feilong-liu** [comment]
> > Just drafted a doc on HBO, since it's mainly for Presto user, hence I skip the technical details, but focus on the brief description of the supported optimizers and associated session properties to turn them on. https://docs.google.com/document/d/1Y6ylfV4yfbJ5X5lQwG5gTiC5nSVyV0QoyP0VLyJfLME/edit?usp=sharing
> > @steveburnett Hi Steve, I know that you are working on Presto documentation, wonder if you could help to polish the draft before adding it to the documentation (and share a email account so that I can assign edit access to you or copy it into another doc whichever works better for you). Thanks!
> 
> @feilong-liu I would be happy to help! I see that you've already received some good feedback on the draft in your link. You can use the email address attached to my GitHub profile if you like.

Hi @steveburnett, thanks for helping with it. I've addressed the comments and added you as editor of the doc.

**Comment by steveburnett** [comment]
> Hi @steveburnett, thanks for helping with it. I've addressed the comments and added you as editor of the doc.

Hi @feilong-liu! I'm sorry I took longer than I expected to get to this, but I just completed a light edit of the draft - light mostly because it's an excellent draft, especially after you've already addressed the other reviewers' technical recommendations. 
I suggested some minor rephrasings, and added some formatting of items as unordered lists to break up big paragraphs to help readability. When you use this draft in a PR for the Presto docs I'll likely focus on formatting of property names and similar concerns. Thanks for the draft, and for inviting me to contribute, I hope you find my suggestions helpful.
