### ISSUE TITLE
Row ID support

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22078]
Row ID is a binary key for a row that is globally unique across the warehouse. It identifies a specific row at a specific version of a partition’s data. A row_id will continue to locate the same row in the warehouse until there is a mutation to the underlying partition. 

## Expected Behavior or Use Case

Row IDs resolve to the same value across compute engines. In this way they can be used as a strong-equality comparison across compute engines.

## Possible Implementation

row_number:row_group_id:data_version:partition_id:tbl_id:table_guid.substring(0, 6):spec_version

Row IDs will be binary encoded. There is no delimiter in the actual row_id. It’s just binary compressed fixed width fields (except for the variable width row_group_id)

data_version:partition_id:tbl_id:table_guid.substring(0, 6):spec_version has the same value for all rows in a partition 

The XLDB reader libraries will supply  row_number:row_group_id as independent pieces  accessed alongside rows.

data_version:partition_id:tbl_id:table_guid.substring(0, 6):spec_version: This component will be exposed as a binary field in the Partition object. It currently is fixed width 26 bytes. 

In essence there are two pieces: one to locate the partition and one to locate the row within the partition. The partition ID is passed into the reader library from above while the reader supplies the row ID within the partition. The reader passes back the row ID alongside the other columns. 

## Context

A row_id would introduce an automatic skew mitigation, giving each row a unique key to be shuffled on.

**Comment by tdcmeehan** [comment]
In order for a row ID to be interpreted the same between engines, there must be a spec or shared library that defines how to derive a row ID given the table and file formats used to read the data.  Hence, I think a row ID might be considered something that is connector-specific: each data source will likely have different conventions on how to define a row ID.  Some data sources may have no clear explicit convention, and should not expose a row ID.  Only connectors whose sources have a row ID convention defined in a spec or shared library should expose it.

For those that do, it seems that we should use the constraints framework to convey uniqueness of the column, as this particular column is just a special case of general uniqueness constraint.  CC: @ClarenceThreepwood

**Comment by elharo** [comment]
There are some Meta-internal details I'm having to redact in this proposal, so my apologies if this isn't as clear as it should be. I do want this feature to be generally useful though, and certainly not to cause any problems for any other Presto users. Also, this is all still new so nothing is written in stone yet and changes are very much possible.

Roughly my understanding (and I do mean *my* understanding; this might not be in perfect agreement even with what other Meta-presto devs are thinking, and I might be flat out wrong about some of this) is that there are two parts to the binary ID; call them the table ID and the row ID, sort of like a last name and a first name.

The "table ID"  part identifies the "file" to look in to find the row. That could be be an actual file in a local or distributed file system, or maybe it's a group of files if separate columns are in separate files, or maybe it's some subsection of some much larger file. It completely depends on how the warehouse is set up and different warehouses will have different ways of doing this. Consequently this binary table ID will be passed into the page source from higher up the stack.

At the top the user executes a query like "SELECT name, $row_id from EMPLOYEES". Presto figures out the table ID part at the same time it's figuring out what files it needs to read to find the name in the EMPLOYEES table. Most likely this is just a binary string it retrieves from whatever system tells it where the tables are. Then it passes this binary string into the page source.

The page source figures out which rows and columns satisfy the query and returns those like it does now. Assuming one of those columns is $row_id, the page source will get the row ID and the row group ID for each row it returns, append the table ID part it already has, and return that entire binary string as the value of the $page_id column for each row.

I think you're correct that row IDs will be connector-specific. We should avoid locking in specific representations if we can avoid it. The tldr is an opaque, binary $row_id pseudo-column that can be used in queries and is persistent over time until the underlying partition is mutated.

I'm not sure I'm explaining this well, but I'll try to iterate on this description.

**Comment by kaikalur** [comment]
Actually I think the spec should be clear of the intent

* Rowid type is a first class volatile type so you can't materialize it
* a rowid for a given row is fixed for the life time of a quest
* each row will have a unique rowid for the entirety of the query

And it's an optional feature that may not be supported by all connectors. That should simplify things a lot.

**Comment by tdcmeehan** [comment]
Connectors can already add hidden columns and new types.  Why make it first class and core?

**Comment by mlyublena** [comment]
@kaikalur , the requirement "you can't materialize it" may contradict some of the optimizations that use materialization (for example the CTE work). We can of course limit these optimizations to stuff that will not use the rowid column, but I wonder if there is another way to allow that

**Comment by kaikalur** [comment]
> @kaikalur , the requirement "you can't materialize it" may contradict some of the optimizations that use materialization (for example the CTE work). We can of course limit these optimizations to stuff that will not use the rowid column, but I wonder if there is another way to allow that

IIUC, it's lot harder to have globall unique row_id (not impossible but maybe too constly). "CTE materialization" is still intermediate stage so it's just a implementaiton limitation.

**Comment by tdcmeehan** [comment]
> > Connectors can already add hidden columns and new types. Why make it first class and core?
> 
> So we can use it in the optimizer and other places freely. Also I'm not sure if we call them hidden columns. Maybe they are like current_user etc. Maybe we should introduce CURRENT_ROWID of RowId type.

1) How does the engine know if a connector supports it?  Does it check to see if the RowId is present in the results?  And then we add logic that checks for a specific type, the RowId, in optimizer rules?  Are we not concerned about lots of special case checks littering the code?
2) We already have constraints.  Why add logic to special-case check a specific column type, where we think we can infer uniqueness from it, but not generally make use of unique columns that may be supported by any column?  In other words, why restrict these optimizations to one column?  And why enforce that connectors must use this type to convey the row ID?  Wouldn't it be better to let connectors inform the engine of a row ID in whatever way is convenient to the connector, without pigeon holing into a binary RowID type?  And't wouldn't a solution that works for any column that has unique constraints be better than one that works for just a small subset?
3) I am concerned about overloading the Type with major new responsibilities without thinking through the broader approach.  Right now, the type specifies a domain of values for a given block value, lets use know if its orderable or comparable, and gives us utilities for writing and reading from blocks.  It does not infer properties of the whole column, like uniqueness.  And as far as I'm aware there isn't a SQL type that behaves in this manner, which is why the spec has constraints.  So we'll be adding code in the engine in lots of different places, telling the engine that here is a *special type*, where we can infer special things about every value in the column.  I think there needs to be a more generic and systematic way to infer constraints from the column, so that we're not special-casing just one column and just one type and introducing a lot of complexity.  I understand this approach may make the optimizer features easier to write initially, but I'm not convinced at all it will make the code easier to maintain in the long run.

I'd really like a detailed design that evaluates these trade-offs carefully.  Can we make a design doc and open up for feedback before proceeding?

**Comment by kaikalur** [comment]
> > > Connectors can already add hidden columns and new types. Why make it first class and core?
> > 
> > 
> > So we can use it in the optimizer and other places freely. Also I'm not sure if we call them hidden columns. Maybe they are like current_user etc. Maybe we should introduce CURRENT_ROWID of RowId type.
> 
> 1. How does the engine know if a connector supports it?  Does it check to see if the RowId is present in the results?  And then we add logic that checks for a specific type, the RowId, in optimizer rules?  Are we not concerned about lots of special case checks littering the code?
> 2. We already have constraints.  Why add logic to special-case check a specific column type, where we think we can infer uniqueness from it, but not generally make use of unique columns that may be supported by any column?  In other words, why restrict these optimizations to one column?  And why enforce that connectors must use this type to convey the row ID?  Wouldn't it be better to let connectors inform the engine of a row ID in whatever way is convenient to the connector, without pigeon holing into a binary RowID type?  And't wouldn't a solution that works for any column that has unique constraints be better than one that works for just a small subset?
> 3. I am concerned about overloading the Type with major new responsibilities without thinking through the broader approach.  Right now, the type specifies a domain of values for a given block value, lets use know if its orderable or comparable, and gives us utilities for writing and reading from blocks.  It does not infer properties of the whole column, like uniqueness.  And as far as I'm aware there isn't a SQL type that behaves in this manner, which is why the spec has constraints.  So we'll be adding code in the engine in lots of different places, telling the engine that here is a _special type_, where we can infer special things about every value in the column.  I think there needs to be a more generic and systematic way to infer constraints from the column, so that we're not special-casing just one column and just one type and introducing a lot of complexity.  I understand this approach may make the optimizer features easier to write initially, but I'm not convinced at all it will make the code easier to maintain in the long run.
> 
> I'd really like a detailed design that evaluates these trade-offs carefully. Can we make a design doc and open up for feedback before proceeding?

I will reply im detail later but spec does have user defined types and we have precedent for that in presto already like Tdigest etc

As for special cares I believe we have many properties that are connector specific and may or may not be supported?

**Comment by tdcmeehan** [comment]
While we have built-in types like T-Digest, these can be generated by any connector that supports real or double.  It doesn't infer anything about the capabilities of the connector.

Yes, connectors don't need to implement the entire Connector interface.  There's lots of opt-in features.  Usually, they throw when you attempt to use them.  The core of what I'm asking is: if we're going to introduce uniqueness optimizations to the engine, shouldn't we make sure this can apply to any column rather than just RowID (especially since this is being worked on right now)?
