### ISSUE TITLE
[docs] wrong docker pull command in Deploy Presto From a Docker Image

### ISSUE THREAD

**Issue by nielspardon** [prestodb/presto#22074]
[Deploy Presto From a Docker Image](https://prestodb.io/docs/0.285.1/installation/deploy-docker.html#installation-deploy-docker--page-root) currently says to run:

```
docker pull prestodb/latest
```

which should be:

```
docker pull prestodb/presto:latest
```

**Comment by steveburnett** [comment]
Thanks! I will fix this.

**Comment by steveburnett** [comment]
Checked and this has already been fixed in [PR 21518](https://github.com/prestodb/presto/pull/21518), and has been merged into master, as visible in 

https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/installation/deploy-docker.rst

According to [PR 21906](https://github.com/prestodb/presto/pull/21906/), this merged documentation fix will be part of the documentation update in the upcoming 0.286 release. 

Closing this issue.
