### ISSUE TITLE
TPC-DS SF-1K Q72 extremely slow in Iceberg 

### ISSUE THREAD

**Issue by yzhang1991** [prestodb/presto#22148]
## On Java clusters
[Java Run Comparision Dashboard, Iceberg vs. Hive](https://grafana.ibm.prestodb.dev/d/a9a2c8a6-b7f5-4d67-a67c-ed363949b83e/run-comparison?from=now-90d&to=now&var-base_run=%5BREF%5D%20c0w1_java_oss_power_ds_sf1k_ice_240310-151324&var-target_run=%5BREF%5D%20c0w1_java_oss_power_ds_sf1k_240310-151324&var-selected_run=13&var-stage_id=ds_sf1k_ice&var-query_file=queries%2Fquery_72.sql&var-query_idx=0&orgId=1)
![image](https://github.com/prestodb/presto/assets/6643318/1575572a-0a74-4eb5-97c5-edb9056b2388)

It took 1.04 hours to finish on the Iceberg schema and only 2 mins on the Hive schema.
[Query Comparison Dashboard, Iceberg vs. Hive](https://grafana.ibm.prestodb.dev/d/cc6a4ccf-2fc7-4220-8f4e-397b03061acf/query-detail-comparisons?orgId=1&from=now-90d&from=1710090530458&to=now&to=1710094257488&var-query1=20240310_170850_00084_p63fj&var-query2=20240310_164150_00083_w2q4s)

## On Prestissimo clusters
[Prestissimo Run Comparision Dashboard, Iceberg vs. Hive](https://grafana.ibm.prestodb.dev/d/a9a2c8a6-b7f5-4d67-a67c-ed363949b83e/Run%20Comparison?from=now-90d&to=now&var-base_run=%5BP1%5D%20c0w1_native_oss_power_ds_sf1k_ice_240310-151323&var-target_run=%5BREF%5D%20c0w1_native_oss_power_ds_sf1k_240310-225117&var-selected_run=11&var-stage_id=ds_sf1k_ice&var-query_file=queries/query_72.sql&var-query_idx=0)
![image](https://github.com/prestodb/presto/assets/6643318/39b39dbf-b663-4e11-abc8-9b416d34ea76)
We killed the query on Prestissimo Iceberg schema after 6 hours. On Prestissimo Hive it only took 1.31 mins.
[Query Comparison Dashboard, Iceberg vs. Hive](https://grafana.ibm.prestodb.dev/d/cc6a4ccf-2fc7-4220-8f4e-397b03061acf/query-detail-comparisons?orgId=1&from=now-90d&from=1710086930375&to=now&to=1710108874198&var-query1=20240310_160850_00080_k4zpw&var-query2=20240310_232959_00287_nbzb8)

**Comment by hantangwangd** [comment]
In my experiments, q72's running time would be greatly shorten after executing `ANALYZE <tableName>` for it's involving tables, thanks for the PR [#](https://github.com/prestodb/presto/pull/20993) risen by @ZacBlanco. For the NDV value is crucial when selecting the best join tree.

**Comment by yingsu00** [comment]
The Iceberg plan is very different than the Hive one. The Hive one was a bushy tree, while the Iceberg one is a left deep tree. This may result in the way the stats is used is different?
Hive Plan:
<img width="866" alt="Screenshot 2024-03-11 at 15 37 45" src="https://github.com/prestodb/presto/assets/33299678/ed26137b-82fd-42df-89ac-0e9ece04f766">
Iceberg Plan
<img width="1109" alt="Screenshot 2024-03-11 at 15 38 04" src="https://github.com/prestodb/presto/assets/33299678/ea92c506-cb98-4320-9e96-d87c7973ee4e">

@yzhang1991 Are you sure the Iceberg tables stats were collected?

**Comment by yzhang1991** [comment]
Yes, but I found the stats we got from analyzing the hive tables and the iceberg tables are different. See the two screenshots below showing the stats for the same table in the same scale factor but one in the hive catalog one in the iceberg catalog:
![image](https://github.com/prestodb/presto/assets/6643318/4a910ec2-c00f-46d7-9aaa-5682422434d6)
![image](https://github.com/prestodb/presto/assets/6643318/b095ee6a-ba61-48c8-9498-0192ff691188)
In hive table stats, there is not any `NULL` value in the `distinct_values_count` column., some `NULL`s in the `data_size` column.
However, in the Iceberg table stats, the `distinct_values_count` column is completely NULL. But there is no NULL value in the `data_size` column.
@ZacBlanco I thought your NDV work would add the distinct value count, maybe I was confused?

**Comment by aaneja** [comment]
I think the issue here is with the setup - the iceberg connector employs a `iceberg.catalog.type` of `HIVE`.  

For this, the relevant [code path for statistics load](https://github.com/prestodb/presto/blob/08c49debf27a9668af0db15c163bfa74406bf0d2/presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergHiveMetadata.java#L483-L489), merges the stats from HMS and Iceberg using the `iceberg.hive_statistics_merge_strategy` session property (or `iceberg.hive-statistics-merge-strategy` feature config). The default for this is `NONE`

By changing this property to `USE_NULLS_FRACTION_AND_NDV` and then running ANALYZE, I can see that we do get non-zero NDV counts in show stats -

```
presto:tpcds_sf1000_parquet_iceberg> show stats for reason;
  column_name  | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value 
---------------+-----------+-----------------------+----------------+-----------+-----------+------------
 r_reason_sk   |     148.0 | NULL                  |            0.0 | NULL      | 1         | 65         
 r_reason_id   |     147.0 | NULL                  |            0.0 | NULL      | NULL      | NULL       
 r_reason_desc |     466.0 | NULL                  |            0.0 | NULL      | NULL      | NULL       
 NULL          | NULL      | NULL                  | NULL           |      65.0 | NULL      | NULL       
(4 rows)
presto:tpcds_sf1000_parquet_iceberg> set session iceberg.hive_statistics_merge_strategy='USE_NULLS_FRACTION_AND_NDV';
SET SESSION
presto:tpcds_sf1000_parquet_iceberg> analyze reason;
ANALYZE: 65 rows

Query 20240311_112336_00044_ivzjq, FINISHED, 3 nodes
Splits: 19 total, 19 done (100.00%)
[Latency: client-side: 0:02, server-side: 0:01] [65 rows, 2.36KB] [63 rows/s, 2.32KB/s]

presto:tpcds_sf1000_parquet_iceberg> show stats for reason;
  column_name  | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value 
---------------+-----------+-----------------------+----------------+-----------+-----------+------------
 r_reason_sk   |     148.0 |                  65.0 |            0.0 | NULL      | 1         | 65         
 r_reason_id   |     147.0 |                  65.0 |            0.0 | NULL      | NULL      | NULL       
 r_reason_desc |     466.0 |                  64.0 |            0.0 | NULL      | NULL      | NULL       
 NULL          | NULL      | NULL                  | NULL           |      65.0 | NULL      | NULL       
(4 rows)
```

We will need to do this (set flag, re-analyze) for all tables in the schema

**Comment by ZacBlanco** [comment]
Re: support for NDVs in Iceberg+Hive. By default the `ANALYZE` behavior will collect all of the hive-supported statistics and store them into the Hive metastore. This should include NDVs and null counts.

When reading the statistics from an Iceberg table that uses Hive, statistics can come from the table itself or from the Hive metastore. By default, we only use statistics from the Iceberg table when reading because values like min/max and null counts are supposed to be more accurate as the manifests should always accurately reflect the values. However, NDVs and null counts are not always necessarily the as accurate from the iceberg table, so we provide the option to override the stats coming from the iceberg table with stats from the HMS. To override the behavior when retrieving stats you can set the property connector session property `iceberg.hive_statistics_merge_strategy`.

You can set it to the following values:

1. `USE_NDV`: overwrites NDV stats from iceberg table with those from the HMS
2. `USE_NULLS_FRACTIONS`: overwrites nulls fraction stats from iceberg table with those from the HMS
3. `USE_NULLS_FRACTION_AND_NDV`: overwrites NDV and nulls fraction stats from iceberg table with those from the HMS.

Since the HMS should already have the stats from the analyze before, you shouldn't need to re-analyze the tables.

**Comment by ZacBlanco** [comment]
Adding on to this investigation. I confirmed that after analyzing on the Iceberg table and running `SET SESSION iceberg.hive_statistics_merge_strategy = 'USE_NDV'` that the query executes successfully in about ~45s and has a plan shape similar to the hive one @yingsu00 posted above.

<details><summary>Query Plan Image</summary>
<p>

Plan image from the coordinator UI to show plan shape is the same as hive
<img width="882" alt="image" src="https://github.com/prestodb/presto/assets/3464508/594f3452-8eed-4579-87a2-031c569d35a3">

</p>
</details> 

[Query JSON](https://github.com/prestodb/presto/files/14563524/q72-iceberg-analyzed-queryinfo.json)

**Comment by tdcmeehan** [comment]
@ZacBlanco quick unrelated question: when would null fractions ever be inaccurate when they come from Iceberg?  From my understanding of the spec, manifest files store the absolute count of nulls, so shouldn't the fraction be mergeable and hence completely accurate solely from the manifest file information?

**Comment by yzhang1991** [comment]
Confirmed that this issue goes away after applying the session property in run `c1w0_native_oss_sf1k_ice_ds_power_240311-214304` Closing this issue now.

**Comment by aaneja** [comment]
>It seems when this issue was filed the statistics for the iceberg versions of the tables were also not yet in the HMS. So ANALYZE was probably not run on these tables.


@ZacBlanco Can we test this hypothesis? I recall I analyzed a table, set the right feature flag, but could not get the NDVs to show up without doing a re-analyze. If we can add this as a integration test, that would be ideal

**Comment by ZacBlanco** [comment]
@aaneja See https://github.com/prestodb/presto/pull/22162
