### ISSUE TITLE
Expose Presto's View definition to other engines

### ISSUE THREAD

**Issue by huangxiaopingRD** [prestodb/presto#22269]
When using Presto to create a hive view, other engines cannot read it because Presto uses base64 encoding on the original text before writing the view to the hive metastore. As a result, other engines cannot read the definition of the view.
## Expected Behavior or Use Case

Do not encode the view's raw text

## Presto Component, Service, or Connector

presto-spi， hive connector

## Possible Implementation

Remove the logic of using base64 to encode and decode view original sql in the code

## Example Screenshots (if appropriate):
1. presto SQQL：create view xxx as select
2. spark SQL：desc formatted xxxx
<img width="1530" alt="image" src="https://github.com/prestodb/presto/assets/35296098/28bb5cde-95a6-447a-9f20-db5479b33b45">

## Context

Many companies do not use Presto to execute DDL statements because Presto's metadata operations may not be compatible with other engines (such as Spark), resulting in fewer usage scenarios for Presto.

**Comment by tdcmeehan** [comment]
How would Spark or other engines interpret the SQL?  Wouldn't there be potential semantic differences between the two without some sort of sophisticated rewrite?

**Comment by huangxiaopingRD** [comment]
The problem of syntactic differences does exist. This is a big topic and there is no perfect solution in the industry. This issue just wants to consider exposing view original sql to the outside world, especially the scenario of hive connector.

> How would Spark or other engines interpret the SQL? Wouldn't there be potential semantic differences between the two without some sort of sophisticated rewrite?

**Comment by tdcmeehan** [comment]
@huangxiaopingRD how do you propose we go about this change, since people have already saved their views?

I also don't think it's wise to optimistically presume SQL is compatible across engines.  The most dangerous thing is SQL which executes, but has semantic differences, because these differences may be persisted, or end up in dashboards or reports which then cause people to make bad decisions based on flawed queries.  If the intention of this issue is to make it so people can accidentally run Presto SQL views in Spark or Hive and perhaps only discover that there are differences in semantics and syntax after the fact, that seems like a non-objective.

**Comment by huangxiaopingRD** [comment]
> @huangxiaopingRD how do you propose we go about this change, since people have already saved their views?
> 
> I also don't think it's wise to optimistically presume SQL is compatible across engines. The most dangerous thing is SQL which executes, but has semantic differences, because these differences may be persisted, or end up in dashboards or reports which then cause people to make bad decisions based on flawed queries. If the intention of this issue is to make it so people can accidentally run Presto SQL views in Spark or Hive and perhaps only discover that there are differences in semantics and syntax after the fact, that seems like a non-objective.

@tdcmeehan  I agree with you. Thanks for your reply and I will close this issue.
