### ISSUE TITLE
Anomaly found in Schema Creation for Hive and Iceberg Catalogs

### ISSUE THREAD

**Issue by dmariamgeorge** [prestodb/presto#22553]
There exists an anomaly in schema creation where cross schema creation is happening between two different catalogs (Hive or Iceberg). When using a common Hive Metastore Service for two different catalogs, say a Iceberg catalog and a Hive catalog, or two Iceberg catalogs, and trying to create schema in the first catalog by specifying the location of the second catalog, cross schema creation is getting possible. Schema is getting created in the second catalog. 

Consider two Iceberg catalogs, **catalog_a** and **catalog_b**. Try creating schema in the first catalog, '**catalog_a**' with specifying the location of the second catalog 'catalog_b'.

CREATE SCHEMA catalog_a.i1 WITH (location = 's3a://<catalog_b_storage>/i1');

Schema is getting created and not throwing any errors.

When executing the statement SHOW SCHEMAS from <catalog_name>, the created schema 'i1' will be shown for both the catalogs. When executing the CREATE TABLE <schema_name>.<table_name> statement under the first catalog 'catalog_a', the query is not getting executed successfully and resulting in connection timeout error. When executing the CREATE TABLE <schema_name>.<table_name> statement under the second catalog 'catalog_b', query
is getting executed successfully and not throwing any errors. From this it can be concluded that, the schema 'i1' which was created under the first catalog 'catalog_a' by specifying the location of the second catalog 'catalog_b' was created under the second catalog 'catalog_b'.

## Your Environment
* Presto version used: v0.288
* Storage (HDFS/S3/GCS..): IBM Cloud Object Storage
* Data source and connector used: Iceberg, Hive

## Expected Behavior

Cross schema creation should not be possible, and should throw the right error message. 

## Current Behavior

Schema is getting created, and not throwing any errors. 

## Steps to Reproduce

1. Create an Iceberg catalog A backed by any storage A-prime.
2. Create an iceberg catalog B backed by any storage B-prime.
3. Now create a schema as follows:

    create schema A.test with (location="s3a://B-prime/test")

4. The schema will appear under catalog B.

## Context

This behaviour is an anomaly in schema creation.

**Comment by tdcmeehan** [comment]
This is a limitation of sharing the same metastore between two Iceberg catalogs, and it's not a bug.  It is the same problem as having two Hive catalogs share the same metastore.

There is no guarantee of isolation between catalogs in Presto.  This is because catalogs represent specific settings in a connector.  If the setting of metastore, which is the internal catalog of tables, is the same between two Presto catalogs, then it is expected behavior that they would share the same tables.  An example of why one might want this is you might want two different catalogs for batch and interactive queries--the Hive or Iceberg catalog for the batch queries would have settings appropriate for batch, and likewise for the interactive catalog.
