### ISSUE TITLE
Presto allows cast from out-of-range floating point value to bigint and returns "bogus" result

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#22640]
```
presto> select cast(REAL '2.0523825839131036E23' as bigint);
        _col0
---------------------
 9223372036854775807
(1 row)
```

Prestissimo throws: 

```
VeloxUserError:  Cannot cast REAL '2.0523335847491578E23' to BIGINT. Loss of precision during arithmetic conversion: (long) 2.0523335847491578E23 cast((field_0) as BIGINT)
```

CC: @rschlussel @spershin @tdcmeehan @aditi-pandit @kgpai @kagamiori @gggrace14 @amitkdutta

**Comment by mbasmanova** [comment]
CC: @Yuhta

**Comment by mbasmanova** [comment]
I wonder if Presto's behavior is by design. It seems to return max (or min) bigint when input value is out of range.

```
presto> select cast(REAL '2.0523825839131036E23' as bigint);
        _col0
---------------------
 9223372036854775807
(1 row)

presto> select cast(REAL '-2.0523825839131036E23' as bigint);
        _col0
----------------------
 -9223372036854775808
(1 row)
```

**Comment by elharo** [comment]
What does the ANSI SQL spec say should happen?

**Comment by tdcmeehan** [comment]
See reference from the spec below.  Postgres also throws.  To me, this seems like a bug.

> 9) If TD is approximate numeric, then
Case:
a) If SD is numeric, then
Case:
i) If there is a representation of SV in the data type TD that does not lose any leading significant digits after rounding or truncating if necessary, then TV is that representation. The choice of whether to round or truncate is implementation-defined.
ii) Otherwise, an exception condition is raised: data exception — numeric value out of range.

**Comment by tdcmeehan** [comment]
It looks like this was fixed by https://github.com/prestodb/presto/pull/22917, closing
