### ISSUE TITLE
Multiple modules failing in CI [Could not download Node.js]

### ISSUE THREAD

**Issue by imjalpreet** [prestodb/presto#22676]
Multiple modules failing due to the below error
```
Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.15.0:install-node-and-yarn (install node and yarn) on project presto-main: Could not download Node.js: Could not download https://nodejs.org/dist/v18.20.2/node-v18.20.2-linux-x64.tar.gz: Premature end of Content-Length delimited message body (expected: 44,323,820; received: 10,018,816) -> [Help 1]
```

Example: https://github.com/prestodb/presto/actions/runs/8966323942/job/24621616088?pr=22675
https://github.com/prestodb/presto/actions/runs/8965297597/job/24618540265?pr=22674

**Comment by tdcmeehan** [comment]
@yhwang This is probably because of #22645.  I wonder if we can retry somehow in the plugin.

**Comment by yhwang** [comment]
definitely from the PR, since it's caused by the `frontend-maven-plugin`. If the CI hosts reached the rate limit ( don't know if that's the reason) I guess retry may still fail. I don't see `retry` in the plugin doc but I saw this:

> Node/npm will only be "installed" locally to your project. It will not be installed globally on the whole system

Wondering if we can prep the the node/yarn on the GH action and skip the download to eliminate the download.

**Comment by yhwang** [comment]
by looking into the error message:
> Premature end of Content-Length delimited message body (expected: 44,323,820; received: 10,018,816)

@tdcmeehan your suggestion may work. seems not rate limit issue. let me figure out how to do retry for the plugin
