### ISSUE TITLE
"Fragments separation represent the data exchange between Presto nodes."

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#23675]
I'm not quite sure what this means or if it's correct, but at the least it has bad subject verb agreement. Maybe "Fragments' separations represent the data exchange between Presto nodes." but I'm not sure. 

https://prestodb.io/docs/current/sql/explain.html

**Comment by aaneja** [comment]
How about ' Each plan fragment is executed by a single or multiple Presto nodes and represents a data exchange boundary between nodes' cc: @steveburnett

**Comment by steveburnett** [comment]
I don't think combining the sentences helps, honestly, so I'd like to leave "Each plan fragment is executed by a single or multiple Presto nodes." as it is because that seems simple to understand. 

Addressing the second sentence and @elharo's concern, while the expressed subject verb agreement concern could be addressed by something like 
"Fragment separation represents the data exchange between Presto nodes." 
However, when I read this sentence I am not sure what is meant by "represent", and that may not be the best word here. Could someone who knows this topic suggest a revision of this sentence?

**Comment by tdcmeehan** [comment]
How about we enrich the [Presto concepts](https://prestodb.io/docs/current/overview/concepts.html) page and include sections for **query plan** and **plan fragment**.  And just link the first sentence to the newly added plan fragment section, and remove this second sentence?

**Comment by tdcmeehan** [comment]
I took a quick stab at some initial documentation for Presto concepts, appreciate feedback:

> ### Query Plan
> 
> A query plan is a sequence of steps used to access and manipulate data according to the SQL query.  It is represented as a tree of nodes, with each node representing an [operator](https://prestodb.io/docs/current/overview/concepts.html#operator).   Because multiple query plans can return data in an equivalent way, but with different implications for performance, Presto uses a query optimizer to make query plans more efficient.
> 
> There are two phases of optimization: logical and physical.  The logical phase of optimization transforms plans by only considering algorithmic complexity.  After a plan has been logically optimized, the plan is then converted into a more specific form called the physical plan, which is optimized for distributed execution and includes details such as the number and [types](https://prestodb.io/docs/current/overview/concepts.html#server-types) of nodes which should process a query plan node, and how data is [exchanged](https://prestodb.io/docs/current/overview/concepts.html#exchange) between Presto servers.
> 
> ### Plan Fragment
> 
> A **plan fragment** is a section of the physical query plan executed by [tasks](https://prestodb.io/docs/current/overview/concepts.html#task) on different [Presto servers](https://prestodb.io/docs/current/overview/concepts.html#server-types).

**Comment by steveburnett** [comment]
Thanks! Two minor revisions for shortness, with the intent to improve readability. 

* Maybe change 
"Because multiple query plans can return data in an equivalent way, but with different implications for performance, Presto uses a query optimizer to make query plans more efficient." 
to
"Because query plans can have different performance behavior, Presto uses a query optimizer to make query plans more efficient."

* Consider changing 
"After a plan has been logically optimized, the plan is then converted into a more specific form called the physical plan,"
to 
"The logically optimized query plan is then converted into a physical query plan,"

**Comment by tdcmeehan** [comment]
Thanks @steveburnett, updated my response to include your suggestions.
