### ISSUE TITLE
SliceDictionaryStreamReader creates too much garbage

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#2644]
Profiling shows that `openRowGroup()` is responsible for about 60% of all object allocation on the workers, at least for highly selective queries. This is likely a side-effect of 9bf232f07f8b2a7eec864e77188e51e94da1b41c

We should add a heuristic when creating these dictionaries to avoid large buffers, but also avoid too much object creation

**Comment by cberner** [comment]
Assigning to myself, so that we don't lose track of this, but if someone else wants to write a patch that'd be great!

**Comment by Myrthan** [comment]
I want to but I need to have design review or some hints how it should be written.

**Comment by haozhun** [comment]
@cberner 

I was about to start writing code on this one. But I realized a flaw with the solution we discussed.

In case I didn't remember the solution we discussed correctly. Let me summarize our discussion first.

>There are 2 alternatives for allocating memories for slices in the dictionary:
>   1. Use an individual slice for each slice. This can cause excessive memory allocation, which causes gc issues. (after 9bf232f)
>   2. Use a shared buffer for slices in the dictionary. This can cause heap fragmentation and excessive memory retention. (before 9bf232f)
> 
> The solution you suggested was a heuristic:
>   * If `numberOfRow / dictionarySize > 5`, alternative 1 is used. Excessive memory allocation is unlikely to happen because the number of slices in the dictionary is relatively small.
>   * Otherwise, a variant of alternative 2 is used. But instead of having each data link to the shared buffer, data is copied. This variation avoids excessive memory retention. And by using a shared buffer, memory allocation is also limited.

The flaw here is:
* In order to copy the data, a Slice object needs to be allocated for each row. In alternative 1, a byte array and a Slice object is allocated for each item in the dictionary. With this new approach, a Slice object is allocated for each row. As a result, more allocation will be needed with this new approach when `numberOfRow / dictionarySize > 2`. And `numberOfRow / dictionarySize > 2` is almost always true.

**Comment by cberner** [comment]
You don't need one slice per row, you can have one slice per block. You can use a variable width block builder which creates a single slice for the whole block and an array of offsets. Just make sure to size it correctly, so that it doesn't have to reallocate the underlying slice

**Comment by haozhun** [comment]
This is more like a code structure issue.

`OrcRecordReader.readVector`, `SliceStreamReader.readBatch`, `SliceXXXStreamReader.readBatch` all use an `ObjectVector` in the argument to pass to its caller the result. And like every other `LazyBlockLoader`s in `OrcPageSource`, `OrcPageSource$LazySliceBlockLoader` depends on such an API.

I'll talk to Dain and see why `LazyVariableWidthBlock` doesn't exist, and see his opinion on re-structuring the API so that object creation for each Slice can be avoided. If that happens, this change will benefit `SliceDirectStreamReader` as well.

**Comment by dain** [comment]
@cberner basically, we're going to try the simpler approach and see if the problem is resolved.  If not, we can do the more complex approach.

**Comment by haozhun** [comment]
In addition, I was wrong in saying that a Slice object needs to be allocated for each row. Instead, a Slice object is only needed for each dictionary entry.
