### ISSUE TITLE
Proper coercion support for type parameters and computed literals

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#3447]
We have spotted an issue when trying to implement coercion for DECIMAL type. Consider
`BOOLEAN equal(A a, B b)`
where `A` and `B` is `comparableWithVariadicBound(DECIMAL)`. In such case query:
`12 = DECIMAL 12`
will fail even though `12` can be easily coerced to `DECIMAL(19,0)`.
This is because coercion for type parameters is limited and works only if coercion target is already resolved form other, non coerced parameters. This won't work in decimal case (and possibly others) because the coercion target (in example case `DECIMAL(19,0)`) cannot be deduced from other parameters.

Another issue is with literal parameters, which are calculated. Consider function:
`DECIMAL(x1+x2, y1+y2) someFunction(DECIMAL(x1, y1) param1,  DECIMAL(x2, y2) param2)`
In this case we could call this function as `someFunction(1, 2)`. `BIGINT` parameters could be easily coerced to `DECIMALs`. Again the problem is that we need to resolve coercion target when matching function parameters.

This is why we propose a method similar to `Optional<Type> getExactCoercionTarget(Type actualType, TypeSignature expectedType)`. `canCoerce` from `FunctionRegistry` could be implemented on top of it. We could use `getExactCoercionTarget` in cases like described to perform coercion when target type cannot be resolved from other function parameters.

Note that `DECIMAL(19, 0)` represent the slower, long decimal version. So coercing `BIGINT` to `DECIMAL(19, 0)` would not have the best performance. So the question is also whether having such coercion is beneficial in the first place

Side node: as an additional improvement it may also be worth to refactor type hierarchy handling. Making this modularized and pluggable would be beneficial for plugins and would make the whole mechanism cleaner and more understandable.

CC: @cberner @dain

**Comment by martint** [comment]
> Again the problem is that we need to resolve coercion target when matching function parameters.

Indeed, this is the kind of problem I assumed we would start seeing once we added more complex features to the type system. The current type system and inference engine are too dumb to handle it (they work bottom up, but what we need is something more powerful modeled as a constraint solving problem and a clear definition of type equivalence and assignability rules).

> Side node: as an additional improvement it may also be worth to refactor type hierarchy handling. Making this modularized and pluggable would be beneficial for plugins and would make the whole mechanism cleaner and more understandable.

We've avoided doing this because it's currently hard to reason about the implications of allowing arbitrary coercions. Once we revamp the type system and inference engine, we intend to make it possible for plugins to register their own.

**Comment by sopel39** [comment]
@martint so you suggest to skip coercions for decimals for now (and wait for more powerful engine) or should we try to improve the current mechanism to make it work in the cases described? Maybe if you outline other requirements that the coercion system should support we could propose some more refined approach (we had a modularized type hierarchy in Hadapt). What do you mean by implications of allowing arbitrary coercions?

**Comment by martint** [comment]
No, it's going to take a while to get to a more powerful engine, so we'll have to improve the current mechanism in the way you described. 

> Maybe if you outline other requirements that the coercion system should support we could propose some more refined approach (we had a modularized type hierarchy in Hadapt). What do you mean by implications of allowing arbitrary coercions?

What I meant is that allowing anyone to define implicit coercions can make it impossible to type-check a query (e.g., if there are cycles), may affect type-checking performance (high polynomial or exponential behaviors), may introduce ambiguity due to overloaded functions, and may result in "incoherent" type system (e.g., a -> b -> c may not be equivalent to a -> c).

Therefore, I would avoid tackling this part of the problem for now and define implicit coercions for new types in a controlled way.

**Comment by ilfrin** [comment]
@martint I'm wondering how important is to have those coercions in short term (ie. implementing this stop gap solution by just adding those specific ones in the way described)? Is it just convenience and ease of use, so that users don't have to do explicit casting, or do some external tools rely on their presence?

Anyway, I think for now we'll just come up with a proposal of some "more powerful engine" design, as you described it, and discuss it.

**Comment by sopel39** [comment]
Discussed coercions onsite
