### ISSUE TITLE
ORC reader slow/unstable for big stripe-level dictionaries

### ISSUE THREAD

**Issue by losipiuk** [prestodb/presto#3584]
We encountered very poor performance and presto instability when reading ORC files using dictionary encoding in case when dictionary is large. 

Seems like culprit is copying dictionary for each read batch of data in 
`SliceDictionaryStreamReader` around line 185: 

``` java
       int[] ids = Arrays.copyOfRange(dataVector, 0, nextBatchSize);
       boolean[] isNullVector = Arrays.copyOfRange(this.isNullVector, 0, nextBatchSize);
       Slice[] values = Arrays.copyOf(dictionary, dictionary.length);
       sliceVector.setDictionary(values, ids, isNullVector);
```

The change came in revision https://github.com/facebook/presto/commit/b18ca67d477c881ea173fcebebb223fcba511929

The code is fine for small dictionaries but for large ones performance is degraded at best. Reading from large files rendered presto unresponsive due to heap overconsumption and excessive GC operation.

Though large dictionaries are probably not very common in real world it would be nice to be able to work with them.

The fix we thought of is to fill sliceVector with actual data values based on dictionary in `readBatch`. And return sliceVector with `dictionary` flag set to `false`. We can do it only in case when dictionary is larger than batch size. Or maybe get rid of that copying at all. What is the benefit of using dictionary based sliceVector when we need to do the dictionary copy?

What do you think?

cc: @nileema, @dain,  @pnowojski, @sopel39

**Comment by nileema** [comment]
We copy the dictionary because we try to reuse the dictionary array across multiple reads. We can change it so that it creates a new dictionary array for every read. Then we wouldn't need to copy the dictionary. We would prefer to keep it as a dictionary (instead of flattening it out) as it will let us do more optimizations (across pages sharing the same dictionary).

**Comment by pnowojski** [comment]
What do you mean across multiple reads? Between different orc stripes? Do you refer to this part of the SliceDictionaryStreamReader?

```java
    private void openRowGroup()
            throws IOException
    {
        // read the dictionary
        if (!dictionaryOpen && dictionarySize > 0) {
            // resize the dictionary array if necessary
            if (dictionary.length < dictionarySize) {
                dictionary = new Slice[dictionarySize];
                dictionaryLength = new int[dictionarySize];
            }
```

To hot fix our use case, we have removed this second if check and we removed this Arrays.copyOf mentioned by @losipiuk . It indeed fixed performance/stability issue for us, but we are not sure if such change can brake something? It could if something somewhere is modyfing dictionary in place. But we couldn't find anything like this. Closes would be method compactAndGet from LazySliceArrayBlock, however it first creates COPY of this dictionary. As far as we can tell, this Arrays.copyOf in SliceDictionaryStreamReader::readBatch is abundant. Is that correct?

As far as removing this if check in SliceDictionaryStreamReader::openRowGroup (so that new dictionary array is allocated on every dictionary read), it shouldn't impact perfomance at all. If the array is small, one more allocation per stripe is meaningless. If dictionary array is huge, bottleneck is Arrays.copyOf.

pull request with this change described above: #3589
