### ISSUE TITLE
Automatic conversions for literals

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3740]
It would be nice if this worked:

``` sql
CREATE TABLE foo (ds date);

SELECT * FROM foo WHERE ds = '2015-10-09';
```

**Comment by martint** [comment]
I don't think this is a good idea. It amounts to allowing implicit coercions between types that would normally not be allowed in some contexts. Unless we can clearly describe what's the general rule, it's going to be a problem to reason about and do safely.

For example, given that bigint implicitly casts to double, how should this be resolved if `x` is bigint?

```
x = 1.0
```

Would 1.0 be implicitly converted to a bigint, assuming it follows the same rule as the example you posted above?

It also makes the language very inconsistent. For instance, should this work?

```
ds = ('2015-' || '10-09')
10 + '2' = 1 || 2 
```

It would also allow for expressions like these:

```
1 + '2'  => 3?
1 || '2'  => '12'?
```


It can also result in ambiguities. For instance, if there's an `foo(date)` and a `foo(varchar)` defined, what would `foo('2015-10-09')` do? One answer would be "it binds to the most specific function". This is problematic, because if you only start with a `foo(date)` any queries that rely on the implicit conversion, would break if the `foo(varchar)` form is introduced later.
