### ISSUE TITLE
multiple coordinator support

### ISSUE THREAD

**Issue by knight1128** [prestodb/presto#3918]
Hi. I'm novie of presto.

Do you, guys have plan to support multiple coodinator?
I have known discovery.uri have only one host. I hope to support multiple coodinators of discovery.uri.

If I wrong, please take a example. It is very helpful for me.

**Comment by sbmaggarwal** [comment]
The same issue reported [here](https://github.com/prestodb/presto/issues/10174) (on a later date but better explained).

**Comment by HariSekhon** [comment]
That describes multiple coordinators for performance scaling clusters.

It would be nice if presto supported coordinator ha to start with.

One could use a load balancer, I have HAProxy config for this and other related big data and nosql tech here:

https://github.com/HariSekhon/haproxy-configs

**Comment by sbmaggarwal** [comment]
> > That describes multiple coordinators for performance scaling clusters.
> > It would be nice if presto supported coordinator HA to start with.
> > One could use a load balancer for coordinator high availability, I have HAProxy config for this and other related big data and nosql tech here:
> > https://github.com/HariSekhon/haproxy-configs
> 
> Hi Hari, sorry to disturb you. I tried to deploy a presto cluster with multiple active coordinator nodes, and use haproxy to achieve high availability. But I got a lot of warnings in SqlTaskManager, talking about the node is switching coordinator affinity from one to other. Is that ok?
> Thanks a lot

Hi @ZJULothar I am not sure about the HAProxy but as of now, PrestoDB doesn't support having multiple coordinators and this is what happens if you try to configure multiple coordinators, the nodes infinitly switch between those coordinators whenever each coordinator ask for a heartbeat.

**Comment by ZJULothar** [comment]
@sbmaggarwal OK, thanks for your reply

**Comment by HariSekhon** [comment]
Did you use the config at the link I provided? That should do an Active / Backup style HAProxy which means the second coordinator should not be used unless the first goes down.

The other alternative is to use heartbeat / pacemaker traditional active/standby clustering to keep one coordinator shut down until the other one fails, at which point the cluster tech would start up the other coordinator and fail over the VIP so that nodes would transparently contact the second coordinator.

I would definitely like to see better native support for coordinator HA, including documentation, rather than admins having to come up with their own solutions.

**Comment by ZJULothar** [comment]
@HariSekhon I got it, thanks buddy
