### ISSUE TITLE
Full GC happening on nodes causing PAGE_TRANSPORT_TIMEOUT exception with distributed joins.

### ISSUE THREAD

**Issue by reliablendn** [prestodb/presto#4004]
Hello,

We are seeing this error with some of our big queries which deals with huge amount of data in join, after upgrading from 0.117 to 0.125. Disabling distributed join seems to fix the issue and everything works fine. I was reading this thread https://github.com/facebook/presto/issues/3876 and tried tweaking jvm settings but to no avail. Distributed joins was enabled by default in 0.116 so so it should have started happening from that version but the same queries works fine till 0.117 and fails on all later versions. 

We have a 13 node presto cluster with 24G attributed to each presto node with this config:

http-server.http.port=8081
query.max-memory-per-node=14GB
query.max-memory=180GB
discovery.uri=<discovery-uri>
node-scheduler.min-candidates=1
node-scheduler.max-splits-per-node=50
optimizer.optimize-hash-generation=false
distributed-joins-enabled=false

Also is there any config to increase the timeout which throws PAGE_TRANSPORT_TIMEOUT. From the code it looks like its set to 1m but in our case we might need to increase this. I tried increasing scheduler.http-client.timeout and exchange.http-client.timeout but both of them didn't take effect and I got the same exception with 1m timeout.

**Comment by reliablendn** [comment]
So we tried presto 0.125 with distributed joins disabled and that is still causing Full GC issue. With 0.117 we are not seeing any of it. Any pointers to what might be causing this and what can be done. Also we tried 0.126 and same problems persists.

Cheers

**Comment by dain** [comment]
It is hard to say without seeing you cluster.  There are many things that can happen as you push your cluster to the limits.  I would start by upgrading to the latest release and checking if we already fixed the root cause.   If that doesn’t work I would spend some time to convince myself it is GC causing the timeouts (correlate the GC logs to timeouts), before starting on anything else.  Assuming you still think it is GC, I would configure the GC to print a histogram to see what is taking up the space.  Additionally, I might grab a heap dump.  It is possible there is a leak which should be easy to spot. 

We have one very old cluster that uses a 28GB heap.  Here is the config we use:

#
#worker jvm.config
-server
-Xmx28G
-Xms28G
-XX:+PreserveFramePointer
-XX:-UseBiasedLocking
-XX:+UnlockExperimentalVMOptions
-XX:G1MaxNewSizePercent=20
-XX:G1HeapRegionSize=32M
-Xss2048k
-XX:+UseG1GC
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+UseGCOverheadLimit
-XX:OnOutOfMemoryError=kill -9 %p
-XX:ReservedCodeCacheSize=250M
-agentpath:/packages/presto.presto/bin/libjvmkill.so
-agentpath:/packages/presto.presto/bin/libperfagent.so
# this is just debug info
-XX:+PrintGCApplicationConcurrentTime
-XX:+PrintGCApplicationStoppedTime
-XX:+PrintGCCause
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-XX:+PrintGCDetails
-XX:+PrintClassHistogramAfterFullGC
-XX:+PrintClassHistogramBeforeFullGC
-XX:PrintFLSStatistics=2
-XX:+PrintAdaptiveSizePolicy
-XX:+PrintSafepointStatistics
-XX:PrintSafepointStatisticsCount=1
  
#
# worker config.properties
coordinator=false
task.max-worker-threads=32
task.writer-count=5
http-server.threads.max=500
compiler.interpreter-enabled=false
exchange.http-client.idle-timeout=10s
discovery.http-client.request-timeout=10s
query.max-memory-per-node=10GB
