### ISSUE TITLE
Optimize memory usage of AbstractMinMaxBy

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4126]
`AbstractMinMaxBy` uses `getSingleValueBlock()` and then stores them in an array. This is extremely wasteful for narrow data types, such as `BIGINT`. This should be optimized so that the state object used for grouped aggregations stores the native container values in a flat, segmented, array

**Comment by wenleix** [comment]
I am looking into this.

**Comment by wenleix** [comment]
Similar to `AbstractMinMaxAggregationFunction` ([code](https://github.com/wenleix/presto/blob/df72703e935961e0bec73ef5417f104b520f514a/presto-main/src/main/java/com/facebook/presto/operator/aggregation/AbstractMinMaxAggregationFunction.java#L110), we can specialize state class for primitive types -- it has 5 different state classes. However, since `MinMaxBy`  need to store both key and value in state, it would explode into 5*5=25 state classes.

We might want to only specialize it for some common cases, and use the current general implementation. Need to discuss it.

**Comment by wenleix** [comment]
Since the memory issue is only with `GroupedMaxOrMinByState`, we can have `GroupedMinMaxByPartialState` (need to find a better name), and implement the 5 subclasses for partial state. And we can make `GroupedMaxOrMinByState` a generic class of key and value. The keys and values are going to be of the type `GroupedMinMaxByPartialState`.

Will check how to correctly initialize the new `GroupedMaxOrMinByState`  in this case.
