### ISSUE TITLE
Question about BlackHoleConnector

### ISSUE THREAD

**Issue by sweetfisheric** [prestodb/presto#4246]
Hello,

I have been working on BlackHoleConnector in order to get familiar with Presto. I am currently trying to implement the insertion for the connector but I have encountered some issues. I rewrote BlackHoleinsertTableHandle into followings

```
public class BlackHoleInsertTableHandle implements ConnectorInsertTableHandle
{
	 private final String schemaName;
	 private final String tableName;
	 private final List<BlackHoleColumnHandle> columnHandles;
	 private final int splitCount;
	 private final int pagesPerSplit;
	 private final int rowsPerPage;
	 private final int fieldsLength;
	
    @JsonCreator
    public BlackHoleInsertTableHandle(
    		@JsonProperty("schemaName")String schemaName,
    		@JsonProperty("tableName")String tableName,
    		@JsonProperty("columnHandles")List<BlackHoleColumnHandle> columnHandles,
    		@JsonProperty("splitCount")int splitCount,
    		@JsonProperty("pagesPerSplit")int pagesPerSplit,
    		@JsonProperty("rowsPerPage")int rowsPerPage,
    		@JsonProperty("fieldsLength")int fieldsLength){
    	this.schemaName = schemaName;
    	this.tableName = tableName;
    	this.columnHandles = columnHandles;
    	this.splitCount = splitCount;
    	this.pagesPerSplit = pagesPerSplit;
    	this.rowsPerPage = rowsPerPage;
    	this.fieldsLength = fieldsLength;
    }
	 @JsonProperty
	 public List<BlackHoleColumnHandle> getColumnHandles() {
		return columnHandles;
	}
         @JsonProperty
	 public int getFieldsLength() {
		return fieldsLength;
	} 
         @JsonProperty
	 public int getPagesPerSplit() {
		return pagesPerSplit;
	}
         @JsonProperty
	 public int getRowsPerPage() {
		return rowsPerPage;
	}
        @JsonProperty
	 public String getSchemaName() {
		return schemaName;
	}
         @JsonProperty
	 public int getSplitCount() {
		return splitCount;
	}
        @JsonProperty
	 public String getTableName() {
		return tableName;
	}
}
```

and implemented beginInsert in BlackHoleMetadata

```
    @Override
    public ConnectorInsertTableHandle beginInsert(ConnectorSession session, ConnectorTableHandle tableHandle)
    {
    	BlackHoleTableHandle b = checkType(tableHandle, BlackHoleTableHandle.class,"BlackHoleTableHandle");
    	
        return new BlackHoleInsertTableHandle(b.getSchemaName(), b.getTableName(), b.getColumnHandles(),
        		b.getSplitCount(), b.getPagesPerSplit(), b.getRowsPerPage(), b.getFieldsLength());
    }
```

If I do 'select *' from a BlackHole table, it still returns zero row. I have looked at the implementation of PageSink for other connectors but still not be able to grab the concept. If BlackHole is not a real database, am I supposed to save all the data in memory? How should I implement PageSink? Thank you.

Update: I think I've fixed the Jackson issue, but I am not sure if I did it correctly

**Comment by pnowojski** [comment]
Hi,

BlackHoleConnector at the moment doesn't store any data and it wasn't intended to do so. We have created it for performance tests of reading and writing from other connectors, like ```INSERT INTO blackhole.some_table SELECT * FROM hive.tpch100tb.orc.lineitem```, so it's not supposed to store any data. 

Implementing real PageSink for Blackhole, that would store inserted data even in memory, wouldn't be easy, since you would have to implement or use some external storage. You couldn't store data inside PageSink, since it is short lived and is destroyed once insert operation finishes. You even couldn't implement simple in memory static context for storing Pages, because it would reside in memory on some particular worker node on which particular PageSink was executed - you have no guarantee that when you access those data in select query, that PageSources will be spawned on the same nodes on which PageSinks were executed. In other words, if you have two nodes A and B. PageSink could have been executed on node A and PageSource could be executed on node B.

To do this properly, you would have to implement some in memory database, which you would access from Presto. As a training exercise Probably simpler solution would be to replace ```com.facebook.presto.plugin.blackhole.BlackHolePageSinkProvider.NoOpConnectorPageSink``` so that it would write to some textual file on HDFS and create ConnectorPageSource in ```com.facebook.presto.plugin.blackhole.BlackHolePageSourceProvider```that would read from those textual files (although it wouldn't be BlackHole anymore). Secondly you could still use current BlackHole's way of holding metadata about tables in memory, but you would have to extend those metadata to hold information about collection of file paths. For reading those data, simplest solution would be to create one ```com.facebook.presto.plugin.blackhole.BlackHoleSplit``` per each existing file (of course BlackHoleSplit would have to hold this file path, so that BlackHolePageSource would know which file to read).

Does it make sense to you?

**Comment by dain** [comment]
Instead of putting this in the black hole connector, I suggest we just add a new `MemoryConnector`.

**Comment by sweetfisheric** [comment]
Thank you for the explanation. I will have a look at Split and SourceProvider.

**Comment by cawallin** [comment]
Closing this, it's not an issue.
