### ISSUE TITLE
Presto + Hive Streaming + ORC: Malformed ORC file com.facebook.presto.orc.CachingOrcDataSource

### ISSUE THREAD

**Issue by timshenkao** [prestodb/presto#4587]
Hi!
We use Hive Streaming to ingest data and write it in ORC format directly without intermediate processing like Oozie + Hive scripts, etc. It's very convenient. Documentation: https://cwiki.apache.org/confluence/display/Hive/Hive+Transactions
But Hive creates temporary auxiliary files like bucket_00006_flush_length which are text files and not ORC files in directories delta_xxxxxxx.
So, when I make queries in Presto:
`select count(*) from table_hivestreaming;`
or
`select * from table_hivestreaming;`
I get error:
Query 20160219_085227_00029_wbw9s failed: Error opening Hive split hdfs://namenode:8020/user/hive/hive_streaming/dt=2016-02-19/dh=05/delta_0596801_0596900/bucket_00000_flush_length (offset=0, length=8): Malformed ORC file com.facebook.presto.orc.CachingOrcDataSource@7cf7aef1. Invalid postscript.

So, Presto should miss files with suffix '_flush_length' in order the queries to pass. 
Do you plan to add Hive Streaming support in Presto?
If not, where is it better to change the Presto code: in OrcReader.java ?

**Comment by dain** [comment]
I assume this is a form of Hive ACID tables.  If so, there is an issue here #1970, but there has been no progress because ACID tables aren't very popular yet.  If not and you are interested in support in Presto, I think you will need to implement it yourself (none of us had heard of this until reading this issue).
