### ISSUE TITLE
Convert LIKE without pattern to equality for TupleDomain

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#4643]
The Presto JDBC driver creates metadata queries like this:

```
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE,
  TYPE_NAME, COLUMN_SIZE, BUFFER_LENGTH, DECIMAL_DIGITS, NUM_PREC_RADIX,
  NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB,
  CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE,
  SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_TABLE,
  SOURCE_DATA_TYPE, IS_AUTOINCREMENT, IS_GENERATEDCOLUMN
FROM system.jdbc.columns
WHERE TABLE_CAT = 'hive' AND TABLE_SCHEM LIKE 'schema' AND TABLE_NAME LIKE 'table' AND COLUMN_NAME LIKE '%'
ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION
```

The `LIKE` filters don't have a pattern:

```
TABLE_SCHEM LIKE 'schema'
```

These should be converted to equality filters before generating the `TupleDomain` so that they can be pushed down to the connector.

**Comment by spragues-trulia** [comment]
i would rate this one pretty big as it effectively breaks the jdbc connector.  thanks david for identifying it.

**Comment by martint** [comment]
> These should be converted to equality filters before generating the TupleDomain so that they can be pushed down to the connector.

This should be done in the expression optimizer. It should apply to all cases, not just for the purpose of generating `TupleDomain`.

**Comment by zhenxiao** [comment]
@electrum @martint do u mean rewriting like filter without a pattern into equality filters in expression optimizer? If I am understanding correctly, willing to take a try

**Comment by martint** [comment]
@zhenxiao, yes, exactly

**Comment by JeffSaxe** [comment]
I am definitely not an expert, just sitting here in the peanut gallery admiring the discussion. It seems to me that rewriting LIKE a constant with no pattern into an equality is a no-brainer, all upside with no downside. 

But I'm curious about one of the other parts of that JDBC-generated string... `LIKE '%'`. This seems as if it's robotically generated by some code that snaps together all the `AND` clauses no matter what, but what does it really mean to use `LIKE` with a pattern that matches _anything_? Should that be completely optimized out of existence -- does it check anything at all? Or can it be turned into `COLUMN_NAME IS NOT NULL`, if `LIKE '%'` would actually omit the rows for a NULL value? Does `IS NOT NULL` gain any benefits in terms of predicate pushdown?

Again, I'm just trying to help. If we're looking at the one case in the Optimizer, it might be worth looking at the other as well.

**Comment by zhenxiao** [comment]
@electrum @martint seems like rewriting filter without a pattern into equality filters is already done:

presto:sf1> explain select partkey, name from part where name like 'hot chiffon';
                                                           Query Plan                                                           
--------------------------------------------------------------------------------------------------------------------------------
 - Output[partkey, name] => [partkey:bigint, name:varchar]                                                                      
     - Exchange[GATHER] => partkey:bigint, name:varchar                                                                         
        ** - Filter[("name" = CAST('hot chiffon' AS VARCHAR))] => [partkey:bigint, name:varchar]**                                  
             - TableScan[tpch:tpch:part:sf1.0, originalConstraint = ("name" = 'hot chiffon')] => [partkey:bigint, name:varchar] 
                     partkey := tpch:partkey                                                                                    
                     name := tpch:name                                                                                          
                                                                                                                                
(1 row)

**Comment by cawallin** [comment]
@electrum @zhenxiao closing this since it seems it's already implemented.

**Comment by sajjoseph** [comment]
@zhenxiao  - I noticed something strange with the query plan generated for the query @electrum mentioned here. Some reason, schema portion of the LIKE clause generates equality filter and table portion never does !

Query:
`explain
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE,
  TYPE_NAME, COLUMN_SIZE, BUFFER_LENGTH, DECIMAL_DIGITS, NUM_PREC_RADIX,
  NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB,
  CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE,
  SCOPE_CATALOG, SCOPE_SCHEMA, SCOPE_TABLE,
  SOURCE_DATA_TYPE, IS_AUTOINCREMENT, IS_GENERATEDCOLUMN
FROM system.jdbc.columns
WHERE TABLE_CAT = 'hive' AND TABLE_SCHEM = 'schema' AND TABLE_NAME LIKE 'table' AND COLUMN_NAME LIKE '%'
ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION`

Relevant part of the result:

   - ScanFilter[table = $system@system:$system@system:jdbc.columns, originalConstraint = (((""table_cat"" = CAST('hive' AS varchar)) AND (""table_schem"" = CAST('schema' AS varchar))) AND ((""table_name"" LIKE 'table') AND (""column_name"" LIKE '%'))), filterPredicate = (((""table_cat"" = CAST('hive' AS varchar)) AND (""table_schem"" = CAST('schema' AS varchar))) AND ((""table_name"" LIKE 'table') AND (""column_name"" LIKE '%')))] => [table_cat:varchar, table_schem:varchar, table_name:varchar, column_name:varchar, data_type:bigint, type_name:varchar, column_size:bigint, buffer_length:bigint, decimal_digits:bigint, num_prec_radix:bigint, nullable:bigint, remarks:varchar, column_def:varchar, sql_data_type:bigint, sql_datetime_sub:bigint, char_octet_length:bigint, ordinal_position:bigint, is_nullable:varchar, scope_catalog:varchar, scope_schema:varchar, scope_table:varchar, source_data_type:bigint, is_autoincrement:varchar, is_generatedcolumn:varchar]

Note that filterPredicate has table_schema part correctly generated but table_name part doesn't. For now, I created a patch like @electrum suggested, but it will be great if we can get it fixed in the expression optimizer.

**Comment by kokosing** [comment]
@sajjoseph Would it be possible to create a new issue instead of commenting an old one?

What is the Presto version that you are using?

**Comment by sajjoseph** [comment]
Done - https://github.com/prestodb/presto/issues/10222
Thanks

**Comment by kokosing** [comment]
Thanks!
