### ISSUE TITLE
Presto query to read from postgres  and load to hive fails for large table

### ISSUE THREAD

**Issue by tsvivek** [prestodb/presto#4727]
Presto version - 0.118
Query - "create table hive.db.test1 as select \* from pg.public.test1"

I have presto installed on 4 nodes, 1 of them being the coordinator node and the others are worker nodes.
The source table has approx 60 million rows. The query works when table has upto 100,000 rows.
When the query is executing (with no progress) i notice no spikes in CPU/Mem utilisation

Is there anything i need to tune at the Presto end ?

**Comment by tsvivek** [comment]
everytime i see the following error message in one of the nodes (actual node varies everytime):

com.facebook.presto.operator.PageTransportTimeoutException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load.

**Comment by cawallin** [comment]
See https://github.com/prestodb/presto/issues/4182 for more details on the PageTransportTimeoutException -- it's usually caused by a full GC or high CPU on one of the workers. Also, in the Postgres connector, Presto only has a single connection to Postgres, so it's not recommended for large tables without predicates. Free free to ask on the presto-users mailing list if you have further questions.
