### ISSUE TITLE
Incorrect results with corrupt binary statistics with the new Parquet reader

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#4732]
Corrupt statistics for the Parquet Binary type ([PARQUET-251](https://issues.apache.org/jira/browse/PARQUET-251)) affects the experimental Parquet reader when predicate pushdown is enabled. Apparently [the existing](https://github.com/facebook/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/parquet/predicate/TupleDomainParquetPredicate.java#L183) change for handling incorrect binary statistics cannot handle all the cases. Maybe it's time to upgrade to the latest stable Parquet release (v 1.8.1), which includes a proper fix.

cc\  @zhenxiao

**Comment by zhenxiao** [comment]
yes, exactly. We need to upgrade to a newer parquet version, which is using the org.apache namespace, not the old com.twitter namespace. presto-hive-apache needs to be updated to 1.8.1 first, then we could upgrade presto side. What do you think? @dain @electrum

**Comment by xubo245** [comment]
there are warnings :2016-4-15 14:24:31 WARNING: org.apache.parquet.CorruptStatistics: Ignoring statistics because created_by could not be parsed (see PARQUET-251): parquet-mr
org.apache.parquet.VersionParser$VersionParseException: Could not parse created_by: parquet-mr using format: (.+) version ((.*) )?\(build ?(.*)\)    in adam 0.18.3 
How to solve it please?

**Comment by zhenxiao** [comment]
@xubo245 are u using the new Parquet Reader or the old Parquet Reader in Presto? The stack trace u sent seems from a Parquet bug, which the old Parquet reader is depending on. For the new Parquet Reader, we bypass the messy Parquet-MR code, and do all the reading in Presto, with lots of optimizations. You could enable it by setting session properties:
set session parquet_optimized_reader_enabled=true
set session parquet_predicate_pushdown_enabled=true

**Comment by xubo245** [comment]
@zhenxiao sorry, I don't use Presto.  I use adam system:https://github.com/bigdatagenomics/adam
I don't know the version of Parquet.  In adam :   ` <parquet.version>1.4.3</parquet.version>`

**Comment by shardnit** [comment]
@zhenxiao are those parquet session properties removed in newer version of presto/presto-cli? I am running 0.149 and both properties are not found. 
`Unknown session property parquet_optimized_reader_enabled`
`Unknown session property parquet_predicate_pushdown_enabled`

**Comment by zhenxiao** [comment]
@shardnit these are session properties for hive connector. Here is from the latest branch:

`presto:luoz> show session;
                  Name                   |     Value      |    Default     |  Type   |                                    Description        
-----------------------------------------+----------------+----------------+---------+-------------------------------------------------------
 colocated_join                          | false          | false          | boolean | Experimental: Use a colocated join when possible      
 dictionary_aggregation                  | false          | false          | boolean | Enable optimization for aggregations on dictionaries  
 distributed_index_join                  | false          | false          | boolean | Distribute index joins on join keys instead of executi
 distributed_join                        | false          | false          | boolean | Use a distributed join instead of a broadcast join    
 execution_policy                        | all-at-once    | all-at-once    | varchar | Policy used for scheduling query tasks                
 hash_partition_count                    | 100            | 100            | bigint  | Number of partitions for distributed joins and aggrega
 initial_splits_per_node                 | 16             | 16             | bigint  | The number of splits each node will run per task, init
 optimize_hash_generation                | true           | true           | boolean | Compute hash codes for distribution, joins, and aggreg
 optimize_metadata_queries               | false          | false          | boolean | Enable optimization for metadata queries              
 plan_with_table_node_partitioning       | true           | true           | boolean | Experimental: Adapt plan to pre-partitioned tables    
 prefer_streaming_operators              | false          | false          | boolean | Prefer source table layouts that produce streaming ope
 processing_optimization                 | disabled       | disabled       | varchar | Type of optimization for query processing             
 push_table_write_through_union          | true           | true           | boolean | Parallelize writes when using UNION ALL in queries tha
 query_max_cpu_time                      | 1000000000.00d | 1000000000.00d | varchar | Maximum CPU time of a query                           
 query_max_run_time                      | 100.00d        | 100.00d        | varchar | Maximum run time of a query                           
 query_priority                          | 1              | 1              | bigint  | The priority of queries. Larger numbers are higher pri
 redistribute_writes                     | true           | true           | boolean | Force parallel distributed writes                     
 resource_overcommit                     | false          | false          | boolean | Use resources which are not guaranteed to be available
 split_concurrency_adjustment_interval   | 100.00ms       | 100.00ms       | varchar | Experimental: Interval between changes to the number o
 task_concurrency                        | 1              | 1              | bigint  | Default number of local parallel jobs per worker      
 task_share_index_loading                | false          | false          | boolean | Share index join lookups and caching within a task    
 task_writer_count                       | 1              | 1              | bigint  | Default number of local parallel table writer jobs per
 hive.force_local_scheduling             | false          | false          | boolean | Only schedule splits on workers colocated with data no
 hive.orc_max_buffer_size                | 8MB            | 8MB            | varchar | ORC: Maximum size of a single read                    
 hive.orc_max_merge_distance             | 1MB            | 1MB            | varchar | ORC: Maximum size of gap between two reads to merge in
 hive.orc_stream_buffer_size             | 8MB            | 8MB            | varchar | ORC: Size of buffer for streaming reads               
 hive.parquet_optimized_reader_enabled   | false          | false          | boolean | Experimental: Parquet: Enable optimized reader        
 hive.parquet_predicate_pushdown_enabled | false          | false          | boolean | Experimental: Parquet: Enable predicate pushdown for P
(28 rows)
`

And playing with them:

`set session hive.parquet_optimized_reader_enabled=true;`
`set session hive.parquet_predicate_pushdown_enabled = true;`

**Comment by electrum** [comment]
The Adam project is not related to Presto. Please file an issue with that project.

**Comment by ducky427** [comment]
+1

**Comment by ryanrupp** [comment]
If this issue ends up being a general issue for upgrading the Parquet library version I will note I ran into an exception [here](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetEncoding.java#L148) because with the latest version of Parquet-MR (1.9.0), which I was using to generate Parquet files, support was added for delta encoding was added to int64 (in addition to int32), see here - https://github.com/apache/parquet-mr/pull/154

In the meantime I worked around it by just disabling that encoding on the int64 column.
