### ISSUE TITLE
Selecting only partition column causes table scan in parquet-hive

### ISSUE THREAD

**Issue by billonahill** [prestodb/presto#4816]
```select min(datehour) from foo;``` will cause a full table scan on a table ```foo``` partitioned by ```datehour```. Instead the query should only scan the hive table metadata.

**Comment by martint** [comment]
Try setting the `optimize_metadata_queries` session property to true or enabling the `optimizer.optimize-metadata-queries` configuration option (in config.properties).

This optimization is disabled by default because it's invalid if there are empty partitions (which is, unfortunately, allowed by Hive).

**Comment by billonahill** [comment]
Thanks @martint. ```optimize_metadata_queries``` doesn't seem to be a session property, but I'll try setting the other on the connector, if possible. We can't set it globally since we do have empty partitions in some cases.

**Comment by martint** [comment]
The session property was added in the last version or the one before it

**Comment by billonahill** [comment]
Thanks I see it now. It's in 142.

**Comment by zhenxiao** [comment]
@billonahill the session property is in 142 release:
https://prestodb.io/docs/current/release/release-0.142.html

**Comment by nezihyigitbasi** [comment]
I guess this is resolved, please re-open if you see any issues.
