### ISSUE TITLE
why  not  support  delete operation ？

### ISSUE THREAD

**Issue by yuanxiang250** [prestodb/presto#4835]
https://prestodb.io/docs/current/sql/delete.html

presto version ==presto-server-0.142

execute ：：：

 delete from aa  where url_action like '%baseservice%' and date='20160301';

 ”date“  is my partition  。。。。 
presto  error：：： 
Query 20160320_051502_00027_e3mbd failed: This connector only supports delete where one or more partitions are deleted entirely

**Comment by dain** [comment]
Hive only supports dropping an entire partition at a time (under the covers it uses the Hive Metastore to drop the partition).  It is possible to rewrite a whole partition removing specific rows, but we have not implemented that since most people only manage whole partitions in Hive (and it is very expensive).
