### ISSUE TITLE
CLI displays misleading error if CLI and server versions are not compatible

### ISSUE THREAD

**Issue by brian-rickman** [prestodb/presto#4876]
If the CLI and server versions are not compatible, the CLI reports:

> Query is gone (server restarted?)

when a query using new datatypes is executed.

It would be much better if the CLI checked the server version when first establishing communications and reported "Version XXX of CLI is not compatible with version YYY of Presto server."

**Comment by electrum** [comment]
The protocol should be backwards compatible and thus the CLI should be forwards compatible. Unfortunately, there was a bug in the CLI Java code (it didn't affect clients in other languages).

We don't want the CLI to reject new server versions because it should be compatible.

An option here that we didn't think about previously (but could still implement) is to have the server return a fake error to old versions of the CLI (based on the User-Agent in the HTTP request).

**Comment by brian-rickman** [comment]
That seems like a good solution for times when the protocol is not actually backwards compatible.

**Comment by electrum** [comment]
Feel free to send a PR for this example you found.
