### ISSUE TITLE
Support INTERSECT

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#4918]
```
java.sql.SQLException: Query failed (#20160329_122015_00073_tc92r): line 410:11: INTERSECT not yet implemented
	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1824)
	at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1773)
	at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:142)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:193)
	at com.facebook.presto.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:68)
	at com.teradata.benchto.driver.execution.QueryExecutionDriver.executeSelectQuery(QueryExecutionDriver.java:59)
```

**Comment by anusudarsan** [comment]
I will be looking into this.

**Comment by anusudarsan** [comment]
We are planning to implement a first version of this as query rewrite, by rewriting the `INTERSECT` query as an `UNION ALL..GROUP BY..WHERE`.

Say we have a query:
`SELECT a FROM foo INTERSECT SELECT x FROM bar;`

This query can be rewritten in the following ways -
**Approach 1:**
```
SELECT a 
  FROM
  (SELECT a,
	COUNT(CASE WHEN intersect_marker = 1 THEN 1 ELSE null END) AS foo_cnt,
	COUNT(CASE WHEN intersect_marker = 2 THEN 1 ELSE null END) AS bar_cnt 
        FROM 
           (SELECT a, 1 as intersect_marker FROM foo UNION ALL SELECT x, 2 FROM bar) T1 
GROUP BY a) T2 
WHERE foo_cnt >= 1 AND bar_cnt >= 1;
```

**Approach 2:**
```
SELECT a FROM
	(SELECT a, 1 intersect_marker FROM foo
	UNION ALL
	SELECT b, 2 intersect_marker FROM bar)T
GROUP BY a HAVING SUM(intersect_marker) >= 3;
```
**Approach 3:**
`SELECT DISTINCT a FROM foo INNER JOIN bar WHERE a <=> x; `(provided we have a NULL safe equality operator implemented)

We think **Approach 1** is the best option here because:

1. Extending Approach 1 to implement `EXCEPT` will be easiest, since T1 and T2 will remain the same as the `INTERSECT` rewrite. 

2. Approach 1 will work the best for multiple branches scenarios like: 
	i)` a INTERSECT b INTERSECT c `
	ii) combination of SET operations - `((a EXCEPT b) INTERSECT c) UNION D)`
Here, Approach 3 will result in multiple joins whereas with Approach 1 we can condense everything into a single` group by`. Also, Approach 3 would involve figuring out the appropriate join ordering for optimal performance. In addition for Approach 1's query rewrite, T1 and T2 rewrite remains the same, only the expression after `GROUP BY `(`WHERE` clause) changes. 

3. Approach 2 and 3 will not work well and the rewriting logic wont be extensible when we want to implement `INTERSECT ALL` or `EXCEPT ALL`. With Approach 1, we already have the COUNT of the distinct records. Above this query rewrite, we could have a special operator that would know how to duplicate some set of these records n times (based on the count) for the `ALL` part.

Code changes:

Looks like the parser changes for `INTERSECT/EXCEPT` are already in place. For the query rewriting part, we are thinking to have the logic added as a new optimization rule extending PlanOptimizer. 

@martint  does this approach sound reasonable? We will be also working on Issue #4908 since its related.

**Comment by martint** [comment]
That sounds reasonable.

A slightly different rewrite could be:

```sql
SELECT a
  FROM
  (SELECT a,
    COUNT(foo_marker) AS foo_cnt,
    COUNT(bar_marker) AS bar_cnt
        FROM
           (
            SELECT a, true as foo_marker, null as bar_marker FROM foo
            UNION ALL
            SELECT x, null as foo_marker, true as bar_marker FROM bar
           ) T1
GROUP BY a) T2
WHERE foo_cnt >= 1 AND bar_cnt >= 1;

```

**Comment by anusudarsan** [comment]
ok. Thanks for the suggestion. This way there is no CASE statement to evaluate.

**Comment by gruberjuliannama** [comment]
Approach 1 we can condense everything into a singlegroup by. Also, Approach 3 would involve figuring out the appropriate join ordering for optimal performance. In addition for Approach 1's query rewrite, T1 and T2 rewrite remains the same, only the expression after GROUP BY(WHERE clause) changes.

Approach 2 and 3 will not work well and the rewriting logic wont be extensible when we want to implement INTERSECT ALL or EXCEPT ALL. With Approach 1, we already have the COUNT of the distinct records. Above this query rewrite, we could have a special operator that would know how to duplicate some set of these records n times (based on the count) for the ALL part??
