### ISSUE TITLE
Need a way to produce empty approx sets

### ISSUE THREAD

**Issue by martint** [prestodb/presto#4952]
`approx_set` currently produces NULL if there are no input values. Arguably, this is wrong, but it's consistent with the behavior of `sum`, `avg`, etc. (although not with `count`)

We need a way to represent empty approx sets. A couple of alternatives:
- Change approx_set to return an empty set if there's no input
- Introduce an approx_empty_set() function that can be used to substitute NULLs via COALESCE: ```COALESCE(approx_set(...), empty_approx_set())```
- Both?

**Comment by erichwang** [comment]
The consensus here is that we should support the empty_approx_set() function.

**Comment by philippu** [comment]
I will take a look at this. I also noticed that there is no documentation for approx_set().

**Comment by philippu** [comment]
May I ask what was the rationale for leaving approx_set to return NULL instead of an empty HLL state? I understand it makes it more consistent with other aggregate functions. But approx_set is not a stand-alone aggregate function. It just creates an intermediate state for incremental HLL computation. I just cannot think of a use case where a user would really want a NULL instead of an empty state.

**Comment by philippu** [comment]
The pull request should take care of it. Let me know what you think.
