### ISSUE TITLE
Inconsistent error messages for invalid queries with distinct

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#5157]
```
presto> select count(query), distinct(query) from presto_queries;
Query failed: line 1:22: no viable alternative at input 'distinct'
select count(query), distinct(query) from presto_queries
```
but
```
select distinct(query), count(*) from presto_queries;
Query failed: line 1:17: '"query"' must be an aggregate expression or appear in GROUP BY clause
select distinct(query), count(*) from presto_queries
```

**Comment by martint** [comment]
That's because `distinct` can only appear right after `select` or as the first thing in the argument list to a function. It's a set quantifier, not a function, so the first query would be equivalent to writing:

```select count(query), distinct query from presto_queries```

And the second query:

```select distinct query, count(*) from presto_queries```

So, the first query is syntactically illegal (hence the parsing error), while the second one is syntactically valid but semantically invalid because of a missing group by clause.

Per the SQL spec:

```
<query specification> ::= SELECT [ <set quantifier> ] <select list> <table expression>

<set quantifier> ::= DISTINCT | ALL
```
