### ISSUE TITLE
 Full table scan problem

### ISSUE THREAD

**Issue by Huangsir** [prestodb/presto#5361]
I use presto to query Redshift via postgre connector. But when I look at the sql on the Redshift dashboard, all the where sub querys are gone, and the sql become a full table scan sql and it's very slow..

**Comment by harunurhan** [comment]
I am not sure If I understand you correctly correctly but Presto works like this. It reads all data from data source in that case is Redshift then processes data according to your query (where conditions, aggregations etc.). 

About the speed, it is probably because you use Postgres connector which is a JDBC based connector and it is limited to a single connection.

**Comment by maciejgrzybek** [comment]
This should be a question for mailing list, not issue on Github.
If you believe your particular problem is a bug / regression, please provide details and steps to reproduce the problem.

**Comment by Huangsir** [comment]
ok~
