### ISSUE TITLE
Drop table in Hive leaves the empty folder to exist

### ISSUE THREAD

**Issue by Jimexist** [prestodb/presto#5685]
Hi, I wonder why the HDFS folder is still left to exist after I drop the table from presto-cli, e.g. `drop table users` will truncate all data in `hdfs://user/hive/warehouse/users` but the folder itself will be left to exist, which means I can not re-create the table because of the existing folder.

**Comment by haozhun** [comment]
For Hive connector, when you request that Presto drop a table, Presto simply tells Hive metastore to drop the table. Presto is not responsible for deleting the data. Instead, metastore will delete the data. In your case, metastore somehow decided that it’s going to leave the top-level directory alone. I’m not sure why this is the case. But I’m suspecting there are hidden files in the directory that metastore doesn’t feel safe to delete.

**Comment by jcap** [comment]
Just confirming we're seeing this too. 

These work as expected (no folder left behind):
- CREATE and DROP from Hive 
- CREATE in Presto and DROP from Hive 

These both leave a stray directory and as a result block reusing table name:
- CREATE and DROP from Presto
- CREATE in Hive and DROP in Presto 

Further:
```hadoop fs -rmdir hdfs:///...``` removes the directory cleanly. I _think_ confirming it is in fact empty.

**Comment by haozhun** [comment]
@Jimexist @jcap It would be great if one of you can find and explain the root cause of the issue. At that point, we can discuss how we are going to fix it.

**Comment by jcap** [comment]
@haozhun sure thing, we're looking into it now. If we find anything we will report back.

**Comment by jcap** [comment]
Ok well I think I at least found the error @haozhun : 

```
hive.log (MetaStoreUtils.java:logAndThrowMetaException(1314)) - Converting exception to MetaException
metastore.HiveMetaStore (HiveMetaStore.java:deleteTableData(1721)) - Failed to delete table directory: hdfs://host:8020/user/hive/warehouse/jcaptest1 Got exception: org.apache.hadoop.security.AccessControlException Permission denied by sticky bit setting: user=hive, inode=jcaptest1
```

**Comment by jcap** [comment]
The above seems to in fact have been the problem. 

Removing the sticky bit on ```hdfs://user/hive/warehouse``` resolves the problem though is likely not the best option.  

That said we've been unable to find the right combination of user for presto to talk to HDFS / Hive where this doesn't otherwise happen.

This is on EMR using the default perms they set on spin up.

**Comment by pgirolami** [comment]
Any progress on this issue ? Has it been determined why the sticky bit is set ?

**Comment by daigexuyu** [comment]
I find this problem is that the username of metastore is different from the username of creating files in HDFS, so please make sure the "hive.metastore.username" in hive.properties of the hive catalog file is the same as the username of creating files in HDFS. If not, the presto "drop table "  only drops the metadata, does not drop the folder in HDFS.

**Comment by daigexuyu** [comment]
I find this problem is that the username of metastore is different from the username of creating files in HDFS, so please make sure the "hive.metastore.username" in hive.properties of the hive catalog file is the same as the username of creating files in HDFS. If not, the presto "drop table " only drops the metadata, does not drop the folder in HDFS.

HDFS Username
When not using Kerberos with HDFS, Presto will access HDFS using the OS user of the Presto process. For example, if Presto is running as nobody, it will access HDFS as nobody. You can override this username by setting the HADOOP_USER_NAME system property in the Presto JVM Config, replacing hdfs_user with the appropriate username:

-DHADOOP_USER_NAME=hdfs_user

https://prestodb.io/docs/current/connector/hive.html#hive-configuration-properties

@Jimexist @jcap
