### ISSUE TITLE
how use presto-parser

### ISSUE THREAD

**Issue by sd4324530** [prestodb/presto#5757]
I want to know how many tables in sql
or how many columns in query sql

**Comment by cawallin** [comment]
It's a little unclear what your issue is. Are you trying to run a SQL query? Or are you writing a custom plugin and want to use the presto-parser module?

**Comment by dain** [comment]
The presto parser can not tell you the number of tables and columns in a query, since it only validates the syntax.  For example,  in `SELECT * FROM T` you don't know the columns, and then you have more complex stuff like `SELECT foo FROM (SELECT * FROM T)`.  The easiest and best way to determine this information is to run the full analyzer and planner.  For an example of this take a look at this test code: https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/testing/LocalQueryRunner.java#L586

**Comment by psaoji** [comment]
@dain Can you share sample code where we could call createPlan for any sample sql query ? I am trying to extract information about any input SQL query like table name, columns accessed, filter clause, etc. Would appreciate your help..

**Comment by findepi** [comment]
> @dain Can you share sample code where we could call createPlan for any sample sql query ?

@psaoji, for your information, @dain now works on https://github.com/prestosql/presto/ repo, you can find him there.
You can also find @dain on Presto Community Slack https://prestosql.io/slack.html
