### ISSUE TITLE
Support '==' as equivalent to '='

### ISSUE THREAD

**Issue by DerrickRice** [prestodb/presto#5847]
Usability perk. Software engineers have a habit of writing `==` when they intend to test equality. This is a syntax error in Presto. It would be nice if it was understood as an alternative to `=`.

There is precedent for this. `<>` is the traditional not-equal operator in SQL, but Presto supports `!=`.

**Comment by electrum** [comment]
Do any other database support this?

The != syntax is universal among SQL databases.

**Comment by electrum** [comment]
I checked and no other popular databases support this (aside from Hive). We avoid adding non-standard syntax unless there is a compelling reason. Adding additional syntax for an existing operator has the downside that it makes queries harder for others to understand, because now they have to know about the additional syntax.
