### ISSUE TITLE
Using presto with Vertica

### ISSUE THREAD

**Issue by wmorin** [prestodb/presto#5869]
Hi,
Is it possible to use Vertica with presto ? I can't find Vertica or JDBC in the connector list.

Thank you

**Comment by ebd2** [comment]
Hi,
This question came up on the presto-users mailing list back in April:

https://groups.google.com/forum/#!searchin/presto-users/vertica%7Csort:relevance/presto-users/-HGV8hzwTWk/5d_wd3rsIQAJ

In early May, somebody announced a website for community connector development:

https://groups.google.com/forum/#!searchin/presto-users/connector$20community%7Csort:relevance/presto-users/m72RewPMIE0/vO8cxxOdIwAJ

Direct link: http://presto-connectors.ml/

At the moment, there doesn't yet seem to be anything specifically for Vertica on that website, but you might try asking on the mailing list to see if anybody has done any work since then.
