### ISSUE TITLE
Resource groups for IO / number of concurrent drivers

### ISSUE THREAD

**Issue by RobinUS2** [prestodb/presto#5946]
Hi there,

We've been playing around a bit with https://prestodb.io/docs/current/admin/resource-groups.html and it's a really nice feature, yet still a basic one. My proposal would be to add IO limitations and concurrent drivers (running splits). 

I would love to hear your thoughts on these two items. If you believe this is a good idea I wouldn't mind taking the work to modify the code and open a PR.

Thanks !
- Robin

**Comment by electrum** [comment]
That's an interesting idea, though it would be need to be configured carefully. You could have a query that is tying up memory, but is executing slowly due to the concurrency restriction. It's easy and basically free to share CPU, but memory is fixed for the duration of a query, so you typically want to complete queries as quickly as possible once they start executing.

**Comment by dain** [comment]
The concept of concurrent drivers is not something I expect us to add to resource groups.  Instead, I think we are going to add a system to dynamically adjust these the concurrent drivers (we already do this in one case).  Additionally, I expect us to expand the priority stuff to allow us to favor high priority queries (e.g., allocate more concurrent drivers or give the drivers larger CPU slices).
