### ISSUE TITLE
Don't materialize pages in AggregateWindowFunction.accumulate

### ISSUE THREAD

**Issue by maciejgrzybek** [prestodb/presto#5954]
When frame is specified on rows (in oppose to range) significant amount of time is spent on building pages in `accumulate` method.
Example query:

``` sql
SELECT sum(quantity) over (rows between unbounded preceding and current row)
  FROM tpch.sf10.lineitem;
```

According to YourKit we spent 25% time on this:

```
+---com.facebook.presto.spi.PageBuilder.<init>(int, int, List) PageBuilder.java
  |
  +---com.facebook.presto.spi.PageBuilder.<init>(int, List) PageBuilder.java:46 
    |
    +---com.facebook.presto.spi.PageBuilder.<init>(List) PageBuilder.java:41 
      |
      +---com.facebook.presto.operator.window.AggregateWindowFunction.accumulate(int, int) AggregateWindowFunction.java:84 
        |
        +---com.facebook.presto.operator.window.AggregateWindowFunction.processRow(BlockBuilder, int, int, int, int) AggregateWindowFunction.java:67 
          |
          +---com.facebook.presto.operator.window.WindowPartition.processNextRow(PageBuilder) WindowPartition.java:111 
```

**Comment by maciejgrzybek** [comment]
Me or @ebd2 will take care of this.
Comments are welcome though.

**Comment by electrum** [comment]
Yeah, this is known to be inefficient, especially for small accumulations:
```java
// TODO: add Accumulator method that does not require creating pages
```
@cberner might have some thoughts on what the `Accumulator` changes should look like

**Comment by cberner** [comment]
I would need to look at it in more detail, but my initial thought is that instead of using `InternalAggregationFunction` this should be getting the underlying `MethodHandle`s and holding onto an `AccumulatorState`.

**Comment by cawallin** [comment]
@cberner -- I was looking into this, and in order to hold onto an `AccumulatorState`, you have to duplicate the input/final logic from `AccumulatorCompiler`. I guess the alternative is to change the bytecode itself -- either to add a method `Accumulator#addInput(WindowIndex index, int start, int end)`, which would re-use most of `Accumulator#addInput(Page page)` except the way it gets the arguments for the innermost `InputFunction` call. Or maybe addInput could be passed a lambda that returns the arguments for `InputFunction` (e.g. for `Page`, returns the relevant blocks for the page, or for `AggregateWindowFunction`, returns the equivalent from the `WindowIndex` for each row). Thoughts?

**Comment by electrum** [comment]
Adding an `addInput` method for `WindowIndex` seems like the most straightforward approach. The lambda might have performance issues with virtualization.

**Comment by cawallin** [comment]
Great, I'll look into that. Thanks for the input!

**Comment by maciejgrzybek** [comment]
I'm implementing this based on @cawallin's findings.
I'm going to add a `void addInput(WindowIndex index, int start, int end, int channel)` method to an `Accumulator` interface.

**Comment by maciejgrzybek** [comment]
PR's here: https://github.com/prestodb/presto/pull/6793

**Comment by maciejgrzybek** [comment]
Closing given https://github.com/prestodb/presto/pull/7788 is merged.
