### ISSUE TITLE
Implement prepared statements in JDBC driver

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6158]
This will use the functionality from #4338.

**Comment by electrum** [comment]
@nahi is working on this.

**Comment by xerial** [comment]
Spark also requires this PreparedStatement support when using presto-jdbc.

**Comment by electrum** [comment]
@nahi Are you still working on this?

**Comment by nahi** [comment]
@electrum Really sorry for late reply. I created this commit months ago but due to work commitments I didn't have enough time to write unit tests after that. https://github.com/treasure-data/presto/commit/9b042eec34fbc3ee679d9fee992b5c684b1c8bc8
It's already out-of-sync with current master branch but do you think it's worth trying to rebase?

**Comment by electrum** [comment]
We still need this feature, so please do! The JDBC driver hasn't had many changes so it's likely the rebase conflicts are minimal.

**Comment by kc14** [comment]
We are using PDI/Kettle/Spoon ... it would be very nice to have prepared statements in the presto jdbc driver, because otherwise spoon cannot get the metadata for the result set of an SQL statement, ie. it cannot explore and show, which fields and types the SQL statement will return ... it does this by preparing the SQL statement and then asking for DESCRIBE OUTPUT of the query ... so it would know, which fields the SQL statement would return ... any chances to see prepared statements in presto?

**Comment by nasmithan** [comment]
Has anyone had luck getting this working? Nahi's solution is nearly a year out of sync with master... is anyone still pursuing this? It would be great to have JDBC support for applications like PDI/Pentaho or Snaplogic.

**Comment by kokosing** [comment]
Currently prepared statements are supported by JDBC simba drivers which work with Teradata provided release of Presto.

**Comment by eakarsu** [comment]
So we can use https://www.simba.com/drivers/presto-odbc-jdbc/ simba jdbc drivers here? We can integrate spark to Presto. Right?

**Comment by chafidz0000000** [comment]
Any updates?

**Comment by craftmaster2190** [comment]
+1

**Comment by kevintop** [comment]
When can this function be completed?

**Comment by electrum** [comment]
I finished up @nahi's patch: #10673

**Comment by romeran** [comment]
+1 
Very needed indeed
