### ISSUE TITLE
Enum type broken in PostgreSQL

### ISSUE THREAD

**Issue by karol-szuster** [prestodb/presto#6212]
How to reproduce:

In postgres database create enum type and table:

```
CREATE TYPE my_enum AS ENUM ('foo', 'bar');
CREATE TABLE my_table (foo_or_bar my_enum);
```

Now when execute following query in presto

```
SELECT * FROM my_database.public.my_table WHERE foo_or_bar = 'foo';
```

it will fail with following error:

```
Query 20160928_101929_00001_fu4a5, FAILED, 1 node
Splits: 2 total, 0 done (0.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20160928_101929_00001_fu4a5 failed: org.postgresql.util.PSQLException: ERROR: operator does not exist: my_enum = character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 64
```

Actually this worked in 0.147 and stopped working in 0.148. I've did quick bisect and found that this problem has been introduced by following commit: [Improve QueryBuilder to support VARCHAR condition ](https://github.com/prestodb/presto/commit/c023565d883407a0c3e7bb8818f463d8ec683aac)

**Comment by rafalpas** [comment]
It seems that because PreparedStatement is used to build the query, it is necessary to specify the enum type when adding the value, e.g. `'foo'::my_enum` instead of just `'foo'` (see http://stackoverflow.com/questions/16492370/java-enum-and-postgresql-enum)

In current implementation the latter is added, as the type is identified by Presto as VARCHAR.

That would require changing the current:
`return quote(columnName) + " " + operator + " ?";`
and
`String values = Joiner.on(",").join(nCopies(singleValues.size(), "?"));`
to include the "::enum_name" (`?::enum_name`) if the type is enum, and obviously also passing down the actual type and enum_name so that it is available when adding the predicate. 

Alternatively the "::enum_name" could be added when the actual value is inserted with `statement.setString()`, but again the knowledge of actual type (enum) is needed.

The last alternative would be to revert to not using PreparedStatement, as in such a case the original statement works (you can check by issuing the `SELECT * FROM my_database.public.my_table WHERE foo_or_bar = 'foo';` query directly in postgres)

**Comment by gyson** [comment]
I got similar issue in presto 0.206. The following is a solution (cast enum to varchar via `||`) that works for my case:
```
SELECT * FROM my_database.public.my_table WHERE (foo_or_bar || '') = 'foo';
```
