### ISSUE TITLE
Consistent hashing when determining Raptor shards

### ISSUE THREAD

**Issue by buremba** [prestodb/presto#6252]
Currently Raptor uses modulo operator for determining the shard of a row and it makes it impossible to change bucket count of an existing table. We usually use 1 bucket for small tables for performance reasons and when the amount of data gets bigger, we have to create a new table from the existing one using a different shard count but it's an expensive operation.

We may use a decent consistent hashing algorithm called jump consistent hashing since it's simple and quite easy to implement. The algorithm is described in https://arxiv.org/pdf/1406.2294v1.pdf

I'm aware that this is a breaking change but we may add a flag to the metadata table in order to determine which algorithm we need to use. 

Also Presto doesn't support changing the table properties of an existing table yet but we may also add syntax for `SET TABLE PROPERTIES` for mutable properties similar to `SET SESSION`.

**Comment by electrum** [comment]
Thanks for the link to the Google paper. That's an interesting algorithm.

I don't think it's possible to use consistent hashing with Raptor bucketing since it doesn't provide the necessary data consistency properties. We rely only bucketing for aggregations and joins.

For example, if two tables use the same distribution (they share the same bucketing), and we are joining on the bucket keys, a local join is performed (no need to redistribute the tables over the network).

The same is true for aggregations. If we aggregate on the bucket keys, then we know all the data for a specific grouping value is guaranteed to be on a single machine, thus we can do the entire aggregation in one step (no hashing and transferring partials to a second stage).

Given Raptor's design of immutable shards, even moving a few values would require rewriting the shards anyway, thus recreating the table is a good strategy.

In the future, we could have support for rebuilding tables safely, even if concurrent processes attempt to insert or otherwise modify it.

**Comment by electrum** [comment]
However, you might know of some clever trick, so please let me know if I'm missing something here.

**Comment by buremba** [comment]
Ah, it seems that I forgot to write an answer. I think that bucketing can also be useful for predicate pushdowns for equality checks. If the predicate has certain values for bucket key i.e `bucket_key = 2` we might find the shards from bucket ids.

The reason for 1 bucket count is that network operations are expensive and Presto distribute the data of a table to the all nodes in the cluster even if it doesn't have many rows. It makes simple queries that scan whole table slow even for small tables. Since the tables won't be huge when we want to change the bucket_count, recreating the table might not be a problem as you suggested.

What do you mean by `Raptor doesn't provide the necessary data consistency properties`?

**Comment by electrum** [comment]
We actually do that predicate optimization for Hive buckets in the Hive connector (might only support a single value for equality). Now that we support this in the engine, we might be able to do it generically.

I mean that consistent hashing would not meet the requirements needed to tell the Presto engine that the table is bucketed (the engine would produce incorrect results).
