### ISSUE TITLE
Incorrect memory accounting for Hash Aggregation operator

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6436]
The following query reports peak memory that varies wildly from cluster to cluster and run to run. I've seen numbers ranging from 0 GB to 20 GB. It seems to be sensitive to how much concurrent work is being performed, how fast work completes, etc.

For instance, in one cluster, setting task_concurrency to 1 causes it to report ~2 GB. With a task_concurrency of 2 or higher, it reports 0 GB.

In another cluster, it reports 4.4 GB with task_concurrency=1 and 3 GB/3.3 GB/3.8 GB with task_concurrency > 1

```sql
SELECT custkey, count(*) c
FROM tpch.sf1000.orders
GROUP BY custkey
```

**Comment by martint** [comment]
There are 99,999,998 distinct values of orders.custkey in SF 1000, so the size of the aggregation should be at least 1.6 GB (8 bytes for the key, 8 bytes for the count, plus per-entry overhead).

**Comment by martint** [comment]
As @dain suggested, this might be due to partials being tracked as user memory instead of system memory.

**Comment by martint** [comment]
@haozhun, can you work on this?

**Comment by haozhun** [comment]
HashAggOpreator and AggOperator exempts 16MB (`task.operator-pre-allocated-memory`) per operator for the purpose of memory accounting. The exemption applies regardless of output-partial. #6455 removes this exemption for non-output-partial aggs. This is the reason why we see 0GB in some cases

I looked at the original query that lead to @martint filing this task. The peak memory usage for the query is higher when task_concurrency is set to 4 (compared to 1). It turns out this is caused by faster processing. When task_concurrency is on, queries that used to spread out their memory usage over a longer period of time are now using it all at the same time, which brings the peak memory usage higher.
