### ISSUE TITLE
Use LIMIT for automatic join ordering

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6621]
Consider the following query:
```sql
SELECT *
FROM (SELECT * FROM a LIMIT 10000)
JOIN b ...
```
The subquery should be assumed to be the small side of the join, since it has a small, fixed bound on the number of rows.

**Comment by idemura** [comment]
What pattern I see is we join (among other joins) with tiny dimension table (~1000). If you do distributed join on it, you'll see skew. I'd like to have opportunity to mark (annotate) that this join is broadcast join. But this may be good annotation itself - if we see limit on the one side of join we 1) flip it to the correct side 2) do broadcast join. For my small dimension table I will put artificially limit 10'000 (more than number of rows) just to let the optimizer run this optimization.

**Comment by rschlussel** [comment]
@idemura we're working on a statistics based optimizer that automatically chooses a broadcast join if one of the tables is small enough.  With an optimizer that's based on table statistics, we would know the table is small even if there is no limit clause.  There's no PR yet because @martint is still figuring out how to handle stats based optimizers in general, but it'll be coming soon!

**Comment by rschlussel** [comment]
linking https://github.com/prestodb/presto/issues/6257 since it is related.

**Comment by idemura** [comment]
@rschlussel as long as statistics take into account LIMIT it works for me.

**Comment by KBP-TDC** [comment]
@idemura It's actually more than statistics, it's cost/size estimation. @losipiuk can elaborate more but essentially all information that can be assessed before query starts (filtering, projections, limits, etc.) will be taken into account.
