### ISSUE TITLE
Implement cache size limit for CachingHiveMetastore

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#6665]
a heap dump from a cluster with only light load shows that this cache takes up a significant amount of space and also grows with size proportional to the number of partitions queried

**Comment by martint** [comment]
I thought we weren't using this, since we're only caching metadata per transaction now.

**Comment by cberner** [comment]
We did turn it off globally, but the per transaction cache is unbounded in size

**Comment by dain** [comment]
We really only need the transaction cache if we are running a non-autocommit transaction.  In autocommit the data is only read once.

**Comment by haozhun** [comment]
We are reading the data dozens of times regardless of whether we are in autocommit mode.

**Comment by dabaitu** [comment]
Sorry to comment directly here, but have been scratch my head on a problem that might be related to this. Our Presto(0.149) setup uses hivemetastore; we've noticed frequent ExternalErrors that says failed to connect to hive-metastore due to "ConnectException: Cannot assign requested address". This usually happens when several heavy queries hit the cluster at the same time(we have a small 180 machines cluster). Our ulimits all seem pretty high.
Still reading through the code to see how the HivePlugin is being used since that's the one establishing the connection. Any guidance to speed up the process would be greatly appreciated.

**Comment by haozhun** [comment]
Fixed in #6691
