### ISSUE TITLE
Views on Columnar Table

### ISSUE THREAD

**Issue by col15** [prestodb/presto#6708]
Question on the way views and column selection work... Given I created this view:

CREATE VIEW myview AS 
SELECT 
col1, col2, col3, table2.prop1, table2.prop2
sum(val4) as col4, sum(val5) as col5  
FROM table1_columnar, table2
WHERE table1_columnar.someid = table2.someid
GROUP BY col1, col2, col3, table2.prop1, table2.prop2

If I run the query shown below, will the view still process col2, col3, col4, & prop2 every time? 

SELECT col1, prop1, sum(col5) FROM myview GROUP BY col1, prop1;

This is only a simple example with a few columns but I wanted to know if views could leverage the columnar structure and performance by excluding certain columns if they were not actually being selected (without having to create many subset views)? 

Thanks!

**Comment by dain** [comment]
A view is just a stored query, so the engine inlines the query and then optimizes query.  In the case above, you end up with a query that looks like this:
```sql
SELECT 
col1, prop1, sum(col5) 
FROM (
    SELECT
        col1,  
        col2, 
        col3,  
        table2.prop1, 
        table2.prop2
        sum(val4) as col4, 
        sum(val5) as col5
    FROM table1_columnar, table2
    WHERE table1_columnar.someid = table2.someid
    GROUP BY col1, col2, col3, table2.prop1, table2.prop2
) 
GROUP BY col1, prop1
```
This will optimize to something like this:
```sql
SELECT 
col1, prop1, sum(col5) 
FROM (
    SELECT
        col1,  
        table2.prop1, 
        sum(val5) as col5
    FROM table1_columnar, table2
    WHERE table1_columnar.someid = table2.someid
    GROUP BY col1, col2, col3, table2.prop1, table2.prop2
) 
GROUP BY col1, prop1
```
So col2, col3, col4, & prop2 are pruned from the inner query, but must still be loaded because they are present in the inner `GROUP BY` clause.  The other sum `sum(val4) as col4` and the underlying column `val4` will be removed entirely from the query.

**Comment by col15** [comment]
Thanks dain for the great explanation. Seems optimal to also prune from the group by especially if querying columnar tables. Wish it worked that way, but I can workaround it with info you provided. Thanks!
