### ISSUE TITLE
Coordinator does not expire all queries

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6747]
I see finished queries that are several days old in the UI on busy clusters that should only have a few minutes worth of finished queries. This means there is a bug/leak in query expiration.

**Comment by elonazoulay** [comment]
We're experiencing this as well, taking a look also.

**Comment by elonazoulay** [comment]
The issue was that the finalQueryInfo listeners were not always being executed since the updateQueryInfo function was not always called after a possible transition to a terminal state. 
This is the function which calls compareAndSet to the finalQueryInfo StateMachine inside QueryStateMachine.

The leak only occured on busy clusters where the QueryExecution::getQueryInfo function (which is the only place that calls updateQueryInfo) was not called after the query transitioned to a terminal state.

Tested with a verifier suite that ran about 86k queries against our test cluster.

**Comment by elonazoulay** [comment]
Here is the updated fix: #6948

**Comment by nezihyigitbasi** [comment]
Fixed by #7362.
