### ISSUE TITLE
Incorrect results for UNION ALL query with duplicate column names

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6935]
This query:

```sql
SELECT 'x', 'y' 
UNION ALL 
SELECT orderstatus, orderstatus 
FROM orders
```

produces incorrect results:

```
 _col0 | _col1
-------+-------
 x     | x
 F     | F
 F     | F
 F     | F
 F     | F
 F     | F
...
```

Plan:

```
 - Output[_col0, _col1] => [orderstatus:varchar(1), orderstatus:varchar(1)]
         _col0 := orderstatus
         _col1 := orderstatus
     - LocalExchange[ROUND_ROBIN] () => orderstatus:varchar(1)
         - Project => [expr:varchar(1)]
                 expr := 'x'
             - LocalExchange[ROUND_ROBIN] () =>
                 - Values => []
                         ()
         - RemoteExchange[GATHER] => orderstatus:varchar(1)
             - TableScan[tpch:tpch:orders:sf0.01, originalConstraint = true]
                     orderstatus := tpch:orderstatus
```

This is probably another bug in UnaliasSymbolReferences.

**Comment by martint** [comment]
It used to work correctly in 0.157. This commit in 0.158 introduced a planning failure for that and other kinds of queries: 32ba4feb8c9fec5a2e04a982b58bb5de3947e445. This commit in 0.160 fixed the planning failure but introduce this issue: 1dd5c88150ddf13c6b9f25a21778a78b2784ecae.

**Comment by martint** [comment]
cc @sopel39

**Comment by sopel39** [comment]
The issue is caused by:
https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddExchanges.java#L1131
which adds layout consisting of output symbols. Therefore in:
https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddExchanges.java#L1144
a union node is created which has symbols mapping:
```
{expr_7=[expr, expr_7], expr_8=[expr_0, expr_8]}
```
This mapping is invalid since `expr_7` maps to itself union `expr`. I am not sure how to fix the bug since there is some partitioning and layout logic which I am not clear how it works yet. I will investigate more.

**Comment by sopel39** [comment]
Ok. I think it's trivial to fix. I will publish PR in a moment
