### ISSUE TITLE
JDBC driver should throw SQLFeatureNotSupportedException for PreparedStatement

### ISSUE THREAD

**Issue by the6campbells** [prestodb/presto#6957]
0.160 driver is throwing com.facebook.presto.jdbc.NotImplementedException which extends SQLNonTransientException.

Per JDBC API, it should be throwing SQLFeatureNotSupportedException which application code is designed to catch and handle.

https://docs.oracle.com/javase/6/docs/api/java/sql/Connection.html#prepareStatement(java.lang.String,%20java.lang.String[])

**Comment by electrum** [comment]
This is one of those areas where the specification is not clear:

* There are required methods such as `prepareStatement(String)` that are not specified to throw `SQLFeatureNotSupportedException`. For all of these, we throw our own `NotImplementedException`.
* Then there are optional methods such as `prepareStatement(String, String[])` which do throw `SQLFeatureNotSupportedException` as specified.

I intentionally chose not to extend `SQLFeatureNotSupportedException` since that exception is documented as being used for *"an optional JDBC feature"*. That's the reason I added that exception and painstakingly went through the docs to determine which methods were required vs optional.

However, I'm fine with making `NotImplementedException` extend `SQLFeatureNotSupportedException` if that improves the driver's compatibility with real applications.
