### ISSUE TITLE
Support NULLs as valid values in `value IN (%subquery%)` 

### ISSUE THREAD

**Issue by ArturGajowy** [prestodb/presto#6991]
Follow up for #6622.

Currently we disallow NULLs on probe side of `HashSemiJoinOperator` because it's impossible to distinguish between an empty and non-empty build side in the operator and thus to return a correct result for `NULL in <empty subquery>`. 

The challenges around the fix and fix proposals are described in #6622. One additional fix/incremental improvement approach - as proposed by @kokosing - is as follows:

since the incorrect NULL result for a `NULL in (%subquery%)` expression only matters outside of a `WHERE` clause (NULLs are treated as FALSE in filters), let's:
 - keep the old implementation of semijoin (returning `(null, null)` for *every* null in probe side) in where-clauses (it's correct there)
 - disallow NULLs on the probe side for other usages of `NULL in (%subquery%)` using a projection with an `ensure_not_null(probe_source)` expression, where `ensure_not_null` signals a NON_SUPPORTED error whenever a null is passed

This way we retain correctness without sacrificing execution ability for `WHERE NULL IN (%subquery%)`

**Comment by petroav** [comment]
This issue is referenced in TPC-DS query 33. I ran the query on master and right after the last commit from this PR https://github.com/prestodb/presto/pull/7792 and it returns wrong results (i.e. 0 rows instead of the expected 100). It may be that something else is going on in the query unrelated to NULL values, I haven't done a deep investigation yet but just wanted to note this down.

cc @cawallin @rschlussel @kokosing @findepi @KBP-TDC

**Comment by petroav** [comment]
Please ignore my comment above and apologies for the false alarm. The problem with the query was the `WHERE ("i_category" IN ('Electronics'))` comparison. `i_category` is of type `CHAR(50)` and so the `Electronics` literal needs extra white space after it so that in total it takes up 50 characters.
