### ISSUE TITLE
Error while selecting data from hive 

### ISSUE THREAD

**Issue by Anwaar26** [prestodb/presto#7047]
I have installed latest version of the presto,0.162 on cluster and tried to access remote hadoop cluster
running HDP 2.3.2 .I am able to get Hive table details , definition etc but while selection data from hive
table using a simple select "Select * from datelist.txt " i am getting below exception 

Query 20170111_081938_00003_ngim9 failed: Could not obtain block: BP-901402627-39.7.48.2-1452839346071:blk_1075628789_1889336 file=/apps/hive/warehouse/date_list/datelist.txt

hive properties file:-
connector.name=hive-hadoop2
hive.metastore.uri=thrift://c2master01.xyz.corp:9083,thrift://c2master02.xyz.corp:9083
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml

config.properties:-

node-scheduler.include-coordinator=true
http-server.http.port=8082
query.max-memory=10GB
query.max-memory-per-node=1GB
discovery-server.enabled=true
discovery.uri=http://prestonodeip:8082

node properties:-

node.id=78e57f91-1b58-4f98-9401-e886498a158a
node.data-dir=/data01/presto/data
node.environment=presto

jvm properties:-

-server
-Xmx8G
-XX:-UseBiasedLocking
-XX:+UseG1GC
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+UseGCOverheadLimit
-XX:OnOutOfMemoryError=kill -9 %p
-DHADOOP_USER_NAME=ud_anasiddiqui

Can somebody point me what more setting needs to be done??

**Comment by akshatnair** [comment]
look like the same issue as https://github.com/prestodb/presto/issues/2467

**Comment by Anwaar26** [comment]
@akshatnair ..yes almost same...but that one was also not resolved?? or is there any solution to that..

**Comment by dain** [comment]
"Could not obtain block" is an error that the HDFS client give us when it believes the data is "offline" because too many data nodes are down (or not responding).  I suggest you look into the HDFS system to validate if the file "/apps/hive/warehouse/date_list/datelist.txt" is available, or of data nodes are falling offline, or if your HDFS client config is incorrect.

**Comment by maffan76** [comment]
Hi Dain,
From the same Presto node and hadoop cluster, when we get the data from Hadoop CLI it works but from Presto it doesn't. we are using the same config files for both.
Any other idea to how to further debug this issue?
Thanks in advance.

**Comment by dain** [comment]
I'd use a debugger and see what is different between the two call paths.  My guess is there is something different about the two setups.  Could be versions of the client jars, or a different timeout, or maybe local read short circuit setup.  Unfortunately, this is one if the things that works for almost everyone, and is something we don't have much influence on.

**Comment by jnehmee** [comment]
hi @dain 

i can see that the path is path=hdfs://XYZHADOOP02/apps/hive/warehouse/date_list/datelist.txt from the error log on presto worker node :

ERROR   SplitRunner-9-46        com.facebook.presto.execution.TaskExecutor      
Error processing Split 20170105_190721_00010_bjpqk.1.0-0 {path=hdfs://XYZHADOOP02/apps/hive/warehouse/date_list/datelist.txt, 
start=0, length=23013, hosts=[c2data002.XYZ.corp, c2data004.XYZ.corp, c2data003.XYZ.corp], database=default, table=date_list, 
forceLocalScheduling=false, partitionName=<UNPARTITIONED>, effectivePredicate=com.facebook.presto.spi.predicate.TupleDomain@1f} 
(start = 1483642757497, wall = 134019 ms, cpu = 0 ms, calls = 1)
: HIVE_CURSOR_ERROR: Could not obtain block: BP-901402627-39.7.48.2-1452839346071:blk_1075628789_1889336 
file=/apps/hive/warehouse/date_list/datelist.txt



 We tested successfully to cat and get the file using same hdfs path that we see in presto workers error log above using hadoop cli 2.7.3 using same user that we set in -DHADOOP_USER_NAME=    in jvm.config :


[user@localhost bin]$ ./hdfs dfs -cat hdfs://XYZHADOOP02/apps/hive/warehouse/date_list/datelist.txt

20180407
20180408
20180409
20180410
20180411
20180412
20180413






NOTE : XXXHADOOP2 is the cluster name  , that’s because we have high available hadoop ( 2 namenodes , one is active namenode c2master01-nn.xyz.corp:8020 and other passive node c2master02-nn.xyz.corp:8020 )
Presto understand that from reading the properties in  hdfs-site.xml



i am not sure what version of hadoop client library presto uses internally , if you can guide on this maybe we can download and install same hadoop version presto is using internally and try to cat or get that file 

thanks ,

jad

**Comment by maffan76** [comment]
Can we reopen the issue? as its being marked closed.

**Comment by jnehmee** [comment]
i forget to mention that  we installed presto on the cluster locally and the hive connector works perfectly  , but when we moved presto to remote cluster we had the above issue

**Comment by maffan76** [comment]
hi @dain 
Any further direction to resolve this issue?

Thanks in advance.

**Comment by dain** [comment]
Did you try the hadoop command line from those machines?  If that doesn't work, something is not configured correctly in you `*-site.xml` files, or you networks setup (e.g. firewalls, vlan, vpc, etc.).  If it does work, I'd configure Presto to use you exact site xml files by following these instructions: https://prestodb.io/docs/current/connector/hive.html#hdfs-configuration

**Comment by cawallin** [comment]
Fixed by https://github.com/prestodb/presto/pull/7299
