### ISSUE TITLE
Persto 0.157.1 in EMR is facing issues regarding client side encryption AWS KMS Master Key

### ISSUE THREAD

**Issue by gauravrathi92** [prestodb/presto#7103]
I am getting NULL values in all the rows in result set in presto client in using s3 partitions.

1. Data is stored in the S3 in the encripted form(client side encription) using AWS KMS master key. 
2. EMR Hive is able to decrypt the S3 data on select query.
3. We have done below listed settings in the Presto.hive.properties but it is returning null values(screenshot is attached) against all the rows on making select [query.]

![hive properties](https://cloud.githubusercontent.com/assets/25175199/22021427/3d40e42c-dce3-11e6-9f3b-1c9a555821ee.jpg)
![prestoqueryresult](https://cloud.githubusercontent.com/assets/25175199/22021559/04f550a2-dce4-11e6-83d9-1c91ccd9d918.jpg)

Your help will be really appreciable.
Gaurav

**Comment by ArturGajowy** [comment]
@gauravrathi92 I'm not sure if you noticed, but you've just shown the world your s3 access and secret keys. You probably should change them ASAP.

**Comment by ArturGajowy** [comment]
Also, for the future, text description is preferred to images when filing issues.

**Comment by gauravrathi92** [comment]
Thanks for your advice.

But I have listed the dummy credentials.
These will not work.

I have listed them for exact reference.

Waiting for the assistance on the issue.

Thanks

Gaurav

**Comment by maciejgrzybek** [comment]
All right, then I'm restoring those screen shots.

**Comment by gauravrathi92** [comment]
Thanks

**Comment by gauravrathi92** [comment]
Hello everyone,

Any update on this ?

**Comment by electrum** [comment]
What file format are you using? Does it work against an unencrypted table?

**Comment by RothA** [comment]
@gauravrathi92 what file format are the files you are working with on S3?  

I have been working through issues with parquet files that are stored on S3 with KMS client-side encryption.   Everything on EMR except for Presto uses the EMRFS for dealing with files on S3 which is why in both of our cases Hive works with the files as expected.  Presto instead uses the PrestoS3FileSystem which is where the problem seems to lie.

Here are a few items I have found so far:

1. It seems like there is a bug in the PrestoS3FileSystem that is using the encrypted file length instead of the decrypted file length when attempting to process the decrypted parquet data.  In my case it is showing up as a generic 'Hive split', EOF exception.

```
2017-02-10T18:35:23.715Z	ERROR	remote-task-callback-32	com.facebook.presto.execution.StageStateMachine	Stage 20170210_183521_00052_8ihnz.1 failed
com.facebook.presto.spi.PrestoException: Error opening Hive split s3://bucket/testfiles/part-r-00000-01de6598-2267-408b-a9de-312dffb2c0dd.gz.parquet (offset=0, length=40090): null
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:385)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:157)
	at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createRecordCursor(ParquetRecordCursorProvider.java:92)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:155)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:87)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:244)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at parquet.bytes.BytesUtils.readIntLittleEndian(BytesUtils.java:71)
	at parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:418)
	at parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:385)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.lambda$createParquetRecordReader$0(ParquetHiveRecordCursor.java:332)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:76)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:332)
	... 15 more
```

2. A workaround is to set the 'x-amz-unencrypted-content-length' metadata field on the S3 file to the actual size of the file.  In my case, the size of the encrypted S3 data was 40,090 bytes while the decrypted data was 40,945 bytes.  Once setting the metadata field to 40,945 this started to work.  Similar issue found here: http://stackoverflow.com/questions/40575972/presto-failing-to-query-hive-table

This is not really a good workaround for us as these files are written to S3 during our data warehousing process which uses Spark and EMRFS.

I am digging into the Presto code now to see if I can see if there is a fix that can be made to process with the proper data length once decrypted and will update here on what I find out.

**Comment by gauravrathi92** [comment]
Hi,

The file format which i used in S3 was the simple one just csv and hive is used to create meta data for the data stored in S3 files.

That is table is created in hive specifying the details of raw data in S3 and on that presto is used to compute the data.

**Comment by gauravrathi92** [comment]
@electrum 

yes it works with unencrypted table.

problem is only with encrypted one as presto shows NULL data while making query.

**Comment by RothA** [comment]
@gauravrathi92 if you have the unencrypted file size can you see if setting the 'x-amz-unencrypted-content-length' metadata field on the encrypted S3 file allows it work?  If it does, in my mind that still points to how the PrestoS3FileSystem.getObjectSize() method works.  The issue will probably manifest itself in different ways depending on the file type and the corresponding code that processes it.

**Comment by gauravrathi92** [comment]
@ RothA 
did not get you where to specify the property ?
Are you talking about AWS S3 console or the java code which uploads the encrypted file to S3.

**Comment by RothA** [comment]
@gauravrathi92 sorry I meant manually setting the property on the S3 file via the AWS S3 console

**Comment by RothA** [comment]
I have been able to do a first pass at a fix but have not had the time to fully test it so it could be submitted.  Been running this on a testing patched EMR cluster with Presto and have not experienced any issues yet. I am sure it could be optimized as well as it performs slightly slower than when you have the correct S3 'x-amz-unencrypted-content-length' metadata set, which makes sense. 

The issue is with the PrestoS3FileSystem.getObjectSize() function.  Here is my first pass at a fix you can try:

```
private long getObjectSize(ObjectMetadata metadata, Path path) throws IOException
{
        String length = metadata.getUserMetadata().get(UNENCRYPTED_CONTENT_LENGTH);

        if (length != null) {
            return Long.parseLong(length);
        }

        // check if file has KMS encryption
        String cryptoAlg = metadata.getUserMetadata().get(CRYPTO_KEYWRAP_ALGORITHM);
        if (cryptoAlg != null && cryptoAlg.equalsIgnoreCase("kms")) {
            // KMS client-side encryption
            long decryptedLength = metadata.getContentLength();
            log.info("KMS Client-side encrypted file, initial length: " + decryptedLength);

            // load file and determine actual length
            FSDataInputStream inputStream = this.open(path);

            // read last 25 bytes of file to help determine length
            int eofOffset = 25;
            long startingPos = (decryptedLength > eofOffset) ? decryptedLength - eofOffset : 0;

            // seek to starting point
            inputStream.seek(startingPos);

            while (inputStream.read() != -1) {
                startingPos++;
            }
            decryptedLength = startingPos;

            log.info("Final file size: " + decryptedLength);
            inputStream.close();
            return decryptedLength;
        }
        else {
            // use content length from S3 request
            return metadata.getContentLength();
        }
}
```

I will work on getting this into a PR as time allows.  I can also send the pre-built presto-hive-0.157.1.jar if anyone wants to give it a try.  

NOTE: On EMR clusters this file lives in '/var/lib/presto/data/plugin/hive-hadoop2/'

**Comment by nezihyigitbasi** [comment]
@RothA @gauravrathi92 how did you guys write these data in the first place? According to the linked aws-sdk-java issue when client side encryption is used the `x-amz-unencrypted-content-length` should be set correctly.

**Comment by RothA** [comment]
@nezihyigitbasi We use EMR Spark clusters for our data warehousing processes and write them to S3 via the EMRFS.  I have also validated in instances where we use the AmazonS3EncryptionClient in other applications that this header does not get set either but our main issue is with the S3 files written via EMRFS.

Example of how we are writing in Spark:

```
dataFrame.write.format("parquet").save(filePath)
```

**Comment by nezihyigitbasi** [comment]
@RothA just curious, can you read the data back if you write with Presto?

**Comment by RothA** [comment]
@nezihyigitbasi I will give it a try today and report back with what I find.

**Comment by nezihyigitbasi** [comment]
@RothA did you have a chance to give this a try?

**Comment by RothA** [comment]
@nezihyigitbasi Is there a way for exporting a data set in a parquet format?  I am not seeing that option just the following: ALIGNED, VERTICAL, CSV, TSV, CSV_HEADER, TSV_HEADER.  I have not attempted reading in other formats but I would hazard to guess encrypted CSVs, etc probably don't fall victim to this same issue since you don't have to read from the end of the file to determine its format.

**Comment by nezihyigitbasi** [comment]
You can't export in parquet format through cli, but you can insert into some table in parquet format and use those files for testing.

**Comment by RothA** [comment]
@nezihyigitbasi It looks like when writing to an external table in parquet format on S3 from Presto, the '	x-amz-meta-x-amz-unencrypted-content-length' metadata gets set properly.  

Example:
```
CREATE EXTERNAL TABLE kms_test (
id BIGINT,
key STRING,
value STRING
)
STORED AS PARQUET
LOCATION 's3://testbucket/kms_test';
```

Inserted data:

```
insert into kms_test VALUES (1, 'key1','value1');
insert into kms_test VALUES (2, 'key2','value2');
```

This resulted in 2 files written to S3 in the s3://testbucket/kms_test folder with the following metadata properties being set: Content-Type, x-amz-meta-x-amz-cek-alg, x-amz-meta-x-amz-iv, x-amz-meta-x-amz-key-v2, x-amz-meta-x-amz-matdesc, x-amz-meta-x-amz-wrap-alg, **x-amz-meta-x-amz-unencrypted-content-length**.    This last property being the only difference between the files written with Presto and those written via EMRFS.

**Comment by nezihyigitbasi** [comment]
We had a chat with the EMR people to understand how Hive/Spark is able to read encrypted files when the `x-amz-unencrypted-content-length` is not set. The outcome is, EMR Hive/Spark reads the entire file in those cases to determine the unencrypted content length, which is something that we don't really want to do.

For now the workaround is to fix/rewrite the files on S3 with the proper metadata header set. And the actual fix should be done in the EMR filesystem as it's not populating the `x-amz-unencrypted-content-length` header properly.
