### ISSUE TITLE
Incorrect results due to improper implicit coercion

### ISSUE THREAD

**Issue by martint** [prestodb/presto#7142]
This query:

```sql
SELECT 1 x
```

produces:

```
 x
---
 1
(1 row)
```

```
 - Output[x] => [expr:integer]
         x := expr
     - Project[] => [expr:integer]
             expr := 1
         - LocalExchange[ROUND_ROBIN] () =>
             - Values => []
                     ()
```

However, the following query produces a different result:

```sql
SELECT 1 x
ORDER BY degrees(x)
```

```
  x
-----
 1.0
(1 row)
```

```
 - Output[x] => [expr:double]
         x := expr
     - Project[] => [expr:double]
         - Sort[degrees ASC_NULLS_LAST] => [degrees:double, expr:double]
             - LocalExchange[SINGLE] () => degrees:double, expr:double
                 - Project[] => [degrees:double, expr:double]
                         degrees := 57.29577951308232
                         expr := 1.0
                     - LocalExchange[ROUND_ROBIN] () =>
                         - Values => []
                                 ()
```

I believe the issue is that the presence of the `degrees(x)` call in the `ORDER BY` clause causes the type inferencer to decide that `x` needs to be coerced to `double` to satisfy the call, and it incorrectly applies the coercion to the `x` field in the `SELECT` clause.

**Comment by martint** [comment]
It's due to the rewrite that happens during analysis of the `ORDER BY` clause (OrderByExpressionRewriter), where it inlines references to expressions in the `SELECT` clause by replacing them with references to those expressions. Since coercions are associated with nodes by identity, this causes the field in the `SELECT` expressions to inherit whatever coercions were applied in the `ORDER BY` clause.

**Comment by martint** [comment]
cc @sopel39

**Comment by sopel39** [comment]
I think the proper fix to that (instead of cloning expression tree) can be implemented in following steps:
1. Add `QueryOrderBy` node so that new `Scope` can be added to `Analysis` that is specific for ORDER BY expressions. Such scope would resolve against output symbols first and then against parent scope.
2. Support `QueryOrderBy` scope in planner
3. Fix `StatementAnalyzer` analysis for aggregations and window ORDER BY expressions

I'm working on this solution

Short fix could be clone expression tree through serializing.

**Comment by martint** [comment]
Yes, I think that's the way to go. I was thinking of something along those lines, too.
