### ISSUE TITLE
Leaked system memory reservation in ExchangeOperator

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#7278]
`ExchangeOperator` calls `pipelineContext.reserveSystemMemory`, but appears to leak this reservation under some circumstances. It looks like this was introduced by 64c3fc8b027f598d63fd13e4d8e0b91b77d7d012

Generally, `Operator`s should use `OperatorContext.reserveSystemMemory` not `PipelineContext.reserveSystemMemory`

To reproduce run `TestMemoryManager.testClusterPools` with an invocation count of at least 100

**Comment by dain** [comment]
I'm pretty sure I have found this one also.  The root problem is `ExchangeClient.postProcessPage` method only frees memory if the `closed` flag is not set.  This is because the `close` method clears the memory allocation, so we need to prevent going "negative".  To make it more complex, there are a few places that set `closed` directly without calling the `close` method, and 64c3fc8b027f598d63fd13e4d8e0b91b77d7d012 this to the `close` method:
``` java
if (!closed.compareAndSet(false, true)) {
    return;
}
```
So when closed is set directly from one of the other callers, the memory is not freed by `close` or in `postProcessPage`.

I'll fix this as part of the async statement client work.

**Comment by raghavsethi** [comment]
Ah I see, thanks!
