### ISSUE TITLE
Add support for LZO text files to Hive connector

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#7348]
We have an Apache licensed LZO library: https://github.com/airlift/aircompressor/tree/master/src/main/java/io/airlift/compress/lzo

The `LzoCodec` implements the Hadoop `CompressionCodec` interface. We need to figure out how to write it up and add tests.

**Comment by csliu** [comment]
We had some Text format tables and it's lzo compressed, but Presto treats them as pure non-compressed text file and returns malformed results.

Hope this can fix it.

**Comment by Yaliang** [comment]
Is it possible to refactor the ``AircompressorCodecFactory`` and ``HadoopCodecFactory`` in ``presto-rcfile`` module and move them to ``presto-hive`` as a standard way to find the Codec?

**Comment by dain** [comment]
@Yaliang I don't think so.  The presto-rcfile write works because we "own" the reader code and can modify the compression loading code to favor Airlift compressors over Hadoop compressors.  With other file reader implementations the compression code is loaded by Java class name, and there is really no way to hook into that process.  

What we are going to do for text files add the Airlift LZO and LZOP codecs as the default handler for the `.lzo` and `.lzo_deflate` extensions.  This work is in this PR https://github.com/prestodb/presto/pull/7588, which is dependent on this PR in Airlift https://github.com/airlift/aircompressor/pull/61

**Comment by Yaliang** [comment]
Yep, looks like #7588 will be good for text files but I was initially thinking the pattern of {{AircompressorCodecFactory}} and {{HadoopCodecFactory}} in {{presto-rcfile}} could be preferred for all "owned" readers in {{presto-hive}}. We currently have {{ParquetCompressionUtils}} for the optimized parquet reader, {{OrcDecompressor}} for the orc reader and {{RcFileCodecFactory}} for the rcfile reader. Is there any chance to move them all to one place?
