### ISSUE TITLE
"No nodes available to run query" on EMR using presto-mysql-connector

### ISSUE THREAD

**Issue by daiduongbian44** [prestodb/presto#7432]
Hi all,
I'm setting up EMR with **1 Master node, 2 Core nodes**. When using **presto-mysql-connector** plugin, i queried data on presto which connect to the table on Mysql and it is fail.
`select * from mysql.test_database.test_table;`
error occured:
`Query 20170223_030610_00007_7qfpk failed: No nodes available to run query`
But if i using EMR with **only 1 Master node**, the result of query is ok.
Hope have some advice from you.
Thanks all.

**Comment by cawallin** [comment]
Make sure that your mysql.properties file is on all of the Presto nodes, not just the coordinator.

**Comment by electrum** [comment]
Presto has a config property `node-scheduler.include-coordinator` that means whether or not the coordinator can perform work. EMR likely sets this to `true` with a single master node (otherwise it wouldn't work at all) and `false` if you have additional nodes. This explains why it works in one case but not the other, assuming the `mysql.properties` file is only on the master node as @cawallin guessed.

Please reopen the issue if you need more assistance.
