### ISSUE TITLE
 json_extract skip/truncate the value

### ISSUE THREAD

**Issue by sivankumar86** [prestodb/presto#7439]
Below query returns one value i.e it gets truncated after che
```
SELECT json_extract('["lab: \"che,phy\""]', '$[0]')
```

output 
```
lab: ""che
```

expected 
```
lab: "che,phy"
```

**Comment by findepi** [comment]
@sivankumar86, please make sure your query is _displayed_ here as you expected. Please wrap the query with triple back ticks (e.g. \`\`\` select .... \`\`\`) to prevent GH from tampering with single/double quotes and backslashes in your query.

**Comment by electrum** [comment]
I edited the issue to add code formatting: https://guides.github.com/features/mastering-markdown/

Your example seems to work as expected:

```
presto> SELECT json_extract('["lab: \"che,phy\""]', '$[0]');
       _col0        
--------------------
 "lab: \"che,phy\"" 
(1 row)
```

Note that the output is surrounded by JSON quotes, because `json_extract` returns the result as a JSON string. You probably want to use `json_extract_scalar`:

```
presto> SELECT json_extract_scalar('["lab: \"che,phy\""]', '$[0]');
     _col0      
----------------
 lab: "che,phy" 
(1 row)
```

**Comment by electrum** [comment]
I'm going to close the issue because the function seems to be working as expected. Please re-open if you find another example.
