### ISSUE TITLE
Wrong documentation for "9.1. Migrating From Hive - Outer Join Differences"

### ISSUE THREAD

**Issue by dmarkovitz** [prestodb/presto#7547]
https://prestodb.io/docs/current/migration/from-hive.html

Hive logically implements LEFT JOIN the same as presto (see demo below).
Changing the syntax as suggested will return undesired results. 
This whole "Outer Join Differences" section should be omitted from the documentation.

Demo
--------

You can see that t1 was *not* filtered previous to the JOIN.

>hive select * from (select 1 as n union all select 2 as n) t1 left join (select 1 as n union all select 2 as n) t2 on t1.n=t2.n and t1.n=1;
...
OK
1       1
2       NULL

**Comment by wenleix** [comment]
Some earlier version of Hive does have this legacy behavior. Thus I suggest retain this in the document with some extra notes (e.g. newer version of Hive might already follows the ANSI SQL Join behavior).

**Comment by electrum** [comment]
We should delete this section since this has been fixed in Hive for many years.

**Comment by electrum** [comment]
This was fixed in 0.7.0 by [HIVE-1534](https://issues.apache.org/jira/browse/HIVE-1534) which was released March 29, 2011 (about 18 months before we wrote the first line of code for Presto).

**Comment by haozhun** [comment]
But there's also a flag that Hive users can use to resurrect the legacy behavior. Are such users a majority or minority?

**Comment by rschlussel** [comment]
They got rid of the flag altogether in 2.2.0 https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-hive.outerjoin.supports.filters  so presumably the legacy behavior is not that important anymore.

**Comment by findepi** [comment]
> They got rid of the flag altogether in 2.2.0 

I'm not sure if i understand correctly, but it seems, if you use latest CDH release (5.10), you get Hive ~1.1.0 (https://www.cloudera.com/documentation/enterprise/release-notes/topics/cdh_vd_cdh_package_tarball_510.html#tarball_510x).

**Comment by nezihyigitbasi** [comment]
I also vote for removing this section since

- it has been fixed a long time ago (don't know whether anyone uses v 0.7 or older except FB)
- this behavior is not default (a user has to explicitly enable it to get different results than Presto)
- there are other configs that may cause Hive to behave differently than Presto, do we want to document them all? For example, `hive.exec.dynamic.partition` was `false` by default until `0.9`, but now it's `true` by default (like Presto). One may ask why we are only documenting this difference only.
