### ISSUE TITLE
Optimize Sorts That Don't Effect Results

### ISSUE THREAD

**Issue by cosinequanon** [prestodb/presto#7613]
Simple example that isn't being optimized
```
select count(1)
from (
  select x
  from ( values 4, 2, 1, 3 ) as t(x)
  order by 1
)
```
Query plan is
```
                               Query Plan
-------------------------------------------------------------------------
 - Output[_col0] => [count:bigint]
         _col0 := count
     - Aggregate(FINAL) => [count:bigint]
             count := "count"("count_10")
         - LocalExchange[SINGLE] () => count_10:bigint
             - Aggregate(PARTIAL) => [count_10:bigint]
                     count_10 := "count"(*)
                 - Project[] => []
                     - LocalExchange[ROUND_ROBIN] () => field:integer
                         - Sort[field ASC_NULLS_LAST] => [field:integer]
                             - Values => [field:integer]
                                     (4)
                                     (2)
                                     (1)
                                     (3)

(1 row)
```
In theory there shouldn't be a sort step since that doesn't effect the end result

**Comment by dain** [comment]
We should prioritize this now that we have distributed sorts, sorting can use a huge amount of resources.

**Comment by kokosing** [comment]
@atris Would you like to take a look into this?

**Comment by atris** [comment]
Ack, I will look into this

**Comment by dain** [comment]
BTW, we already have `isOrderSensitive` in local properties (https://github.com/prestodb/presto/blob/master/presto-spi/src/main/java/com/facebook/presto/spi/LocalProperty.java#L39), so I hope 2 is pretty straight forward.  For aggregates, if the user need sorting, they must add the ORDER BY clause to the aggregation invocation (https://prestodb.io/docs/current/functions/aggregate.html), and IIRC there is already an optimizer that removes unnecessary ones (or the execution just ignores it).
=

**Comment by martint** [comment]
isOrderSensitive describes a quality of a given type of local property, not of whether a relational expression (plan node) is order sensitive.

I think the biggest challenge (which might require introducing new concepts) is how to know whether a SortNode was the result of an ORDER BY clause in the original SQL query or whether it was introduced as a by-product of some optimization. For instance, one strategy for implementing a global aggregate such as ARRAY_AGG(x ORDER BY y) could be to do a sort followed by an aggregation. The same could apply to window functions that have ORDER BY clauses.

We may be able to add some short-term "hack" to support this, but generally, we may need to extend the rule-based optimizer with the ability to express requirements/preferences, or the full-blown cascades style optimizer with top-down optimization goals that include required/preferred properties.

**Comment by dain** [comment]
When I added the first version of "order sensitive", it was to determine if I could "mess up" the ordering of a plan node by adding a local exchange.  The specific problem I ran into was my optimizer would add a local exchange before output output node and would cause the expected sorted output to the end user to be randomized.

I get your point about `ARRAY_AGG`.  I have two thoughts. 1) we don't do that today, so we can delay fixing this until someone implement that optimizer. 2) The easiest way to implement this would be to keep a record in the aggregation node that the aggregate is "order sensitive", and then report that during property derivation.

I didn't follow the point about "extending the rule-based optimizer", but I don't think it matters since I believe my comments would fall into your "short-term hack" category :)

**Comment by martint** [comment]
> When I added the first version of "order sensitive", it was to determine if I could "mess up" the ordering of a plan node by adding a local exchange.

Well, in that case, that's an abstraction we need to fix, since it doesn't belong there. That should be modeled as a property requirement (e.g., output needs to be sorted due to query shape) and an evaluation of whether the properties produced by a given subplan satisfy those properties.

In any case, LocalProperties are for reasoning about within stream properties, but for this we need to reason about global properties, which don't support modeling sortedness.

> The easiest way to implement this would be to keep a record in the aggregation node that the aggregate is "order sensitive", and then report that during property derivation.

The rule-based optimizer cannot reason about properties, yet -- that's all within Add*Exchanges, unfortunately.

**Comment by kokosing** [comment]
@martint Is this yet another place where we hit the lack of `traits`?

**Comment by atris** [comment]
@martint @kokosing I was tending to do what @dain said, adding a property in Aggregation to mark if it is order sensitive. However, I agree that lacking traits and the ability to define specific properties and have them considered during later stages of planning is something that we need to address, maybe now.

Could we add a traits member in the Plan context, and have the CBO add it as a cost factor when comparing between two plans?

**Comment by dain** [comment]
I don't think we have an optimizer that makes aggregation (or window) order sensitive yet.  cc @martint

**Comment by atris** [comment]
@kokosing @martint @dain What would be a good starting point for getting traits implemented? I think we should start with having aggregates that are aware of the needed sorting order. This would allow removing redundant sorts as I mentioned earlier.

The second step would be to abstract out the logic in AddExchanges into a generic Validate* class and have Iterative Optimizer and Rule Based Optimizer call into it foreach node being visited. That would allow the optimizer to have visibility into each of the nodes's requested traits.

Let me know your thoughts
