### ISSUE TITLE
Paging Mechanism?

### ISSUE THREAD

**Issue by nt3478** [prestodb/presto#7636]
Hey All 

Does presto have any mechanism to enable paging of results (ex: OFFSET/FETCH NEXT) or something similar?

Thanks!

**Comment by electrum** [comment]
No, these constructs are very expensive, since we have to execute the query every time and throw away most of the results. Even worse is that for analytic data sources, for which Presto is designed, queries often involve a full table scan or otherwise access much more data than in an OLTP system.

This should be handled in the application by executing the query once, caching the results, then doing pagination over the cached results.
