### ISSUE TITLE
Failed Queries - S3 404 Not Found Exception

### ISSUE THREAD

**Issue by bdm123** [prestodb/presto#7807]
Hi Everyone - I am running a variety of scheduled INSERT/SELECT queries against S3 and fairly frequently have many queries failing at once.  Below are the errors I see in the server.log file which seem to correlate with the failed tasks.  Any ideas on the cause or suggestions on how to resolve this?

`INFO    20170411_164451_00741_gfn2r.1.6-0-27760 com.amazonaws.latency   ServiceName=[Amazon S3], AWSErrorCode=[404 Not Found], StatusCode=[404], ServiceEndpoint=[http://bucket.s3.amazonaws.com], Exception=[com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 2DA64F214FC845CB), S3 Extended Request ID: nDSDGr7dvLVDZMBDInnDlWRa1Z9XhK4RQ5cKYpjOuvIzLKKP8CTNhckLv4wuZT+0FKuUvdrg4/Y=], AWSRequestID=[2DA64F214FC845CB], HttpClientPoolPendingCount=0, HttpClientPoolAvailableCount=0, RequestCount=1, Exception=1, HttpClientPoolLeasedCount=13, ClientExecuteTime=[30.105], HttpClientSendRequestTime=[0.035], HttpRequestTime=[29.759], RequestSigningTime=[0.123], HttpClientReceiveResponseTime=[28.525],`

Thanks

**Comment by nezihyigitbasi** [comment]
First, it would be nice to see the entire stack trace, and to know the Presto version you are using.

If you think files should be there, then it's probably due to S3 eventual consistency. Sometimes due to eventual consistency Presto gets an object from the result of an S3 list call, but that object isn't available in S3 data nodes, causing 404s (as the replicas may not have been fully updated, read more [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel)).

Unfortunately, there is no good solution as this is the way the storage system, S3, is designed, the only option is to wait for the replicas to be synced. Usually this shouldn't take much (I have seen extreme cases though where it can take a good amount of time).

**Comment by electrum** [comment]
Is eventual consistency still a problem for S3?

> Amazon S3 provides read-after-write consistency for PUTS of new objects in your S3 bucket in all regions with one caveat. The caveat is that if you make a HEAD or GET request to the key name (to find if the object exists) before creating the object, Amazon S3 provides eventual consistency for read-after-write.

http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel

Do we ever check if a file exists before writing it? If so, we could be causing this problem for ourself.

**Comment by fsck-mount** [comment]
@nezihyigitbasi Can we have config to suppress this kind of errors while reading ? I'm reading from s3 parquet files. I'm getting these errors sometimes more often. 

Can we have config to skip these kind of errors while reading ? so that it will skip the file if not found?

**Comment by nezihyigitbasi** [comment]
If your files do exist and you get a 404 then it's very likely that it's an eventual consistency issue, and the reason it gets triggered is usually due to insert overwrite/update type of writes. So avoiding this type of writes will help reduce the 404s you get. 

In general, I don't think it's a good idea to skip files on 404 as this can hide legit problems (e.g., we cannot differentiate whether it's an eventual consistency issue and the file exists OR the file doesn't really exist).

**Comment by fsck-mount** [comment]
Most of the cases, 404 will throw when the file is deleted. Overwriting will not cause 404 error. So, having a config (hive.s3.skip-file-not-found) to skip s3 404 errors will be safe and good to ignore this error. You are correct, this is due to eventual consistency issue.

**Comment by nezihyigitbasi** [comment]
>> Overwriting will not cause 404 error.

If you look at Amazon's docs [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel):
"Amazon S3 offers eventual consistency for overwrite PUTS and DELETES in all regions." 

So, overwrites are subject to eventual consistency and with that it's possible to get 404s.

My concern regarding the config option is still valid I think: we cannot differentiate whether 404 is due to eventual consistency and the file exists **OR** the file doesn't really exist (a legit 404, say, for example due to a bug somewhere in my system). So, I am not really in favor of adding such a config option. I don't know what your end-to-end pipeline/process does, but once you delete the data on S3 it would be good to make sure that you don't attempt to read it with Presto.

For us to propose some solutions it would be nice if you can send an email to the Presto user group and give more details.

**Comment by fsck-mount** [comment]
@nezihyigitbasi , I verified, overwrite will give inconsistent data, in one request data from old file and in another it will be from new file. But it will not say file is not there ever. Yes overwrite is also eventual consistent. But it will not resolve to 404. It resolves to inconsistent data which causes presto parquet file magic number error or wrong offsets. 

My purpose is simple ([may be not really](https://groups.google.com/forum/#!topic/presto-users/rqdDUlcLCnc)), i'm converting all the json files on disk to parquet files on s3. Sometime the might come late and store it in old files. At that time, convert the file and update to s3 with newer version say (actual file is file1.parquet, now the file will become file2.parquet) and then deletes file1.parquet from s3. 

This is causing the issue. So, my intention behind suggesting a config is, However the file is not present, so when we know that file is not presented, it's deleted, we can get the data from that file. Then why stopping the query, let's continue without that file and at the end, if possible show it as warnings like mysql may be (With little knowledge I have, we don't have warnings as of now, but i'm just suggesting)?

**Comment by nezihyigitbasi** [comment]
@alinadonisa Does this issue look similar to the issue you are observing: https://github.com/prestodb/presto/issues/11587
