### ISSUE TITLE
Add reduce_agg function for lambda

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#7814]
You may be able to find some past discussions about it here: https://github.com/prestodb/presto/pull/6198

**Comment by wenleix** [comment]
As first step, we don't want to support capture for now since it adds a lot of complexity.

There are two problems we need to solve: 
- Provide some sort of support for "group invariants". We can just support constant expression for now. 

- Some way to communicate the lambda expression from coordinator to worker when broadcasting the query plan. One thought is:
  - Broadcast some kind of "typed canonical form of Lambda Expression" and encode it into the query plan (like what we did for MAGIC_LITERAL)

**Comment by wenleix** [comment]
Test Case:
```
select x, reduce_agg(y, 1, (t,s)->t*s, (s1,s2)->s1*s2, s->s) 
from (values (1,1), (1,2), (2,3)) as t(x,y) 
group by x;
```
