### ISSUE TITLE
Redshift through Postgresql connector no longer functions

### ISSUE THREAD

**Issue by jgticketscript2** [prestodb/presto#8011]
On version 0.173 I was able to use the Postgresql connector to connect to a Redshift cluster. Since version 0.174 the Postgresql connector is no longer compatible. Also tested it on 0.175, same error. The full stacktrace can be found in the pastebin at the bottom of this issue.

The error is `com.facebook.presto.spi.PrestoException: ERROR: type "e" does not exist`

I suspect this may relate to [Postgresql string constants](https://www.postgresql.org/docs/8.2/static/sql-syntax-lexical.html).

[Pastebin](https://pastebin.com/0DsKZb08)

**Comment by toyama-h** [comment]
My company has also encountered this problem....

**Comment by samdjohnson** [comment]
Me too

**Comment by electrum** [comment]
I believe this is due to Presto updating the version of the PostgreSQL JDBC driver that we ship. Does anyone know the most recent version of the driver that is compatible for Redshift? We could revert to that version or have a separate Redshift connector that uses the last-working version.

We were previously using version `9.3-1102-jdbc41` of the driver, but that version is rather old, so it would be helpful to know the most recent version that can be used.

Separately, I have contacted Amazon and asked about an open source friendly license for the official Redshift JDBC driver, as the existing license would not allow Presto to ship it.

**Comment by jgticketscript2** [comment]
Thanks electrum, looking forward to hearing Amazon's response.

**Comment by aliavni** [comment]
Same here

**Comment by BigDataDaddy** [comment]
Electrum,  I just recently spoke to the AWS EMR GM on this issue at the AWS Summit in NYC.  They are aware of the breaking change in the Presto PostgreSQL connector at Presto 0.174 when using it to connect to AWS Redshift.  They are concerned and are seeking solutions.  EMR's most recent release (EMR 5.8.0) deploys Presto 0.170 and they are stuck there (or under 0.174) until there's a solution for Redshift.  Is there anything I can do as an AWS EMR and Redshift customer to help coordinate getting Presto a Redshift JDBC driver redistribution license or another solution that supports Redshift past 0.174?

**Comment by dswalter** [comment]
I wish the register that I have the same concerns as everyone else here. Is there a chance this is not being supported because it conflicts with AWS's Redshift Spectrum and Athena products? That would be a disappointing development.

**Comment by electrum** [comment]
It unintentionally broke when I upgraded the PostgreSQL JDBC driver. I’ll get it fixed for the next Presto release (0.186).

**Comment by electrum** [comment]
Presto 0.186 has a Redshift connector: https://prestodb.io/docs/current/connector/redshift.html

**Comment by dswalter** [comment]
Thanks immensely, @electrum! Presto is a fantastic tool.

**Comment by BigDataDaddy** [comment]
@electrum Many thanks for finally adding a Redshift connector!

... now we just have to wait for AWS EMR to pick up Presto 0.186+.  

In an unfortunate series of events EMR 2 weeks back released EMR 5.9.0 with Presto 0.184, oh so close...
