### ISSUE TITLE
Do not keep correlated symbols as SymbolReferences

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#8459]
Take a look at the below query:

`SELECT a, (SELECT a WHERE false) FROM (VALUES 1) t(a)`

Output of it should be: `1, null`.

Currently all the correlated symbols are stored in subquery plan as `SymbolReference`, this causes:
 - difficulties in understanding of subquery plan as most symbols are produced by children nodes or assignment expressions, but some come from the correlation and require special handling SIC!. Take a look at: https://github.com/prestodb/presto/issues/8451
 - issues with symbol equivalence solving. Typically when correlation is added to subquery is wrapped in `Projection` assignment like `expr -> a`, then at some point `UnaliasSymboReferences` maps `expr -> a` and keep symbol reference equivalence that expr = a, then in every place where `expr` occurs `a` is inlined. At the end, there is no way to distinguish output of correlated subquery from correlation symbols (see above query). This relates to: https://github.com/prestodb/presto/pull/8435

CC @martint @sopel39

**Comment by sopel39** [comment]
I see two issues there:
1. Correlated symbols are used in different plan subtrees even though they are not the same instance at the end (after `ApplyNode` and `LateralNode` are resolved). `UnaliasSymboReferences` doesn't correctly work with such plan (see: https://github.com/prestodb/presto/issues/8471), but there might also be problems with `PredicatePushdown`
2. Correlated symbols don't have sources. They "appear" in a middle of a plan out of nowhere. Therefore special correlation handling leaks to unrelated optimizers (e.g: `InlineProjections`)

I think we need to address both issues. Here is the proposal:
1. `ApplyNode#correlation` and `LateralJoinNode#correlation` shouldn't be a list of symbols, but rather a mapping between input (left) symbols and correlated (right) symbols. This way we are sure that same symbol won't occur in different subtrees.
2. We should have a special plan node, e.g: `ProjectCorrelation` that would pass-through input symbols, but also produce correlations. Such node correctly provide correlated symbols to downstream nodes. This way we don't have to special correlations handle in other optimizers.

**Comment by alandpost** [comment]
Rather than a whole new node, would a new row function be sufficient, taking the (constant) name of the correlated symbol as the argument?  The only problem I can see with the row function approach is that it would require special handling in any constant-folding optimization we have or might write in the future.

**Comment by sopel39** [comment]
I prefer node approach since it explicitly binds all correlations into single node and we can assume that there are no more usages of correlated symbol `x` below the `ProjectCorrelations` that produces it (we can push up `ProjectCorrelations` when we decorrelate subquery). Additionally, in the future, we might think of unwinding `ProjectCorrelations` into some materialized table (e.g: with correlated rows) consumer that would allow us to support any correlated subquery in a distributed way.

I think that row functions might be harder to reason about and may cause problems when they get aliased (e.g: `x = correlated_symbol("s")`, then you need to know that `x` is actually correlated symbol).

**Comment by kokosing** [comment]
> Rather than a whole new node, would a new row function be sufficient, taking the (constant) name of the correlated symbol as the argument? The only problem I can see with the row function approach is that it would require special handling in any constant-folding optimization we have or might write in the future.

This was my initial thought, though I was going to create a special `CorrelatedSymbolReference` expression.

IMO `ProjectCorrelations` is more clear and sql-algebra-friendly approach. After that node that correlated symbol does not differ with any other symbol in the plan.
