### ISSUE TITLE
HiveSplitManager schema verifier doesn't respect use-column-names

### ISSUE THREAD

**Issue by vincepri** [prestodb/presto#8510]
When using replace columns, instead of adding new columns, Presto on `PARQUET` fails with the following message:
```
There is a mismatch between the table and partition schemas. The types are incompatible and cannot be coerced. The column 'ads_tracking' in table 'analytics.deviceinfo' is declared as type 'boolean', but partition '__dt=1499662800' declared column 'app_build_ver' as type 'string'.
```

It seems that the exception is thrown here https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HiveSplitManager.java#L244-L264 and it seems that this logic is relying on the ordering of the columns and doesn't respect the option `hive.parquet.use-column-names=true`.

Related commit https://github.com/prestodb/presto/commit/9a653165a8be7bbd81d1265eac8f7de72cd2b702  from @geraint0923

**Comment by vinceprignano** [comment]
Any thoughts?

**Comment by hocanint-amzn** [comment]
Hello Vince,
We are looking at the same issue and wanted to get the communities opinion about this validation as well as we are looking to make some tweaks to the code and contribute back.

From my understanding, you can match schemas to whats within data files either by column index, or by column names. Both of these methods can allow for different ways of schema evolution. For reading data by column indexes, you can rename columns, and add columns to the end of the table, and change data types to name a few but you cannot delete columns, or re-arrange columns within the table schema as it would affect column ordering. For reading data by column names, you can delete columns, re-order columns, but you cannot rename columns. 

The validation that is being conducted in the HiveSplitManager seems to ensure that data types of the same columns are compatible between the partition and the table. As you pointed out, it seems to be doing the validation by column index rather that column names, regardless of how columns in data files are read and mapped to columns.

The three things we wanted to do:
1) Change HiveSplitManager to do either index based validation or column name based data type validation  depending on how presto will map data fields in data to table columns read by index or column name. For example, have JSON validation based on column name, but CSV be done by index.
2) Be able to support table properties that determine whether to configure the reader to map data by index vs column name so that people can have the choice how they want their tables to evolve. For example, for Parquet, we would check "parquet.column.index.access" and as I can't find ORC's eqivalent, we could check for "orc.column.index.access". 
3) Change the optimized Parquet and ORC readers to use the table properties.

If the community feels that this is an appropriate, this may be something that we can start working on and contribute back.

**Comment by hocanint-amzn** [comment]
I will be putting in a PR for this change for the changes that I suggested above to get some feedback.

**Comment by ryanrupp** [comment]
@hocanint-amzn I actually stumbled upon this issue while looking into some of the behavior in Athena with Parquet vs ORC. With Parquet it appears `hive.parquet.use-column-names` must be set to true because I can have two Parquet files with a single column but different names and then create that as a table with the two different names and the data maps to two columns as expected. With ORC it appears `hive.orc.use-column-names` must be set to false because it will treat those two seperate files as just one column. Having the ability to toggle this on at the table level would be useful as we're looking to keep column names immutable (we end up mapping to user friendly names elsewhere so the ability to change the name isn't too useful for us) but allow columns to be added without having to coordinate the order of columns on the write side when generating ORC files.

**Comment by f355** [comment]
Hey @vincepri, you've closed the issue - does that mean there is a fix available, or you just don't care about it anymore? We're facing the same thing, and it would be nice to have a solution.

**Comment by dain** [comment]
There are two levels of mapping in Hive. Table to partition and partition to file.  The `hive.parquet.use-column-names` and `hive.orc.use-column-names` properties effect the second mapping (partition to file).   It does not look like there is any Presto configuration to change table to partition mapping to name based.  Is that a feature Hive supports?  If so, can you point us at the documentation or code for this?

**Comment by f355** [comment]
Thanks for reopening this, @dain. Not having name-based mapping on the first level really hinders the schema evolution possibilities.

We're not using Hive, we rely on AWS Glue to provide the metastore backend, so I can't really say anything about it. But as far as I understand Presto architecture, only Hive metastore is being used, the rest is reimplemented, so mimicking Hive 100% doesn't seem necessary.

The relevant code in the current master seems to be here: https://github.com/prestodb/presto/blob/57c70aee95fe6c00666f13ba5dc2f930fae87d84/presto-hive/src/main/java/com/facebook/presto/hive/HiveSplitManager.java#L310

**Comment by findepi** [comment]
When taking to Hive Metastore we follow Hive's behavior because this is our "reference implementation" as far as what should be supported/allowed is concerned.

When we talk to AWS Glue (purposefully or conveniently reusing Hive connector's infrastructure?), what should be our "reference implementation"? Or maybe Glue has some docs that specify how table and partition schema mismatch should be reconciled during read?
If there is no sufficient documentation, we can
1. live without RI and implement what we think reasonable ourselves
2. take EMR (so AWS Hive) as RI
3. take Glue ETL jobs as RI (no idea how they are implemented; maybe they map to EMR again)
4. ...?

cc @ilfrin

**Comment by f355** [comment]
AWS has their own Presto fork(?), Athena. Here's how it handles schema evolution:
https://docs.aws.amazon.com/athena/latest/ug/handling-schema-updates-chapter.html
https://docs.aws.amazon.com/athena/latest/ug/updates-and-partitions.html

**Comment by dain** [comment]
@findepi according to the second link above (https://docs.aws.amazon.com/athena/latest/ug/updates-and-partitions.html) Athena applies the name-based matching property to the table to partition mapping.  I'm like to know if this is just a Athena/Glue thing or a general Hive thing we got wrong.  Either way, I believe Presto should preform the same as Hive in these environments.

**Comment by hocanint-amzn** [comment]
@dain, @f355, @findepi
Sorry for the long delay in responding. It is true that Athena does perform name matching instead of index matching for readers that read by name (like Parquet, ORC assuming the flags to enable reading by index is not turned on) in the HivePartitionManager. I was planning to provide a patch to share with the OS community but I didn't get around to it yet. Since the amount of time passed quick a bit, I need some time to merge the patch with the latest version of Presto, and get the appropriate approvals before I can provide it. Im hoping that things calm down and I can provide it in mid December.

**Comment by dain** [comment]
@hocanint-amzn can you document the expected behavior here?  Also, if you can note any differences from Hive.  Eventually, we'll need to get this into the full docs.

BTW, assuming this is not what Hive does already,  I'm thinking we may want to consider adding an option for those using a regular Hive metastore.

**Comment by hocanint-amzn** [comment]
@dain I believe the behavior that Hive exhibits is that it uses the partitions schema/properties to read the partition and when the results are merged back to the rest of the table, it will null out anything that cannot be coerced properly. I remember running the exact same queries that would  fail validate in Presto, but would work properly in Hive. 

As sajjoseph mentioned, the validation that we do only validates columns from table against partition by column index only, not by name. Hive does not fail these validations in that case. 

I just received approval to submit a PR. Will submit it shortly.

**Comment by hocanint-amzn** [comment]
I've submitted https://github.com/prestodb/presto/pull/12077 for this change which is similar to the changes that Athena has implemented.

**Comment by wagnermarkd** [comment]
I'm late to the party, but might be able to share some history: Hive is very lenient with SerDes in how they choose to read data. SerDes in Hive receive metadata for both the table and partition to be read and can resolve any differences between the two however they see fit. The final type of rows that will be returned is communicated through the returned ObjectInspector. For example, in the Avro SerDe we always use the schema/metadata from the table and delegate to Avro's schema evolution functionality. In that case, Hive never even sees a difference between the partitions' schemas.

Coincidentally, I made the changes for Orc and the Orc SerDe to switch to using column names for everything: ORC-54. That built on some previous work that introduced this property:
```
 HIVE_SCHEMA_EVOLUTION("hive.exec.schema.evolution", true,
        "Use schema evolution to convert self-describing file format's data to the schema desired by the reader."),
```
If that's enabled, the OrcSerde will pull the "expected" columns from a passed configuration. Those values are always directly from the metastore, so there's an implicit assumption that the SerDe respects the metastore's metadata (i.e. it doesn't do something like the Avro SerDe by parsing a property).

For other formats, my recollection is that they mostly use whatever partition metadata is available and Hive eventually uses ObjectInspectorConverters to map from the partition's schema to the table's. I just checked and that does do positional evolution. I wasn't able to find any tests that cover removing columns from the middle of a table nor documentation of what the expected behavior is.

@hocanint-amzn, I left some comments on your PR. I believe you need to address changes in the order of columns, which the branch I mentioned should help with.
