### ISSUE TITLE
Use SSL for port 443 in presto-jdbc

### ISSUE THREAD

**Issue by xerial** [prestodb/presto#8577]
Since presto 0.180, presto-jdbc requires explicit SSL option like `jdbc:presto://api-presto.treasuredata.com:443/td-presto?SSL=true` for using SSL.

I still don't figure it out what kind of users want to disable SSL for port 443 access. 

If there is no specific reason, I'd like create a PR to turn on `SSL=true` by default when port 443 is used, so that we can always use the simplest URL like:
`jdbc:presto://api-presto.treasuredata.com:443/td-presto`

Any opinion?

**Comment by electrum** [comment]
When rewriting the JDBC config framework for 0.180, we removed the default SSL for port 443 in order to not have a special case. It seems cleaner not to have a special case. However, as you point out, and @dain agrees, no one will use port 443 for non-secure, so it's not harmful.

Actually fixing this would be difficult, since we don't support dynamic defaults in `ConnectionProperties`.

**Comment by electrum** [comment]
I'm open to supporting this if the code isn't horrible. We still need to support explicitly saying `SSL=false` when the port is 443 (so it needs to be a default and not always enabled).

**Comment by electrum** [comment]
The other consideration is allowing `SSLTrustStorePath` (which is only allowed to be configured if SSL is enabled). Ideally, we would allow it if the port is 443 and SSL is not explicitly enabled, but I'm fine with saying you need to explicitly say `SSL=true` in order for `SSLTrustStorePath` to be configurable.

**Comment by xerial** [comment]
@electrum Good. Thanks for the confirmation. We will create a PR for this.

**Comment by electrum** [comment]
Will be fixed in 0.193
