### ISSUE TITLE
Add quantile digest type, similar to HyperLogLog

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#8695]
Needed:

* Quantile digest type that allows casting to/from varbinary. (similar to `HyperLogLogType`)
* Aggregation functions to compute a quantile digest, weighted and unweighted, with specified accuracy. (similar to `approx_set`)
* Aggregation function to merge quantile digests. (similar to `merge` for HLL)
* Scalar function to extract percentiles from quantile digest type, with the same functionality as the existing `approx_percentitle` aggregation functions. (similar to `cardinality` for HLL)

**Comment by martint** [comment]
We need to define a serialization format similar to HLL's (https://github.com/airlift/airlift/blob/master/stats/docs/hll.md). Some of the work needs for this needs to go in airlift.

**Comment by alyssackwan** [comment]
I'm putting together a PR for this. I'm thinking the functions should be named:

- approx_qdigest
- empty_approx_qdigest
- merge
- extract_percentile

Does that sound about right?

I'm unsure how to keep the Long, Double, and Real digests from accidentally being merged. Thoughts? I'm thinking of injecting a set of typed DigestAndPercentileState classes to ensure that type information is written.

I plan on writing up the docs for both this and HLL while I'm at it. https://github.com/prestodb/presto/issues/8968

**Comment by haozhun** [comment]
It appears like no one is actively working on this issue.

I recently heard from a user, whose use case would benefit significantly from this feature.

**Comment by tdcmeehan** [comment]
I'll be working on this issue.

**Comment by tdcmeehan** [comment]
Please let me know if you have any feedback on the decisions below:

1. Given that qdigest differs from HyperLogLog in that one can **extract** an approximate value that is put in, I believe it makes sense to make this type a parameterized type, similar to array, row, etc.  The type parameter must be one of: bigint, double, real (similar to existing approx_percentile aggregations which only take these values).  Because one can cast to/from varbinary, this will be sort of like type erasure, where one could circumvent the typing if one is determined by casting to varbinary and then casting back to qdigest but with a different parameter.
2. I believe the aggregation creation function should be called `qdigest_agg`.  This is as an analog to `array_agg`, `multimap_agg`, etc, where the left part is what is returned and the right part signifies it's an aggregation.
3. If scalar creation functions are even needed, they should be called:
   * `empty_qdigest`
   * `create_qdigest`
I think it's redundant to add `approx` to these names, if we already say it returns a `qdigest`.
4. `merge`  and `extract_percentile` are named as suggested above.
5. Creation functions (scalar and aggregate) will have similar overloads to `approx_percentile`, where one can specify the accuracy.  They will also have defaults where the default value is the same as what is currently in `approx_percentile`.

CC: @haozhun, @martint

**Comment by alyssackwan** [comment]
Sorry for the late reply. I haven't seen your PR, but you could do a CAST-time check against a stored data type field to throw an exception if an attempt to erase type. Would that be enough?

**Comment by tdcmeehan** [comment]
Given that the quantile digest data structure does not have support for any type other than whole numbers, encoding the type into the `qdigest` would require us to push the Presto-specific concept of converting doubles and real numbers into sortable long values into the airlift library.  Discussing with @martint, we don't believe this is the correct approach, because it will embed those trade-offs into the library and it would forever require that support.  Ideally, the connectors would have knowledge of this type, and we wouldn't need to worry about errant casting.  The reality is different, and the best compromise seems to leave any concept of the parameterized type (and what to do with non-integral numbers) outside of the serialization format, and leave the logic of converting to/from fractional values inside Presto.
