### ISSUE TITLE
presto-server-0.179 crash    

### ISSUE THREAD

**Issue by gehaijiang** [prestodb/presto#8900]
presto 
launcher.log: 
Dumping heap to java_pid22316.hprof ...
Heap dump file created [452795761 bytes in 4.309 secs]
Terminating due to java.lang.OutOfMemoryError: Metaspace
2017-09-01T10:42:11.791+0800	INFO	main	io.airlift.log.Logging	Logging to stderr
2017-09-01T10:42:11.796+0800	INFO	main	Bootstrap	Loading configuration
2017-09-01T10:42:12.169+0800	INFO	main	Bootstrap	Initializing logging
2017-09-01T10:42:12.393+0800	INFO	main	io.airlift.log.Logging	Logging to /home/data/programs/presto-server-0.179/data/var/log/server.log
2017-09-01T10:42:12.683+0800	INFO	main	io.airlift.log.Logging	Disabling stderr output
2017-09-01T10:50:20.421+0800	INFO	main	io.airlift.log.Logging	Logging to stderr
2017-09-01T10:50:20.425+0800	INFO	main	Bootstrap	Loading configuration
2017-09-01T10:50:20.604+0800	INFO	main	Bootstrap	Initializing logging
2017-09-01T10:50:20.703+0800	INFO	main	io.airlift.log.Logging	Logging to /home/data/programs/presto-server-0.179/data/var/log/server.log
2017-09-01T10:50:20.817+0800	INFO	main	io.airlift.log.Logging	Disabling stderr output

presto config:

-server
-Xmx28G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-Xloggc:/home/data/presto/presto.gc.log
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-XX:+PrintGCDetails
-XX:+PrintGCCause
-XX:+PrintGCApplicationStoppedTime
-XX:+PrintTenuringDistribution
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError
-XX:MetaspaceSize=512M
-XX:MaxMetaspaceSize=768M
-XX:ReservedCodeCacheSize=512M
-Djava.library.path=/home/data/presto/etc/hadoop/native

**Comment by wenleix** [comment]
We have seen full GC due to Metaspace Full, and we are investigating. Metaspace Full is usually caused by too many bytecode generated classes. 

However, your case is slightly different, as it's OOM due to Metaspace Full. I am wondering if you can check the log to see if there is a Full GC happened before OOM? If not this might be an premature  OOM. One cause is the JNI critical section lock prevents the full GC, and the default retry count is only 2, see http://mail.openjdk.java.net/pipermail/hotspot-gc-dev/2017-May/019827.html for some discussion. One thing to check is "JNI Critical Section" in the GC log before OOM ?

There are two JVM parameter that might be tuned to mitigate the issue: `MetaspaceSize` and `GCLockerRetryAllocationCount`. 

 It would be great if you can find the query cause the issue, and report to us :). 

Also, if you have the full heap dump (from the log it looks like you have), is it possible to find out what are the generated classes names from the heap dump?  Thank you !!

**Comment by gehaijiang** [comment]
presto  worker   OOM 
I will analyze java heap dump

**Comment by wenleix** [comment]
@gehaijiang : You are pasting the heap usage information, while Metaspace is storing the information of loaded classes.

One way to see the loaded class from a Heap Dump is through OQL with Eclipse Memory Analyzer (VisualVM should be able to do OQL as well). See the [document](https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.mat.ui.help%2Ftasks%2Fqueryingheapobjects.html). 

Here is the `OQL` to get all the classes:
```
SELECT * 
FROM java.lang.Class
```

You can also use `WHERE` clause to filter certain class name patterns: 
```
SELECT * 
FROM java.lang.Class
WHERE toString() LIKE ".*LambdaForm.*"
```

In any case, the most efficient way to figure out root cause is to find the query to reproduce the issue so we can debug it.

Also, have you tried to increase `MaxMetaspaceSize`? Has that solved the problem?
