### ISSUE TITLE
Implement "area under ROC curve" function

### ISSUE THREAD

**Issue by martint** [prestodb/presto#9089]
Given a vector of outcomes (true/false) and scores (double), compute the area under the ROC curve. See http://blog.revolutionanalytics.com/2016/08/roc-curves-in-two-lines-of-code.html for an explanation.

This is commonly referred to as AUC or AUROCC, but I don't think that's a good name for the function. Something more explicit like `area_under_roc_curve` or `roc_curve_area` is probably better.

To be decided: whether the input is a pair of arrays (booleans, doubles) or an array of rows representing the outcome/score pairs. The latter makes more semantic sense and prevents certain illegal usages, such as arrays with different lengths.

**Comment by takuti** [comment]
Though I'm new to Presto development, can I tackle this task? @martint 

The function would be implemented at: `com.facebook.presto.operator.aggregation.AreaUnderROCCurveAggregation`.

I bet on your latter interface (i.e., array of rows) because I have experienced implementation of [AUC aggregation function for Hive](https://github.com/apache/incubator-hivemall/blob/e8abae257f45bab419654ebe2d5387755dc7f105/core/src/main/java/hivemall/evaluation/AUCUDAF.java#L91-L426) with the latter interface. 

More concretely, for the following table:

| score<br/>(probability) | label |
|:---:|:---:|
| 0.5 | 0 |
| 0.3 | 1 |
| 0.2 | 0 |
| 0.8 | 1 |
| 0.7 | 1 |

our expectation is that users can compute AUC of the data as:

```sql
select
  area_under_roc_curve(score, label) as auc
from (
  select score, label
  from data
  ORDER BY score DESC
) t;
```

> 0.83333

Since ordering records by score is a key part of AUC computation, I put `ORDER BY` and make sure input rows are preliminarily sorted.

Or, of course Presto only does in-memory computation, so taking another approach:

```sql
select area_under_roc_curve(score, label) as auc from data
``` 

which internally holds sorted list of `<score, label>` pairs might be possible.

**Comment by martint** [comment]
The function should take care of any ordering required internally. That shouldn't be something users  have to be concerned with. In any case, in the first example, the ORDER BY in the subquery is meaningless from a SQL semantics perspective. The engine is free to remove that clause.

**Comment by takuti** [comment]
Thanks for your response. Sure, I'll start working on it in that perspective.

**Comment by peacej** [comment]
This function would be very helpful, any plans to implement?

**Comment by ajaech** [comment]
@peacej  I agree. I wonder if someone can reopen the issue so it gets more visibility
