### ISSUE TITLE
NPE when reading hive table (in parquet) on certain columns

### ISSUE THREAD

**Issue by l1990790120** [prestodb/presto#9172]
Very similar to this issue - https://github.com/prestodb/presto/issues/3827, but even after I set `hive.parquet.use-column-names=true` and restart and I still get NPE when querying certain columns. When querying on hive however, I could see those columns just fine. 

On presto 0.17/ emr 5.8

**Comment by nezihyigitbasi** [comment]
Which Presto version are you using? Did you try the latest version? Also more info such as the stacktrace and some test Parquet file to reproduce the problem would be useful.

**Comment by himanshurawatgh** [comment]
Hi There , was this issue fixed . I am having hard time querying parquet files in S3 . Just for one column and obviously for select * queries fail with NPE . Athena and HIVE both work just fine .
Also realized when I give columns name , columns are just not in place 
for example 
Select city , state , country errors out -- (because of city being there for some reason).
Select state , country I could see many of values in state , which should be present in city .

**Comment by ryanrupp** [comment]
@himanshurawatgh did you set `hive.parquet.use-column-names=true` (resolution from the linked issue https://github.com/prestodb/presto/issues/3827#issuecomment-150987051) - because your issue sounds like that (where you're getting data returning in the incorrect column). Athena has this enabled by default for Parquet files which is probably why it works there.

Alternatively, if you do not enable that you need to have the Hive metadata column order match the Parquet file (it does index based reads).

More discussion on this functionality here - https://github.com/prestodb/presto/issues/8911

**Comment by himanshurawatgh** [comment]
@ryanrupp  yes i did . Below is my hive.properties:
hive.metastore-refresh-interval=1m
connector.name=hive-hadoop2
hive.metastore.uri=thrift://ip-xxxxxxx..xxx..xxx..xxx:9083
hive.metastore-cache-ttl=20m
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
hive.non-managed-table-writes-enabled = true
hive.s3-file-system-type = EMRFS
hive.hdfs.impersonation.enabled = true
hive.parquet.use-column-names = true

Additionally : 
select count(*)  from table_name where  Year = '2017' 
and month='04' and country ='' -- output is zero . when we query this partition in presto it just works fine because there are no '' values for city (first column of parquet file). 


select count(*)  from table_name where
Year = '2018'  and month='04' and day ='05'  and city='' ;  -- Output non zero . -- Querying this partition with presto fails with null pointer exception .
Some how both Athena(impliments presto at backend)  and hive are picking up right values .

**Comment by himanshurawatgh** [comment]
Can anyone tell me how do I set hive.parquet.use-column-names=true.
when setting this in hive.properties , this does not shows up in show session . and when setting this up in session , presto gives not a valid property . I have also tried hive.parquet.use_column_names=true , this does not works either . Also looking at other forums .

**Comment by nezihyigitbasi** [comment]
`hive.parquet.use-column-names` should be put in `hive.properties` under catalog directory. There is no session property that does the same that's why you get a property not valid error, also nothing will show up in session properties when you set this in `hive.properties`.  When Presto starts it prints out all the config properties, you can search for `hive.parquet.use-column-names` to verify that it's picked up.
