### ISSUE TITLE
Increase the xmx for testing worker?

### ISSUE THREAD

**Issue by BlueStalker** [prestodb/presto#9239]
According to https://travis-ci.org/prestodb/presto/jobs/294343811
I think the presto worker has no memory to allocate, see line 5055:
presto-worker_1       | Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000cc400000, 174063616, 0) failed; error='Cannot allocate memory' (errno=12)

**Comment by findepi** [comment]
@BlueStalker I agree, we're sometimes trying to allocate more memory than available to JVM during Travis build.
However, you can't just increase Xmx (and this is not always about heap size btw), because you have limited amount of total memory for all processes.
Having said that, why don't you make a PR with proposed configuration change and give it several rounds on Travis to ±verify it solves the problem?
