### ISSUE TITLE
Offload the backup shard cleanup to the ShardCleaner in Raptor when rolling back a transaction

### ISSUE THREAD

**Issue by jessesleeping** [prestodb/presto#9321]
Currently in Raptor, when rolling back a transaction, each worker will do a [synchronous cleanup](https://github.com/prestodb/presto/blob/4d4c1919a839301562794f0ecd6f5c369e86b60f/presto-raptor/src/main/java/com/facebook/presto/raptor/storage/OrcStorageManager.java#L663) to the uncommitted backup shards. An alternative way is to skip the synchronous cleanup and let the `ShardCleaner` [discover](https://github.com/prestodb/presto/blob/2bbdb43542044edcbb6cde8dd90af4a784087a2f/presto-raptor/src/main/java/com/facebook/presto/raptor/metadata/ShardCleaner.java#L239) and [delete](https://github.com/prestodb/presto/blob/2bbdb43542044edcbb6cde8dd90af4a784087a2f/presto-raptor/src/main/java/com/facebook/presto/raptor/metadata/ShardCleaner.java#L270) those shards asynchronously. The pros and cons of the asynchronous approach are:

Pros:
- Having a central point of control over the delete rate to the backup storage. The # threads used for background cleanup is configurable [here](https://github.com/prestodb/presto/blob/fc72ac5736e60ae2ada57f97e7932cdfd3e808bc/presto-raptor/src/main/java/com/facebook/presto/raptor/metadata/ShardCleanerConfig.java#L37). We have seen issues that several consecutive rollbacks caused a burst in delete rate which overloaded the backup store. By adjusting the # of cleaner threads we can smooth the delete rate.
- Freeing a slot in the query queue immediately after a rollback. We have seen abandoned queries keeps running for over 30 minutes cleaning up backup shards. 

Cons:
- May not free up backup storage space in time. The current background cleanup logic waits for a while before actually deleting the shard from the backup store.
- Can cause deletion lag when the coordinator or the backup storage cannot catch up with the delete rate.

To mitigate the first drawback, we can modify the backup cleanup logic to delete abandoned shards immediately. To deal with the second one, we can closely monitor the deletion lag on the coordinator, which we have already done.

Any thoughts?

cc @electrum @AlekseiS

**Comment by electrum** [comment]
We did this intentionally so that you don’t build up a huge deletion queue without any pushback. Otherwise, you can have a situation where the things fail repeatedly and you fill up the backup store to the point where it takes much longer to recover.

The fact that it slows down is a feature.

**Comment by electrum** [comment]
Deleting abandoned files immediately is not trivial. You would need to keep track of that state, which isn’t done today. Also, you need to keep them in the deletion queue until the timeout, unless they are successfully deleted, since someone could still be writing them (just because you fail/poison the transaction doesn’t mean the work isn’t still being done). That’s one of the reasons we have a delay.

**Comment by electrum** [comment]
The concern about controlling the number of threads is valid. This could be moved to use the backup manager thread pool, so that deletions won’t use additional threads and write operations will need to wait behind deletions.

However, there is still the issue of back pressure. If we have failed workers queue their deletions, the queue could grow without bound, especially if queries are cancelled and retried externally (made worse if they have a timeout).

A different approach is to block or fail deletion and insert queries (in the coordinator) if the deletion queue is too large.

**Comment by electrum** [comment]
Reopening this as the current design will fail read queries when the backup store is having problems, which is not the intended behavior.
