### ISSUE TITLE
Presto BOM for development outside the tree

### ISSUE THREAD

**Issue by hgschmie** [prestodb/presto#9489]
A BOM (bill of materials) POM similar to https://github.com/dropwizard/dropwizard/blob/master/dropwizard-bom/pom.xml would allow a project developed outside the presto tree to import the bom similar to (for dropwizard):

```xml
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

and thus match all dependency versions as the corresponding presto build. 

would you consider such a patch for inclusion? It would contain:

- pulling the dependencyManagement section from the root pom into a `presto-bom` submodule.
- rewrite all existing sub-projects to import the bom and no longer use the root dependencyManagement section.

**Comment by electrum** [comment]
This would be very useful for us (Facebook) since we have many internal plugins for Presto and have to manually keep the dependencies in sync. I was aware of BOM / import scope but had never considered using it for this purpose. Please do send a patch!

I am curious about the motivation. One of the features and goals of the Presto plugin architecture is that the class loader isolation lets you use whatever versions of dependencies you need, with the exception of a few, hopefully stable dependencies that are part of the SPI. Although that doesn't work if you want to use the helper libraries such as `presto-plugin-toolkit`, `presto-record-decoder`, so I can see the usefulness there, too.

**Comment by electrum** [comment]
And the fact that you need basically all of Presto if you want to use the standard code for connector or function integration tests. So this is definitely useful.
