### ISSUE TITLE
Is it possible to allow JDBC readonly to be optional

### ISSUE THREAD

**Issue by TedBear42** [prestodb/presto#9507]
Just wondering about the following line.

https://github.com/prestodb/presto/blob/master/presto-base-jdbc/src/main/java/com/facebook/presto/plugin/jdbc/BaseJdbcClient.java#L258

Is there any use case that benefit from this being optional.  I know that currently this line prevents queries from working on cockroachdb because it doesn't currently support read only mode.

**Comment by findepi** [comment]
@TedBear42 in https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#setReadOnly-boolean- i read 
> Puts this connection in read-only mode as a hint to the driver to enable database optimizations.

which suggests a no-op implementation (except of storing the flag for inspection with `isReadOnly()`) would be almost sufficient. Is there any reason why CockroachDB driver doesn't implement this? :)

**Comment by TedBear42** [comment]
They have a open PR to fix the issue [#20547](https://github.com/cockroachdb/cockroach/pull/20547)

So maybe it isn't needed, unless there would ever be a desire to insert with presto over JDBC.

**Comment by findepi** [comment]
@TedBear42 
Connectors extending `presto-base-jdbc` (the module you linked to) are not read-only. E.g. you _write_ with those connectors using `CREATE TABLE .. AS SELECT ..` statement (`INSERT` works probably too).
In those cases, however, different code path is used, and `Connection` is not brought into read-only mode.

Since https://github.com/cockroachdb/cockroach/pull/20547 looks like work-heavily-in-progress, let me close this.
