### ISSUE TITLE
How to parse a timestamp like "2017-01-14T19:08:14.529274000"?

### ISSUE THREAD

**Issue by watsonpeng** [prestodb/presto#9541]
parse_datetime(mytime, 'yyyy-MM-ddThh:mm:ss.f') does not work: Illegal pattern component: T.

Is there a way to escape the character T, which is for 24 hour time format?

**Comment by akshatnair** [comment]
This function uses http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html
as mentioned in the docs https://prestodb.io/docs/current/functions/datetime.html
You will have to use HH instead of hh for 24 hours

**Comment by watsonpeng** [comment]
Let me clarify my question.  AWS Athena uses presto data types.  As Athena is a managed AWS service, we cannot add other libraries.  Therefore, we need to parse the datetime like 2017-01-22T22:26:09.000200000 using only the capabilities provided by Presto.  For example, if the datetime is "2/14/2017 7:31:35 PM", I would do parse_datetime(my_column, 'MM/dd/yy hh:mm:ss a').

For this issue, as I understand it, %T is for 24 hour time format.  Unfortunately the datetime "2017-01-22T22:26:09.000200000" has a T in it.  How would I parse it using Presto?

**Comment by ryanrupp** [comment]
T is a literal value indicating the start of the time portion of a datetime rather than any special formatting indicator for Joda. In the Joda format, literal values are specified with a single quote but because in the SQL you are already surrounding the date format with single quotes, you need to escape the value with an additional single quote e.g.:

`
select parse_datetime('2017-01-22T22:26:09.002', 'yyyy-MM-dd''T''HH:mm:ss.SSS')
`

I'm not sure Joda supports nanosecond precision in the format so you may have to take the substring or something along those lines.

**Comment by watsonpeng** [comment]
Escaping the literal T with two single quotes works perfectly.  I didn't think of that; I tried double quotes.

**Comment by electrum** [comment]
The built-in function `from_iso8601_timestamp()` will work for this.
