### ISSUE TITLE
Add sequence variant for DATE

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#9681]
Currently, it only supports `TIMESTAMP`, but this is means when you pass a `DATE` you get back a `TIMESTAMP`, which is unexpected.

For the `INTERVAL_YEAR_TO_MONTH` variant, there is no question about how it should behave.

For `INTERVAL_DAY_TO_SECOND`, the expected behavior is less clear when the interval has a fractional day part. There seem to be two choices:

* Consider fractional day parts as illegal and fail.
* Compute with greater precision internally and truncate to days. Example: `sequence(date '2018-01-01', date '2018-01-04', interval '18' hour) -> ['2018-01-01', '2018-01-01', '2018-01-02', '2018-01-03', '2018-01-03']`

All of the existing tests for the timestamp variant only cover whole days. These tests should be used for the new date variant, and new timestamp tests written that cover fractional days.

**Comment by haozhun** [comment]
I find the second choice you proposed here quite unintuitive. I think the first choice is far better.

**Comment by haozhun** [comment]
I discussed with @martint. There are a few arguments against option 2:

* It is surprising in general
* In the cases where this semantics is intended, one can use a timestamp and then truncate explicitly
* We generally prefer a choice that is more conservative because we'll have the choice to extend allowed inputs. But the other way around is much harder.

**Comment by electrum** [comment]
I also support option 1, but I listed both for completeness and to promote this discussion.

**Comment by haozhun** [comment]
Fixed in #10077
