### ISSUE TITLE
Feature Request: JDBC connector for catalog backends to any RDBMS like system

### ISSUE THREAD

**Issue by HariSekhon** [prestodb/presto#9703]
Feature Request for a JDBC catalog connector to be able to connect to any JDBC / RDBMS like system.

I have checked the 0.191 document and cannot see a JDBC catalog connector:

https://prestodb.io/docs/current/connector.html

This feature is available in the Apache Drill distributed SQL solution and seems like it would give maximum flexibility to connect to any JDBC data source (such as Oracle for which there isn't a connector yet):

https://drill.apache.org/docs/rdbms-storage-plugin/

Thanks

Hari

**Comment by electrum** [comment]
The MySQL, PostgreSQL, etc., connectors are built on a base connector `presto-base-jdbc`. In theory, it would be easy to have a generic connector that takes a JDBC URL as configuration and lets you drop in a JDBC driver and go. Unfortunately, every database is different and requires knowledge of those differences in the connector, so it would require coming up with config options for all of those, then expecting users to set them correctly.

We prefer to ship connectors that are well-tested and work out-of-the-box which is why we have specific connectors for popular databases.

It's easy to add a new JDBC-based connector for any database. The difficulty with Oracle is that they do not allow redistributing the driver (compared to the SQL Server driver which is open source under the MIT license). However, we could ship an Oracle connector with the caveat that users will need to add the driver JAR themselves when deploying Presto. We're happy to accept a Pull Request that does this.

**Comment by electrum** [comment]
If there are other databases you are interested in having a connector for, please file an issue or send a Pull Request.

**Comment by tooptoop4** [comment]
https://github.com/prestosql/presto/pull/3105

**Comment by RugratsJ** [comment]
@tooptoop4, do we have a similar generic JDBC connector for PrestoDB since internal functions are different for prestosql and prestodb.
