### ISSUE TITLE
Is not the name "Local File Connector" misleading? 

### ISSUE THREAD

**Issue by sandeep1995** [prestodb/presto#9757]
Since this connector only able to connect to pestro's HTTP request logs "Presto Log File Connector" name makes more sense here.

Is there any ready made CSV, TSV or JSON connector?

**Comment by findepi** [comment]
Yes, the name (IMO) is misleading.

> Is there any ready made CSV, TSV or JSON connector?

Depends where the files are located. Eg. If you have CSV/TSV files HDFS or S3, you can use Hive connector to read them. You will need to have Hive Metastore and define mapping for the files using `hive`, because Presto won't let you set all the required serde properties.

If you files are on local disk, then no, there isn't such a connector (Presto is a distributed query engine after all). However, you may run Hadoop with local disk acting as HDFS. (Not recommended for anything other than local dev/testing)

**Comment by mariusa** [comment]
If you agree the name is misleading, would please re-open the request leave it open until connector is renamed?
I also expected this reads CSV files.

**Comment by sandeep1995** [comment]
Yeah please keep the issue open.

**Comment by rongrong** [comment]
While misleading, I can imagine renaming could be quite inconvenient for some people already using it. Not sure the benefits justifie cost here.

**Comment by pankaj358** [comment]
can anyone guide for json-connector for presto?

**Comment by tanero** [comment]
> can anyone guide for json-connector for presto?

json file support would be great, without hadoop,  worker and coordinators access the files on shared network storage.
