### ISSUE TITLE
Optimize table scan for partitioned table where predicate is known that it selects no partition

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#9822]
Currently (just before release 193), when your predicates matches exactly partitioning column type planner is able to optimize table scan if such predicate selects no partition, see:
```
presto:tiny> explain select * from orders where orderstatus = 'u';
                                                                                                                                              Query Plan
--------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[orderkey, custkey, orderstatus, totalprice, orderdate, orderpriority, clerk, shippriority, comment] => [orderkey:bigint, custkey:bigint, orderstatus
         Cost: {rows: 0, bytes: ?}
     - Values => [orderkey:bigint, custkey:bigint, orderstatus:varchar(1), totalprice:double, orderdate:date, orderpriority:varchar(15), clerk:varchar(15), sh
             Cost: {rows: 0, bytes: ?}
```

But if there is anything more complicated like casting of constant then it does not work:
```
presto:tiny> explain select * from orders where orderstatus = 'unknown';

--------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[orderkey, custkey, orderstatus, totalprice, orderdate, orderpriority, clerk, shippriority, comment] => [orderkey:bigint, custkey:bigint, orderstatus
         Cost: {rows: 7500, bytes: ?}
     - RemoteExchange[GATHER] => orderkey:bigint, custkey:bigint, orderstatus:varchar(1), totalprice:double, orderdate:date, orderpriority:varchar(15), clerk:
             Cost: {rows: 7500, bytes: ?}
         - ScanFilter[table = tpch:tpch:orders:sf0.01, originalConstraint = (CAST("orderstatus" AS varchar(7)) = 'unknown'), filterPredicate = (CAST("ordersta
                 Cost: {rows: 15000, bytes: ?}/{rows: 7500, bytes: ?}
                 clerk := tpch:clerk
                 orderkey := tpch:orderkey
                 orderstatus := tpch:orderstatus
                     :: [[F], [O], [P]]
                 totalprice := tpch:totalprice
                 custkey := tpch:custkey
                 comment := tpch:comment
                 orderdate := tpch:orderdate
                 shippriority := tpch:shippriority
                 orderpriority := tpch:orderpriority
```
In above query there is full table scan with filter that filters out all the rows. However it is known that there is no `unknown` partition among `F, O, P` partitions.

**Comment by martint** [comment]
This is already supported by the engine, but the plugin needs to cooperate. The call to getTableLayouts() receives a constraint the connector can call to determine whether a given combination of bindings would result in the expression short-circuiting to false.

**Comment by findepi** [comment]
@martint that's try that `getTableLayouts()` received sufficient information, but at least Hive connector doesn't seem to cooperate.
Our testing shows that table elimination to values that is supposed to happen in `AddExchanges` (https://github.com/prestodb/presto/blob/ce6744c6ea859bfb5c00ef5251e71e277f84acb2/presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/AddExchanges.java#L599) started to be effectively only now, that `PickTableLayout` is run (roughly equivalent to running `AddExchanges` twice). It's because `PickTableLayout` pass narrows down the `TupleDomain` and on the second pass `MetadataMenager` (https://github.com/prestodb/presto/blob/3c17fd330a54906ab7ba33b04a8c6de628280af6/presto-main/src/main/java/com/facebook/presto/metadata/MetadataManager.java#L310) is able to short-circuit... 
This sounds very incidental (which is bad), but the good side is that connector doesn't need to cooperate that much.

**Comment by findepi** [comment]
long story short, hive connector lacks something like https://github.com/prestodb/presto/pull/9825
