### ISSUE TITLE
Flaky test: TestTpchDistributedStats.testValues()

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#9846]
Entire test output is [here](https://gist.githubusercontent.com/nezihyigitbasi/261c563d2591e4b649ec8ef85129df37/raw/983cc31e929a8fbbd4476317af974bf5ae3c98ce/gistfile1.txt).

```
[ERROR] Tests run: 2122, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2,173.575 s <<< FAILURE! - in TestSuite
[ERROR] testValues(com.facebook.presto.tests.TestTpchDistributedStats)  Time elapsed: 0.037 s  <<< FAILURE!
java.lang.AssertionError: Following metrics do not match: Metric [OUTPUT_ROW_COUNT] - estimated: [1.0], real: [UNKNOWN] - plan node: [com.facebook.presto.sql.planner.plan.OutputNode@2b575894] expected [true] but found [false]
	at com.facebook.presto.tests.TestTpchDistributedStats.testValues(TestTpchDistributedStats.java:104)
```

**Comment by findepi** [comment]
@nezihyigitbasi , this is because `StatisticsAssertion` uses `StageInfo`'s `PlanNodeStats` to obtain actual values (such as row count) and this appears to be inaccurate.
I have a commit changing `StatisticsAssertion` so that it computes actual values directly (e.g. by issuing `count(*)` query), will place a PR soon.

**Comment by kokosing** [comment]
The fix is on the way, it is stored somewhere here: https://github.com/prestodb/presto/pull/9788. Currently actual (real) stats are extracted from the query execution statistics, then we refactored that to wrap the query in some kind of aggregation query which collects such stats. For example `VALUES 1` will be wrapped with (`SELECT count(*), max(a), min(a) FROM (VALUES 1) t(a)`)
