### ISSUE TITLE
Partial query failure recovery

### ISSUE THREAD

**Issue by martint** [prestodb/presto#9855]
# Goals

* Reduce user-visible errors when certain kinds of failures occur and make it possible to trade off between observable errors and latency.
* Allow the engine to "preempt" tasks to overcome skew, resource over-allocation, etc.
* Pave the way to granular checkpointing and recovery, workload migration, etc.

# Ideas and considerations

* Find the transitive closure of tasks/stages that need to be restarted. Given a task failure...
   1. If the task has no observable output, include it.
   2. If the task has consumed input that needs to be recomputed, repeat 1 for each of its sources.
   3. If the task has observable output, repeat 1 for each downstream task
* TODO: refine for bucket-by-bucket execution or other forms of vertical partitioned executions.

* Need to be able to account all "wasted" resources (cpu, bytes read, etc.) due to restarts.

**Comment by sopel39** [comment]
Additonally the client needs to be aware of query checkpointing (if the data is not buffered at sinks between checkpoints). Otherwise once the some rows are consumed you cannot easily restart any part of a query.  

There is another interesting idea that might be relatively simple to incorporate into Presto. One could use external mechanism for synchronously checkpointing Presto cluster. Particularly I was thinking about CRIU (https://criu.org/Main_Page). In that case coordinator could periodically:
* suspend the cluster
* take snapshots of Presto processes on all nodes and dump snapshots to shared distributed storage
* resume the cluster and inform sinks and clients about new epoch so that they can commit data.

Obviously checkpointing of Presto process (and it's memory) might take considerable time so such checkpoints shouldn't be too frequent (e.g: once an hour/few hours). Such approach would be suitable for clusters which are dedicated for long queries (e.g: from hour to 24 hours). I think for short queries (few secs, mins) checkpointing might not matter much because the client can just restart the query (and probability of failure during single query is low) Therefore checkpoining overhead/latency might not be required. Of course this is trade-off between reliability and latency.

There is also another nice twist of Presto cluster suspend/resume feature support. AWS recently introduced spot instance hibernation on terminate. Therefore on Presto node termination one cloud suspend the cluster and restart the worker on another node without any (long) queries failing.

Additionally, with CRIU checkpoining and prepartiotioning one could migrate workers to larger/more nodes.

What do you think? I definitely see how such suspend/resume/checkpoint could be incorporated into Presto without major system rewrite.

**Comment by martint** [comment]
> Additonally the client needs to be aware of query checkpointing (if the data is not buffered at sinks between checkpoints). Otherwise once some rows are consumed you cannot easily restart any part of a query.

Indeed. That's capture by the "no observable output" references above.

> What do you think? I definitely see how such suspend/resume/checkpoint could be incorporated into Presto without major system rewrite.

It could be valuable to do checkpointing. It doesn't need to be an all-or-nothing, though. It could be selective and adaptive based on relative cost of different stages of a query. For instance, a highly selective filter that uses a lot of computation could benefit from it.

Regardless, checkpointing is somewhat orthogonal to being able to restart parts of a query. The latter (in some form) is a partial pre-requisite to being able to reason about checkpointing.

**Comment by voycey** [comment]
I think at this point anything that can prevent a full query restart would be preferable, whether that is checkpointing based on stages or even some kind of automated bucketing with snapshots to allow them to be re-started if on a failed node.

How far down the line is this looking on the roadmap?

**Comment by jaystarshot** [comment]
Since trino has task and query retry logic - [here](https://trino.io/docs/current/admin/fault-tolerant-execution.html) . Should we make a plan and port those changes / implement ourselves in presto?
