### ISSUE TITLE
Avoid shuffling entire map with semi join + or condition

### ISSUE THREAD

**Issue by highker** [prestodb/presto#9861]
Consider the following query:
```
SELECT checksum(interaction_actor_id)
FROM <some_table1>
WHERE ds = '2016-03-03'
AND (
    content_actor_id IN (
        SELECT id FROM <some_table2>
    )
    OR
    TRY_CAST(some_map[map_col] AS BIGINT) IN (
        SELECT user_id FROM <some_table3>
    )
);
```

The distributed query plan is:
```
...
 Fragment 2 [HASH]
     ...
                 expr_7 := TRY_CAST("some_map"[CAST('map_col' AS varchar)] AS bigint)
             - SemiJoin[...] => [..., content_data:map(varchar, varchar), ...]
                 - RemoteSource[3] => [..., some_map(varchar, varchar), ...]
                 ...

 Fragment 3 [SOURCE]
     Output layout: [..., some_map, ...]
     ...
     - ScanProject[table = ... some_map(varchar, varchar) ...]
             ...
             some_map := HiveColumnHandle{..., ...
...
```

We shouldn't shuffle the entire map `some_map`.

**Comment by findepi** [comment]
In other words, the `TRY_CAST(some_map[map_col] AS BIGINT)` projection should be done just above (or directly in) a table scan form `<some_table1>`, right?

**Comment by highker** [comment]
@findepi yes. Only part of `some_map` should be serialized over the wire.

**Comment by sopel39** [comment]
Why does `OR` matters? Does it also happens with just `TRY_CAST(some_map[map_col] AS BIGINT) IN (SELECT user_id FROM <some_table3>)`. It makes me wonder if this isn't a bug. What if other entries of map (non `map_col`) differ?

Could you post entire plan?

**Comment by highker** [comment]
@sopel39, (1) the predicate will be pushed down without `OR` and (2) there you go
```
SELECT checksum(interaction_actor_id)
FROM <table1>
AND (
    content_actor_id IN (
        SELECT user_id FROM <table2>
    )
    OR
    TRY_CAST(some_map['map_key'] AS BIGINT) IN (
        SELECT user_id FROM <table2>
    )
);
```
```
SELECT checksum(interaction_actor_id)
FROM <table1>
AND (
    content_actor_id IN (
        SELECT user_id FROM <table2>
    )
    OR
    TRY_CAST(some_map['map_key'] AS BIGINT) IN (
        SELECT user_id FROM <table2>
    )
);

Fragment 0 [SINGLE]
     Output layout: [checksum]
     Output partitioning: SINGLE []
     Execution Flow: UNGROUPED_EXECUTION
     - Output[_col0] => [checksum:varbinary]
             _col0 := checksum
         - Aggregate(FINAL) => [checksum:varbinary]
                 checksum := "checksum"("checksum_22")
             - LocalExchange[SINGLE] () => checksum_22:bigint
                 - RemoteSource[1] => [checksum_22:bigint]


Fragment 1 [HASH]
     Output layout: [checksum_22]
     Output partitioning: SINGLE []
     Execution Flow: UNGROUPED_EXECUTION
     - Aggregate(PARTIAL) => [checksum_22:bigint]
             checksum_22 := "checksum"("interaction_actor_id")
         - FilterProject[filterPredicate = ("expr_6" OR "expr_16")] => [interaction_actor_id:bigint]
             - Project[] => [interaction_actor_id:bigint, expr_6:boolean, expr_7:bigint, expr_16:boolean]
                 - SemiJoin[expr_7 = user_id_8][$hashvalue, $hashvalue_29] => [interaction_actor_id:bigint, expr_6:boolean, expr_7:bigint, $hashvalue:bigint, expr_16:boolean]
                     - RemoteSource[2] => [interaction_actor_id:bigint, expr_6:boolean, expr_7:bigint, $hashvalue:bigint]
                     - LocalExchange[SINGLE] () => user_id_8:bigint, $hashvalue_29:bigint
                         - RemoteSource[5] => [user_id_8:bigint, $hashvalue_30:bigint]

 Fragment 2 [HASH]
     Output layout: [interaction_actor_id, expr_6, expr_7, $hashvalue_28]
     Output partitioning: HASH [expr_7][$hashvalue_28]
     Execution Flow: UNGROUPED_EXECUTION
     - Project[] => [interaction_actor_id:bigint, expr_6:boolean, expr_7:bigint, $hashvalue_28:bigint]
             $hashvalue_28 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("expr_7"), 0))
         - Project[] => [interaction_actor_id:bigint, expr_6:boolean, expr_7:bigint]
                 expr_7 := TRY_CAST("some_map"[CAST('map_key' AS varchar)] AS bigint)
             - SemiJoin[content_actor_id = user_id][$hashvalue_23, $hashvalue_25] => [interaction_actor_id:bigint, content_actor_id:bigint, some_map:map(varchar, varchar), $hashvalue_23:bigint, expr_6
                 - RemoteSource[3] => [interaction_actor_id:bigint, content_actor_id:bigint, some_map:map(varchar, varchar), $hashvalue_23:bigint]
                 - LocalExchange[SINGLE] () => user_id:bigint, $hashvalue_25:bigint
                     - RemoteSource[4] => [user_id:bigint, $hashvalue_26:bigint]

 Fragment 3 [SINGLE]
     Output layout: [interaction_actor_id, content_actor_id, some_map, $hashvalue_24]
     Output partitioning: HASH [content_actor_id][$hashvalue_24]
     Execution Flow: UNGROUPED_EXECUTION
     - Project[] => [interaction_actor_id:bigint, content_actor_id:bigint, some_map:map(varchar, varchar), $hashvalue_24:bigint]
             Cost: {rows: 0, bytes: ?}
             $hashvalue_24 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("content_actor_id"), 0))
         - Values => [interaction_actor_id:bigint, content_actor_id:bigint, some_map:map(varchar, varchar)]
                 Cost: {rows: 0, bytes: ?}

 Fragment 4 [SOURCE]
     Output layout: [user_id, $hashvalue_27]
     Output partitioning: HASH (replicate nulls and any) [user_id][$hashvalue_27]
     Execution Flow: UNGROUPED_EXECUTION
     - ScanProject[table = <some_cat>:<some_schema>:<table2>, originalConstraint = true] => [user_id:bigint, $hashvalue_27:bigint]
             $hashvalue_27 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("user_id"), 0))
             LAYOUT: ira.<table2>
             user_id := HiveColumnHandle{name=user_id, hiveType=bigint, hiveColumnIndex=0, columnType=REGULAR}

 Fragment 5 [SOURCE]
     Output layout: [user_id_8, $hashvalue_31]
     Output partitioning: HASH (replicate nulls and any) [user_id_8][$hashvalue_31]
     Execution Flow: UNGROUPED_EXECUTION
     - ScanProject[table = <some_cat>:<some_schema>:<table2>, originalConstraint = true] => [user_id_8:bigint, $hashvalue_31:bigint]
             $hashvalue_31 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("user_id_8"), 0))
             LAYOUT: ira.<table2>
             user_id_8 := HiveColumnHandle{name=user_id, hiveType=bigint, hiveColumnIndex=0, columnType=REGULAR}
```

**Comment by martint** [comment]
The issue here is about whether to push a projection (`try_cast(some_map['map_key'] as BIGINT)` below the first semi-join (`content_actor_id in ...`). In general, it is hard to tell whether this is more productive than not doing it. It depends on how selective the semi-join is, how big are the maps and how costly it is to read a value from the map. 

There's also the question of whether the resulting plans are semantically equivalent. For expressions that can fail for some inputs, evaluating them before the semi-join would change the meaning of the query. This is related to https://github.com/prestodb/presto/issues/3232. As a sidenote, evaluating the try_cast can get very expensive when the proportion of rows that fail vs the ones that succeed is large (due to exception throw-catch)

**Comment by yingsu00** [comment]
@martint 
1. On the correctness, do you see any problem in this specific issue, ie. push down the projection on a map to below the semi-join with some OR clause? It seems correct for me, since what we need from the map is just part of the map and it's semantically the same if we shuffle the whole map or not.

2. Performance wise, it's not always good to push down a projection, but this specific case should be able to benefit. 

3. I see we're scanning the table2 twice to read the same user_id. Given the storage is remote and IO bandwidth is very limited this may cause big resource waste and perf regression. Any idea or plan how we want to address it in the future?

**Comment by yingsu00** [comment]
@findepi I heard from @highker that your team is interested in taking this task. Please feel free to do so.

**Comment by findepi** [comment]
> I see we're scanning the table2 twice to read the same user_id. Given the storage is remote and IO bandwidth is very limited this may cause big resource waste and perf regression. Any idea or plan how we want to address it in the future?

@yingsu00 , in the original report there were `<some_table2>` and `<some_table3>` but i understand the two are actually the same table. This is not obvious the table can be read once. 
Please create separate issue about this, so that there is a place for a focused discussion about this.

**Comment by highker** [comment]
@findepi, I used to find a query using CTE:
```
table1 = table2 X table2
table2 = table3 X table3
table3 = table4 X table4
...
```
which directly causes exponentially blow up.

**Comment by findepi** [comment]
> There's also the question of whether the resulting plans are semantically equivalent. For expressions that can fail for some inputs, evaluating them before the semi-join would change the meaning of the query. 

Isn't this exactly the problem with `try_cast(some_map['map_key'] as BIGINT)`. Forgive my ignorance, but doesn't that mean `apply(some_map['map_key'], value -> try_cast(value as BIGINT))`? If i parse this correctly, this can fail since `some_map['map_key']` can fail if `'map_key'` is not a key in the map.

For this to be pushdownable, we would need to have something like a `Future` (either result or error; i don't mean any concurrency). Table scan could evaluate projection like `future := CompletableFuture.supply(() -> <expression>)`. Then, filter condition would be `..... OR future.get() IN .....`. This way projection was effectively pushed down, but query semantics maintained. 
(Of course, @martint remark in https://github.com/prestodb/presto/issues/9861#issuecomment-362026652 about performance risk if there often are exceptions still holds.)

Without that, we could enable pushdown for expressions behind OR which are known not to throw. `some_map['map_key']` isn't such an expression, but this might be useful in other situations. (Of course, we would need to develop a notion of exception-free expressions in the planner.)
