### ISSUE TITLE
GroupTypedHistogram Followups

### ISSUE THREAD

**Issue by rash67** [prestodb/presto#9888]
1. remove single case and profile to make sure we can use the grouped only approach
2. remove short-lived inner class objects to reduce GC pressure in GroupTypedHistogram (have prototype locally)

**Comment by wenleix** [comment]
The second item sounds really great.

Also, have you today the serializedType for histogram is the same as output type, which is a map: https://github.com/prestodb/presto/blob/50f552d557c0dc12f03c07819bc3d7d1a8d63e7b/presto-main/src/main/java/com/facebook/presto/operator/aggregation/histogram/Histogram.java#L91. It might be worthwhile to benchmark how `Array(Row(KeyType, BIGINT))` as the serialized type performs. The reason is today in Presto, MapBlock will eagerly construct the hash table eagerly.

**Comment by wenleix** [comment]
Another random thought is today  in the combine phase, each "scratchState" is deserialized then immediately merged. Not sure if it make sense to make the combine function itself to "deserialize and merge".

While this exists for all aggregation functions, flattening the aggregation state might make this issue standout, since deserializing  into "flatten" state -- often use array to simulate link list -- tend to be more expensive than just copy the data from block to another BlockBuilder.
